/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/storybook/Footer.meta.ts`
 */

import type { StoryContext, Renderer } from 'storybook/internal/types';
import { within } from 'storybook/test';
import { checker } from './utilities';
export const footerMeta = {
  tags: ['autodocs'] as string[],
  title: 'Footer',
  args: {
    ariaLabel: 'footer',
    dataTestId: 'footer',
  },
  argTypes: {
    ariaLabel: {
      control: 'text',
      description: 'Accessible name for the `<footer>` landmark.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    ariaLabelledBy: {
      control: {
        disable: true,
      },
      description:
        'Points to the id of an element that labels the footer. Preferred over `ariaLabel` when a visible heading exists. Maps to `aria-labelledby`.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    className: {
      control: {
        disable: true,
      },
      description: 'CSS classes to apply.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    id: {
      control: {
        disable: true,
      },
      description: 'Optional id for linking/targeting and aria references.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    dataTestId: {
      control: {
        disable: true,
      },
      description: 'Test id for targeting the element in automated tests.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    styles: {
      control: {
        disable: true,
      },
      description:
        'Inline styles applied directly to the footer element. Use for truly dynamic values that cannot be expressed as Tailwind classes.',
      table: {
        type: {
          summary: 'Record<string, string>',
        },
      },
    },
  } as const,
  parameters: {
    docs: {
      description: {
        component:
          'A composable footer built from the Footer semantic wrapper, [FooterSection](/docs/layout-footer-footersection--docs), and [FooterLogo](/docs/layout-footer-footerlogo--docs) atom components.',
      },
    },
  },
};
export const Default = {
  args: footerMeta.args,
  play: async ({ canvasElement, step, args }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    const { footer } = args;
    const check = checker(footer.dataTestId, canvas, step);
    await check.is('footer');
    await check.attributes({
      'aria-label': footer.ariaLabel,
      id: footer.id,
    });
  },
};
