/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/storybook/Footer.meta.ts`
 */

import type { StoryContext, Renderer } from 'storybook/internal/types';
import { within } from 'storybook/test';
import { FooterSectionVariant } from '../FooterSection';
import { checker, enumType } from './utilities';
export const footerMeta = {
  tags: ['autodocs'] as string[],
  title: 'Layout/Footer',
  args: {
    // Footer
    ariaLabel: 'Footer',
    dataTestId: 'footer',
    id: 'footer-id',
    // FooterSection (primary)
    sectionVariant: FooterSectionVariant.PRIMARY,
    sectionDataTestId: 'footer-section-primary',
    // FooterLogo
    logoDataTestId: 'footer-logo',
    // Optional utility section
    showUtilitySection: true,
    utilitySectionDataTestId: 'footer-section-utility',
  },
  argTypes: {
    // Footer
    ariaLabel: {
      control: 'text',
      description: 'Accessible name for the `<footer>` landmark.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    ariaLabelledBy: {
      control: false,
      description: 'ID of an element that labels the footer.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    className: {
      control: false,
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    id: {
      control: false,
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    dataTestId: {
      control: false,
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    children: {
      table: {
        disable: true,
      },
    },
    // FooterSection
    sectionVariant: enumType(FooterSectionVariant, {
      description: 'Variant of the primary footer section.',
      defaultValue: FooterSectionVariant.PRIMARY,
    }),
    sectionClassName: {
      control: false,
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    sectionId: {
      control: false,
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    sectionDataTestId: {
      control: false,
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    // FooterLogo
    logoClassName: {
      control: false,
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    logoId: {
      control: false,
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    logoDataTestId: {
      control: false,
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    // Composition helpers (story-only, not real component props)
    showUtilitySection: {
      control: 'boolean',
      description: 'Whether to render a utility `FooterSection`.',
    },
    utilitySectionDataTestId: {
      control: false,
      table: {
        type: {
          summary: 'string',
        },
      },
    },
  } as const,
  parameters: {
    docs: {
      description: {
        component: 'A composable footer built from `Footer`, `FooterSection`, and `FooterLogo`.',
      },
    },
  },
};
export const Default = {
  args: footerMeta.args,
  play: async ({ canvasElement, step, args }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    const check = checker(args.dataTestId, canvas, step);
    await check.is('footer');
    await check.attributes({
      'aria-label': args.ariaLabel,
      id: args.id,
    });
    await checker(args.sectionDataTestId, canvas, step).is('div');
    await checker(args.logoDataTestId, canvas, step).is('div');
  },
};
