/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/storybook/HeaderTitle.meta.ts`
 */

import pick from 'lodash/pick';
import type { StoryContext, Renderer } from 'storybook/internal/types';
import { within } from 'storybook/test';
import { boxMeta } from './Box.meta';
import { checker } from './utilities';
export const headerTitleMeta = {
  tags: ['autodocs'] as string[],
  title: 'Layout/Header/HeaderTitle',
  args: {
    children: 'Title',
    id: 'header-title-id',
    dataTestId: 'header-title',
  },
  argTypes: {
    ...pick(boxMeta.argTypes, ['className', 'id', 'dataTestId', 'styles', 'children']),
  },
  parameters: {
    docs: {
      description: {
        component: 'Displays the service or site title within a header layout.',
      },
    },
  },
};
export const Default = {
  args: headerTitleMeta.args,
  play: async ({ canvasElement, step, args }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    const check = checker(args.dataTestId, canvas, step);
    await check.is('div');
    await check.attributes({
      id: args.id,
    });
    await check.children();
  },
};
