/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/storybook/Link.meta.ts`
 */

import type { Renderer, StoryContext } from 'storybook/internal/types';
import { within, expect } from 'storybook/test';
import { checker } from './utilities';
export const linkMeta = {
  tags: ['autodocs'] as string[],
  title: 'Navigation/Link',
  args: {
    children: 'Link',
    href: 'https://www.gov.ie',
    id: 'link-example',
    dataTestId: 'link-test',
  },
  argTypes: {
    children: {
      control: 'text',
      description: 'Link content — text, icons, or any HTML element.',
    },
    href: {
      control: 'text',
      description: 'The URL the link points to. Maps to the HTML href attribute.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    external: {
      control: 'boolean',
      description:
        'Opens the link in a new tab. When true, sets target="_blank" and rel="noreferrer noopener". Explicit target/rel props override these defaults.',
      table: {
        type: {
          summary: 'boolean',
        },
        defaultValue: {
          summary: 'false',
        },
      },
    },
    target: {
      control: {
        disable: true,
      },
      description: 'Browsing context for the link. Overrides the value set by external.',
      table: {
        type: {
          summary: "'_self' | '_blank' | '_parent' | '_top'",
        },
      },
    },
    rel: {
      control: {
        disable: true,
      },
      description: 'Link relationship. Overrides the default set by external.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    download: {
      control: {
        disable: true,
      },
      description:
        'When present, the link triggers a file download instead of navigation. A string value suggests a filename.',
      table: {
        type: {
          summary: 'string | boolean',
        },
      },
    },
    ariaCurrent: {
      control: {
        disable: true,
      },
      description:
        'Indicates the current item within a navigation set or process. Use "page" for current-page links in nav, "step" for multi-step flows.',
      table: {
        type: {
          summary: "'page' | 'step' | 'location' | 'date' | 'time' | boolean",
        },
      },
    },
    ariaLabel: {
      control: {
        disable: true,
      },
      description:
        'Accessible label for the link. Use when the visible text alone does not fully describe the destination. Maps to aria-label.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    ariaLabelledBy: {
      control: {
        disable: true,
      },
      description:
        'ID of the element that labels this link. Use when a visible heading or label elsewhere in the DOM should serve as the accessible name.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    ariaDescribedBy: {
      control: {
        disable: true,
      },
      description:
        'ID of the element that describes this link. Use for supplementary information such as file type, size, or "opens in new tab".',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    ariaHidden: {
      control: {
        disable: true,
      },
      description:
        'Hides the link from assistive technology. Use only for duplicate or decorative links that are not the primary interactive path.',
      table: {
        type: {
          summary: 'boolean',
        },
      },
    },
    tabIndex: {
      control: {
        disable: true,
      },
      description: 'Overrides the default tab order. Use -1 to remove from tab order in composite widgets.',
      table: {
        type: {
          summary: 'number',
        },
      },
    },
    lang: {
      control: {
        disable: true,
      },
      description:
        'Language of the link text, when it differs from the surrounding content. Maps to the HTML lang attribute.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    className: {
      control: {
        disable: true,
      },
      description: 'CSS classes to apply. Use gi-* Tailwind utilities for additional styling.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    id: {
      control: {
        disable: true,
      },
      description: 'Optional id for linking/targeting and aria references.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    dataTestId: {
      control: {
        disable: true,
      },
      description: 'Test id for targeting the element in automated tests.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    variant: {
      control: 'select',
      options: ['default', 'inline'],
      description:
        'Controls the styling level. "default" renders a bare anchor with no design-system styles. "inline" applies typography, colour, underline, and focus styles.',
      table: {
        type: {
          summary: "'default' | 'inline'",
        },
        defaultValue: {
          summary: 'default',
        },
      },
    },
    underline: {
      control: 'select',
      options: ['always', 'hover', 'none'],
      description:
        'Controls text decoration independently of variant. "always" shows underline, "hover" shows on hover only, "none" removes underline entirely.',
      table: {
        type: {
          summary: "'always' | 'hover' | 'none'",
        },
      },
    },
    appearance: {
      control: 'select',
      options: ['default', 'light', 'inherit'],
      description:
        'Overrides the text colour. "default" inherits from variant. Use "light" on dark backgrounds, "inherit" to match parent text colour.',
      table: {
        type: {
          summary: "'default' | 'light' | 'inherit'",
        },
        defaultValue: {
          summary: 'default',
        },
      },
    },
    visited: {
      control: 'select',
      options: ['default', 'none'],
      description:
        'Controls visited link colour. "default" keeps the visited style. "none" resets visited colour to the default text colour.',
      table: {
        type: {
          summary: "'default' | 'none'",
        },
        defaultValue: {
          summary: 'default',
        },
      },
    },
  },
  parameters: {
    docs: {
      description: {
        component:
          'Accessible anchor element for navigating to internal or external URLs. By default it renders a bare `<a>` tag with no visual styles — set `variant="inline"` to apply typography, colour, underline, and focus styles for use inside body text.',
      },
    },
  },
};
export const InlineLink = {
  args: {
    ...linkMeta.args,
    variant: 'inline' as const,
    dataTestId: 'link-inline',
  },
  play: async ({ canvasElement, step, args }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    const check = checker(args.dataTestId, canvas, step);
    await check.is('a');
    await check.attributes({
      href: args.href,
    });
    await check.children();
  },
};
export const PlainFocusState = {
  args: {
    ...linkMeta.args,
    dataTestId: 'link-icon-default',
  },
  parameters: {
    docs: {
      description: {
        story: 'Focus states for the default (plain) variant across default and light appearances.',
      },
    },
    pseudo: {
      focus: '.pseudo-focus',
    },
  },
  play: async ({ canvasElement, step }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    await step('icon link is focusable', async () => {
      const element = canvas.getByTestId('link-icon-default');
      element.focus();
      expect(element).toHaveFocus();
      expect(element.tagName).toBe('A');
    });
    await step('icon link has accessible name', async () => {
      const element = canvas.getByTestId('link-icon-default');
      expect(element).toHaveAttribute('aria-label');
    });
    await step('light icon link is focusable', async () => {
      const element = canvas.getByTestId('link-icon-light');
      element.focus();
      expect(element).toHaveFocus();
    });
  },
};
export const PlainLink = {
  args: {
    ...linkMeta.args,
    dataTestId: 'link-plain',
  },
  parameters: {
    docs: {
      description: {
        story:
          'The default variant renders a bare anchor with no design-system styles. Use it to wrap components like icons, or compose with asChild to style a native anchor.',
      },
    },
  },
};
