/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/storybook/SideNav.meta.ts`
 */

import type { ArgTypes, StoryContext, Renderer } from 'storybook/internal/types';
import { within, expect, userEvent } from 'storybook/test';
import type { Props } from '../sidenav/SideNav';
import { boxMeta } from './Box.meta';
import { checker } from './utilities';
export const sideNavMeta = {
  tags: ['autodocs'] as string[],
  title: 'Navigation/SideNav',
  args: {
    dataTestId: 'basic-nav',
  },
  argTypes: {
    className: boxMeta.argTypes.className,
    styles: boxMeta.argTypes.styles,
    id: boxMeta.argTypes.id,
    dataTestId: boxMeta.argTypes.dataTestId,
    ariaLabel: {
      control: 'text',
      description: 'Accessible label for the nav landmark. Maps to `aria-label`.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    ariaLabelledBy: {
      control: {
        disable: true,
      },
      description:
        'Points to the id of an element that labels the nav. Preferred over `ariaLabel` when a visible heading exists. Maps to `aria-labelledby`.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
  } satisfies ArgTypes<Props>,
  parameters: {
    docs: {
      description: {
        component:
          'SideNav is a composable navigation landmark. Nest SideNavHeading, SideNavSection, and SideNavItem to build grouped, expandable side navigation.',
      },
    },
  },
};
export const Default = {
  args: sideNavMeta.args,
  play: async ({ canvasElement, step, args }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    const check = checker(args.dataTestId, canvas, step);
    await check.is('nav');
    await check.children();
    await step('renders section headings', async () => {
      expect(canvas.getByText('Messages')).toBeInTheDocument();
      expect(canvas.getByText('Side Nav Heading')).toBeInTheDocument();
    });
    await step('renders open inbox section with children', async () => {
      expect(canvas.getByText('Inbox')).toBeInTheDocument();
      expect(canvas.getByText('Primary')).toBeInTheDocument();
      expect(canvas.getByText('Social')).toBeInTheDocument();
      expect(canvas.getByText('Promotions')).toBeInTheDocument();
    });
    await step('renders sent section and top-level items', async () => {
      expect(canvas.getByText('Sent')).toBeInTheDocument();
      expect(canvas.getByText('Overview')).toBeInTheDocument();
      expect(canvas.getByText('Reports')).toBeInTheDocument();
      expect(canvas.getByText('Settings')).toBeInTheDocument();
    });
    await step('clicking inbox collapses its children', async () => {
      await userEvent.click(
        canvas.getByRole('button', {
          name: /inbox/i,
        }),
      );
      expect(canvas.queryByText('Primary')).not.toBeInTheDocument();
      expect(canvas.queryByText('Social')).not.toBeInTheDocument();
      expect(canvas.queryByText('Promotions')).not.toBeInTheDocument();
    });
  },
};
