/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/H3.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

import styles from './styles';
import { getSize } from './utils';
import type { Props } from './types';

@Component({
  selector: 'gi-h3',
  template: `
    <h3
      [attr.id]="id"
      [attr.data-testid]="dataTestId"
      [class]="
        styles({
          size: getSize(size, 'md'),
          class: className,
        })
      "
    >
      <ng-content></ng-content>
    </h3>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class H3 {
  styles = styles;
  getSize = getSize;

  @Input() id!: Props['id'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() size!: Props['size'];
  @Input() className!: Props['className'];
}
