/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/heading/H5.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

import classes from './styles';
import { getSize } from './styles';
import type { Props } from './types';

@Component({
  selector: 'gi-h5',
  template: `
    <h5
      [attr.id]="id"
      [class]="
        classes({
          size: getSize(size, 'xs'),
          className: className,
        })
      "
      [attr.data-testid]="dataTestId"
    >
      <ng-content></ng-content>
    </h5>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class H5 {
  classes = classes;
  getSize = getSize;

  @Input() id!: Props['id'];
  @Input() size!: Props['size'];
  @Input() className!: Props['className'];
  @Input() dataTestId!: Props['dataTestId'];
}
