import type { Metadata } from 'next';
import './globals.css';
import '@ogcio/design-system-react/styles.css';
//import '@ogcio/govie-react/styles.css';
import '@ogcio/theme-govie/theme.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">{children}</body>
    </html>
  );
}
