<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/header/HeaderNav.lite.tsx`
-->

<template>
  <nav
    :id="id"
    :class="
      classes({
        className: className,
      })
    "
    :style="styles"
    :aria-label="ariaLabel"
    :data-testid="dataTestId"
  >
    <ul class="gi-list-none gi-flex gi-items-center gi-m-0 gi-p-0 gi-gap-4">
      <slot />
    </ul>
  </nav>
</template>

<script setup lang="ts">
import { tv } from 'tailwind-variants';
const classes = tv({
  base: 'gi-flex gi-items-center gi-flex-none',
});

export type Props = {
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  ariaLabel: string;
  dataTestId?: string;
};

const props = defineProps<Props>();
</script>
