<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/header/HeaderLogo.lite.tsx`
-->

<template>
  <GiBox
    :id="id"
    :className="
      classes({
        className: className,
      })
    "
    :styles="styles"
    :dataTestId="dataTestId"
    ><slot
  /></GiBox>
</template>

<script setup lang="ts">
import { tv } from 'tailwind-variants';
import GiBox from '../Box.vue';
const classes = tv({
  base: 'gi-flex gi-flex-none gi-rounded-sm',
});

export type Props = {
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

const props = defineProps<Props>();
</script>
