<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/header/HeaderSection.lite.tsx`
-->

<template>
  <GiBox
    :id="id"
    :className="
      classes({
        variant: getVariant(variant),
        appearance: getAppearance(appearance),
      })
    "
    :styles="styles"
    :role="role"
    :ariaLabel="ariaLabel"
    :dataTestId="dataTestId"
    ><GiContainer
      :maxWidth="maxWidth"
      :className="
        contentClasses({
          variant: getVariant(variant),
          className: className,
        })
      "
      ><slot /></GiContainer
  ></GiBox>
</template>

<script setup lang="ts">
import { tv } from 'tailwind-variants';
import { clamp } from '../utilities';
import { SurfaceVariant, SurfaceAppearance } from '../constants';
import type { MaxWidth, ValueOf } from '../constants';
import GiBox from '../Box.vue';
import GiContainer from '../Container.vue';
const getVariant = (x: Props['variant']) => clamp(x, SurfaceVariant, SurfaceVariant.PRIMARY);
const getAppearance = (x: Props['appearance']) => clamp(x, SurfaceAppearance, SurfaceAppearance.DEFAULT);
const classes = tv({
  base: 'gi-header-section gi-w-full',
  variants: {
    variant: {
      primary: '',
      utility: 'gi-hidden lg:gi-block',
    },
    appearance: {
      default: 'gi-text-color-text-tone-light-default',
      light: 'gi-text-color-text-system-neutral-default gi-header-section-light',
    },
  },
  compoundVariants: [
    {
      variant: 'primary',
      appearance: 'default',
      class: 'gi-bg-color-surface-system-primary-default',
    },
    {
      variant: 'utility',
      appearance: 'default',
      class: 'gi-bg-color-surface-system-primary-subtle',
    },
    {
      variant: 'primary',
      appearance: 'light',
      class: 'gi-bg-color-surface-system-neutral-default',
    },
    {
      variant: 'utility',
      appearance: 'light',
      class: 'gi-bg-color-surface-system-neutral-layer1',
    },
  ],
  defaultVariants: {
    variant: 'primary',
    appearance: 'default',
  },
});
const contentClasses = tv({
  base: 'gi-flex gi-items-center',
  variants: {
    variant: {
      primary:
        'gi-header-section-primary gi-flex-row gi-flex-nowrap gi-justify-between gi-h-20 gi-text-md gi-font-bold gi-py-3 md:gi-py-4',
      utility: 'gi-header-section-utility gi-justify-end gi-h-10 gi-gap-4 gi-py-1',
    },
  },
  defaultVariants: {
    variant: 'primary',
  },
});

export type Props = {
  variant?: ValueOf<typeof SurfaceVariant>;
  appearance?: ValueOf<typeof SurfaceAppearance>;
  maxWidth?: ValueOf<typeof MaxWidth>;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  role?: 'region' | 'group';
  ariaLabel?: string;
  dataTestId?: string;
};

const props = defineProps<Props>();
</script>
