<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/header/Header.lite.tsx`
-->

<template>
  <header
    :id="id"
    :class="
      classes({
        className: className,
      })
    "
    :style="styles"
    :aria-label="ariaLabel"
    :aria-labelledby="ariaLabelledBy"
    :data-testid="dataTestId"
  >
    <slot />
  </header>
</template>

<script setup lang="ts">
import { tv } from 'tailwind-variants';
const classes = tv({
  base: 'gi-w-full gi-font-primary',
});

export type Props = {
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  ariaLabel?: string;
  ariaLabelledBy?: string;
  dataTestId?: string;
};

const props = defineProps<Props>();
</script>
