<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/header/HeaderTitle.lite.tsx`
-->

<template>
  <GiBox
    :id="id"
    :className="
      classes({
        className: className,
      })
    "
    :styles="styles"
    :dataTestId="dataTestId"
    ><slot
  /></GiBox>
</template>

<script setup lang="ts">
import { tv } from 'tailwind-variants';
import GiBox from '../Box.vue';
const classes = tv({
  base: [
    'gi-min-w-0 gi-flex-1 gi-p-2',
    'gi-text-lg xl:gi-text-xl gi-font-bold gi-font-primary',
    'gi-truncate',
    'gi-ml-2 md:gi-ml-4 lg:gi-ml-10',
  ],
});

export type Props = {
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

const props = defineProps<Props>();
</script>
