FROM node:22-bookworm

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN corepack enable pnpm
RUN pnpm install
RUN npx -y playwright@1.55.0 install --with-deps

ENTRYPOINT ["npx", "playwright"]
