FROM mcr.microsoft.com/playwright:v1.58.2-noble

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN corepack enable pnpm && \
    pnpm install --frozen-lockfile

ENTRYPOINT ["npx", "playwright"]
