location /storybook-react/ {
  alias /usr/share/nginx/html/storybook-react/;
}

location /storybook-react {
  return 301 /storybook-react/;
}

location /storybook-html/ {
  alias /usr/share/nginx/html/storybook-html/;
}

location /storybook-html {
  return 301 /storybook-html/;
}

# Angular storybook is only available in dev during development
location /storybook-angular/ {
  alias /usr/share/nginx/html/storybook-angular/;
}

location /storybook-angular {
  return 301 /storybook-angular/;
}
