pid /tmp/nginx.pid;

events {
  worker_connections 16384;
}

http {
  include mime.types;
  proxy_temp_path /tmp/proxy_temp;
  client_body_temp_path /tmp/client_temp;
  fastcgi_temp_path /tmp/fastcgi_temp;
  uwsgi_temp_path /tmp/uwsgi_temp;
  scgi_temp_path /tmp/scgi_temp;
  
  server {
    listen 8080;
    absolute_redirect off;

    location / {
      root /usr/share/nginx/html/doc;
      index  index.html;
      try_files $uri $uri/ /index.html;
    }

    ## Add rules for health checks
    location /health {
      return 200 'no content';
    }

    location /ready {
      return 200 'no content';
    }

    ## Storybook routes (environment-specific)
    include /etc/nginx/storybook.conf;
  }
}
