packages:
  - "apps/*"
  - "examples/*"
  - "packages/**"
  - "!**/dist/**" # avoid generated package.json (e.g. ng-packagr) being picked up as workspace

minimumReleaseAge: 1440 # 1 day — protect against supply chain attacks

allowBuilds:
  '@bundled-es-modules/glob': true
  '@parcel/watcher': true
  contentlayer2: true
  es5-ext: false
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  style-dictionary: true
  svelte-preprocess: true
  unrs-resolver: true
