<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Box.lite.tsx`
-->

<template>
  <div
    :id="id"
    :class="className"
    :role="role"
    :aria-label="role ? ariaLabel : undefined"
    :aria-labelledby="role ? ariaLabelledBy : undefined"
    :style="styles"
    :data-testid="dataTestId"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
export type Props = {
  className?: string;
  id?: string;
  dataTestId?: string;
  role?: 'region' | 'navigation' | 'complementary' | 'search' | 'form' | 'group';
  ariaLabel?: string;
  ariaLabelledBy?: string;
  styles?: Record<string, string>;
};

const props = defineProps<Props>();
</script>
