<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Button.lite.tsx`
-->

<template>
  <button
    :id="id"
    :class="
      classes({
        variant: getVariant(variant),
        appearance: getAppearance(appearance),
        size: getSize(size),
        disabled: !!disabled,
        className: className,
      })
    "
    :data-size="getSize(size)"
    :disabled="disabled || undefined"
    @click="async (event) => onClick && onClick(event)"
    @focus="async (event) => onFocus && onFocus(event)"
    @blur="async (event) => onBlur && onBlur(event)"
    @keydown="async (event) => onKeyDown && onKeyDown(event)"
    @keyup="async (event) => onKeyUp && onKeyUp(event)"
    :aria-label="ariaLabel"
    :aria-labelledby="ariaLabelledBy"
    :aria-describedby="ariaDescribedBy"
    :aria-checked="ariaChecked"
    :aria-pressed="ariaPressed"
    :aria-expanded="ariaExpanded"
    :aria-controls="ariaControls"
    :aria-haspopup="ariaHasPopup"
    :aria-busy="ariaBusy"
    :role="role"
    :type="type"
    :form="form"
    :value="value"
    :tabIndex="tabIndex"
    :data-testid="dataTestId"
  >
    <slot />
  </button>
</template>

<script setup lang="ts">
import classes, { getAppearance, getSize, getVariant } from './Button.styles';
import type { Appearance, ButtonSize, Variant } from './Button.styles';
import type { ValueOf } from './constants';

export type Props = {
  id?: string;
  variant?: ValueOf<typeof Variant>;
  appearance?: ValueOf<typeof Appearance>;
  size?: ValueOf<typeof ButtonSize>;
  disabled?: boolean;
  className?: string;
  onClick?: (event: any) => void;
  onFocus?: (event: any) => void;
  onBlur?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  ariaLabel?: string;
  ariaLabelledBy?: string;
  ariaDescribedBy?: string;
  ariaChecked?: boolean;
  ariaPressed?: boolean | 'mixed';
  ariaExpanded?: boolean;
  ariaControls?: string;
  ariaHasPopup?: 'menu' | 'listbox' | 'dialog' | 'grid' | 'tree' | boolean;
  ariaBusy?: boolean;
  role?: string;
  type?: 'button' | 'submit' | 'reset';
  form?: string;
  value?: string;
  tabIndex?: number;
  dataTestId?: string;
};

const props = defineProps<Props>();
</script>
