<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Container.lite.tsx`
-->

<template>
  <GiBox
    :id="id"
    :role="role"
    :ariaLabel="ariaLabel"
    :ariaLabelledBy="ariaLabelledBy"
    :styles="styles"
    :dataTestId="dataTestId"
    :className="
      classes({
        inset: inset,
        gutters: gutters,
        maxWidth: getMaxWidth(maxWidth),
        className: className,
      })
    "
    ><slot
  /></GiBox>
</template>

<script setup lang="ts">
import { tv } from 'tailwind-variants';
import { MaxWidth } from './constants';
import type { ValueOf } from './constants';
import { clamp } from './utilities';
import type { Props as BoxProps } from './Box.vue';
import GiBox from './Box.vue';
const getMaxWidth = (x: Props['maxWidth']) => clamp(x, MaxWidth, MaxWidth.DEFAULT);
const classes = tv({
  base: 'gi-container gi-mx-auto',
  variants: {
    inset: {
      true: 'gi-py-4 md:gi-py-6 lg:gi-py-8',
    },
    gutters: {
      false: 'gi-px-0',
    },
    maxWidth: {
      default: 'gi-max-w-full 2xl:gi-max-w-screen-2xl',
      sm: 'gi-max-w-screen-sm',
      md: 'gi-max-w-screen-md',
      lg: 'gi-max-w-screen-lg',
      xl: 'gi-max-w-screen-xl',
      '2xl': 'gi-max-w-screen-2xl',
      full: 'gi-max-w-full',
    },
  },
  defaultVariants: {
    inset: false,
    gutters: true,
    maxWidth: MaxWidth.DEFAULT,
  },
});

export type Props = {
  inset?: boolean;
  gutters?: boolean;
  maxWidth?: ValueOf<typeof MaxWidth>;
} & BoxProps;

const props = withDefaults(defineProps<Props>(), {
  id: undefined,
  role: undefined,
  ariaLabel: undefined,
  ariaLabelledBy: undefined,
  styles: undefined,
  dataTestId: undefined,
  inset: false,
  gutters: true,
  maxWidth: undefined,
  className: undefined,
  children: undefined,
});
</script>
