<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Container.lite.tsx`
-->

<template>
  <CoreBox
    :id="id"
    :role="role"
    :ariaLabel="ariaLabel"
    :ariaLabelledBy="ariaLabelledBy"
    :styles="styles"
    :dataTestId="dataTestId"
    :className="
      classes({
        inset: !!inset,
        gutters: gutters ?? true,
        maxWidth: getMaxWidth(maxWidth),
        className: className,
      })
    "
    ><slot
  /></CoreBox>
</template>

<script setup lang="ts">
import type { MaxWidth, ValueOf } from './constants';
import { getMaxWidth } from './utilities';
import classes from './Container.styles';
import type { Props as BoxProps } from './Box.vue';
import CoreBox from './Box.vue';

export type Props = {
  inset?: boolean;
  gutters?: boolean;
  maxWidth?: ValueOf<typeof MaxWidth>;
} & BoxProps;

const props = withDefaults(defineProps<Props>(), {
  id: undefined,
  role: undefined,
  ariaLabel: undefined,
  ariaLabelledBy: undefined,
  styles: undefined,
  dataTestId: undefined,
  inset: undefined,
  gutters: true,
  maxWidth: undefined,
  className: undefined,
  children: undefined,
});
</script>
