<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Divider.lite.tsx`
-->

<template>
  <hr
    :id="id"
    :data-testid="dataTestId"
    :aria-orientation="getOrientation(orientation)"
    :class="
      classes({
        orientation: getOrientation(orientation),
        className: className,
      })
    "
    :style="styles"
  />
</template>

<script setup lang="ts">
import { tv } from 'tailwind-variants';
import { Orientation } from './constants';
import type { ValueOf } from './constants';
import { getOrientation } from './utilities';
const classes = tv({
  base: 'gi-border-color-border-system-neutral-muted gi-border-0',
  variants: {
    orientation: {
      [Orientation.HORIZONTAL]: 'gi-border-t-xs gi-w-full',
      [Orientation.VERTICAL]: 'gi-border-l-xs gi-self-stretch gi-h-auto',
    },
  },
  defaultVariants: {
    orientation: Orientation.HORIZONTAL,
  },
});

export type Props = {
  orientation?: ValueOf<typeof Orientation>;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

const props = defineProps<Props>();
</script>
