<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Grid.lite.tsx`
-->

<template>
  <GiBox
    :id="id"
    :role="role"
    :ariaLabel="ariaLabel"
    :ariaLabelledBy="ariaLabelledBy"
    :styles="styles"
    :className="
      classes([
        container && 'gi-grid-container',
        container && getGridClasses(columns ?? DEFAULT_COLUMNS, 'gi-grid-columns'),
        container && getGridClasses(gap, 'gi-grid-gap'),
        (!container || !_.isNil(size)) && 'gi-grid-item',
        (!container || !_.isNil(size)) && getGridClasses(size, 'gi-grid-span'),
        className,
      ])
    "
    :dataTestId="dataTestId"
    ><slot
  /></GiBox>
</template>

<script setup lang="ts">
import _ from 'lodash';
import type { ResponsiveValue, BreakpointKey, SpacingScale } from './constants';
import type { Props as BoxProps } from './Box.vue';
import { resolveResponsive } from './utilities';
import GiBox from './Box.vue';
const DEFAULT_COLUMNS: Partial<Record<BreakpointKey, SpacingScale>> = {
  base: 4,
  sm: 6,
  md: 8,
  lg: 12,
};
const classes = (list: Array<string | boolean | undefined>) => _.compact(list).join(' ');
const getGridClasses = (value: ResponsiveValue<SpacingScale> | undefined, prefix: string): string =>
  resolveResponsive(value, (v, bp) => `${bp}${prefix}-${_.clamp(v as number, 0, 12)}`);

export type Props = {
  container?: boolean;
  columns?: ResponsiveValue<SpacingScale>;
  gap?: ResponsiveValue<SpacingScale>;
  size?: ResponsiveValue<SpacingScale>;
} & BoxProps;

const props = defineProps<Props>();
</script>
