<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Grid.lite.tsx`
-->

<template>
  <CoreBox
    :id="id"
    :role="role"
    :ariaLabel="ariaLabel"
    :ariaLabelledBy="ariaLabelledBy"
    :styles="styles"
    :className="
      classes({
        container: container,
        columns: columns,
        gap: gap,
        size: size,
        className: className,
      })
    "
    :dataTestId="dataTestId"
    ><slot
  /></CoreBox>
</template>

<script setup lang="ts">
import type { ResponsiveValue, SpacingScale } from './constants';
import type { Props as BoxProps } from './Box.vue';
import classes from './Grid.styles';
import CoreBox from './Box.vue';

export type Props = {
  container?: boolean;
  columns?: ResponsiveValue<SpacingScale>;
  gap?: ResponsiveValue<SpacingScale>;
  size?: ResponsiveValue<SpacingScale>;
} & BoxProps;

const props = defineProps<Props>();
</script>
