<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/InsetText.lite.tsx`
-->

<template>
  <blockquote
    :id="id"
    :class="
      classes({
        className: className,
      })
    "
    :style="styles"
    :cite="cite"
    :aria-describedby="describedBy || undefined"
    :aria-labelledby="labelledBy || undefined"
  >
    <slot />
  </blockquote>
</template>

<script setup lang="ts">
import classes from './InsetText.styles';

export type Props = {
  cite?: string;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  describedBy?: string;
  labelledBy?: string;
};

const props = defineProps<Props>();
</script>
