<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Stack.lite.tsx`
-->

<template>
  <CoreBox
    :id="id"
    :role="role"
    :ariaLabel="ariaLabel"
    :ariaLabelledBy="ariaLabelledBy"
    :styles="styles"
    :className="
      classes({
        align: getAlignItems(align),
        justify: getJustify(justify),
        wrap: !!wrap,
        className: [getDirectionClasses(direction), getGapClasses(gap), className],
      })
    "
    :dataTestId="dataTestId"
    ><slot
  /></CoreBox>
</template>

<script setup lang="ts">
import type { AlignItems, Direction, Justify, ResponsiveValue, SpacingScale, ValueOf } from './constants';
import type { Props as BoxProps } from './Box.vue';
import { getAlignItems, getJustify } from './utilities';
import classes, { getDirectionClasses, getGapClasses } from './Stack.styles';
import CoreBox from './Box.vue';

export type Props = {
  direction?: ResponsiveValue<ValueOf<typeof Direction>>;
  gap?: ResponsiveValue<SpacingScale>;
  align?: ValueOf<typeof AlignItems>;
  justify?: ValueOf<typeof Justify>;
  wrap?: boolean;
} & BoxProps;

const props = defineProps<Props>();
</script>
