<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Text.lite.tsx`
-->

<template>
  <span
    :class="
      classes({
        size: getSize(size),
        whitespace: getWhitespace(whitespace),
        className: className,
      })
    "
    :id="id"
    :style="styles"
    :data-testid="dataTestId"
    :aria-hidden="ariaHidden"
    ><slot
  /></span>
</template>

<script setup lang="ts">
import type { Size, ValueOf, Whitespace } from './constants';
import { getSize, getWhitespace } from './utilities';
import classes from './Text.styles';

export type Props = {
  size?: ValueOf<typeof Size>;
  whitespace?: ValueOf<typeof Whitespace>;
  className?: string;
  id?: string;
  dataTestId?: string;
  styles?: Record<string, string>;
  ariaHidden?: boolean;
};

const props = withDefaults(defineProps<Props>(), {
  size: undefined,
  whitespace: undefined,
  className: undefined,
  id: undefined,
  styles: undefined,
  dataTestId: undefined,
  ariaHidden: undefined,
  children: undefined,
});
</script>
