parameters:
  - name: autoReleaseCommitMessagePrefix
    type: string

steps:
  - checkout: self
    fetchDepth: 1
  - task: Bash@3
    name: configureVariables
    displayName: Configure variables
    inputs:
      targetType: "inline"
      script: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "Commit Message: $COMMIT_MESSAGE"
        
        if [[ $COMMIT_MESSAGE =~ ^"${{ parameters.autoReleaseCommitMessagePrefix }}" ]]; then
          OVERLAYS_PATH='websites/overlays/prod-02/prod'
          DEPLOY_ENVIRONMENT='production'
        else
          OVERLAYS_PATH='websites/overlays/non-prod-02/dev'
          DEPLOY_ENVIRONMENT='development'
        fi
        
        echo "Overlays path: $OVERLAYS_PATH"
        echo "Deploy environment: $DEPLOY_ENVIRONMENT"
        
        echo "##vso[task.setvariable variable=OVERLAYS_PATH;isOutput=true]$OVERLAYS_PATH"
        echo "##vso[task.setvariable variable=DEPLOY_ENVIRONMENT;isOutput=true]$DEPLOY_ENVIRONMENT"
