/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/header/HeaderLogo.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  children: any;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import GiBox from '../Box';
const classes = tv({
  base: 'gi-flex-none gi-rounded-sm',
});

function HeaderLogo(props: Props) {
  return (
    <GiBox
      id={props.id}
      className={classes({
        className: props.className,
      })}
      styles={props.styles}
      dataTestId={props.dataTestId}
    >
      {props.children}
    </GiBox>
  );
}

export default HeaderLogo;
