/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/header/HeaderNavItem.lite.tsx`
 */

'use client';
import * as React from 'react';

export type Props = {
  children: any;
  /** Visibility: `true`/`false`, a breakpoint to show from (e.g. `"lg"`), or a per-breakpoint map like `{ base: false, lg: true }`. */
  visible?: VisibleValue;
  onClick?: (event: any) => void;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  ariaLabel?: string;
  ariaExpanded?: boolean;
  ariaControls?: string;
  dataTestId?: string;
};

import { getVisibility, classes } from './HeaderNavItem.styles';
import type { VisibleValue } from './HeaderNavItem.styles';

function HeaderNavItem(props: Props) {
  return (
    <li className={getVisibility(props.visible)}>
      <button
        type="button"
        id={props.id}
        className={classes({
          className: ['gi-header-nav-item', props.className],
        })}
        style={props.styles}
        aria-label={props.ariaLabel}
        aria-expanded={props.ariaExpanded}
        aria-controls={props.ariaControls}
        data-testid={props.dataTestId}
        onClick={(event) => props.onClick && props.onClick(event)}
      >
        {props.children}
      </button>
    </li>
  );
}

export default HeaderNavItem;
