/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/header/Header.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  children: any;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  ariaLabel?: string;
  ariaLabelledBy?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
const classes = tv({
  base: 'gi-grid gi-relative gi-overflow-x-clip gi-w-full gi-font-primary',
});

function Header(props: Props) {
  return (
    <header
      id={props.id}
      className={classes({
        className: props.className,
      })}
      style={props.styles}
      aria-label={props.ariaLabel}
      aria-labelledby={props.ariaLabelledBy}
      data-testid={props.dataTestId}
    >
      {props.children}
    </header>
  );
}

export default Header;
