/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/header/HeaderNavItemSeparator.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  /** Visibility: `true`/`false`, a breakpoint to show from (e.g. `"lg"`), or a per-breakpoint map like `{ base: false, lg: true }`. */
  visible?: VisibleValue;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import GiDivider from '../Divider';
import { getVisibility } from './HeaderNavItem.styles';
import type { VisibleValue } from './HeaderNavItem.styles';
const classes = tv({
  base: 'gi-mx-2 gi-h-8 gi-items-stretch',
});
const dividerClasses = tv({
  base: 'gi-header-nav-item-separator !gi-border-[currentColor]' /* `!important` needed for styles to resolve correctly given Tailwind's class-merge limitations. */,
});
function HeaderNavItemSeparator(props: Props) {
  return (
    <li role="none" className={classes({ className: getVisibility(props.visible) })}>
      <GiDivider
        orientation="vertical"
        id={props.id}
        dataTestId={props.dataTestId}
        styles={props.styles}
        className={dividerClasses({ className: props.className })}
      />
    </li>
  );
}
export default HeaderNavItemSeparator;
