/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/header/HeaderNavItemSeparator.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  /** Visibility: `true`/`false`, a breakpoint to show from (e.g. `"lg"`), or a per-breakpoint map like `{ base: false, lg: true }`. */
  visible?: VisibleValue;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import GiDivider from '../Divider';
import { getVisibility } from './HeaderNavItem.styles';
import type { VisibleValue } from './HeaderNavItem.styles';
const listClasses = tv({
  base: 'gi-h-8',
});

// !important is needed for styles to resolve correctly given Tailwind's class-merge limitations. // !important is needed for styles to resolve correctly given Tailwind's class-merge limitations.
const classes = tv({
  base: 'gi-header-nav-item-separator !gi-border-[currentColor] gi-mx-2',
});

function HeaderNavItemSeparator(props: Props) {
  props = { visible: true, ...props };
  return (
    <li
      role="none"
      aria-hidden
      className={listClasses({
        className: getVisibility(props.visible),
      })}
    >
      <GiDivider
        orientation="vertical"
        id={props.id}
        dataTestId={props.dataTestId}
        styles={props.styles}
        className={classes({
          className: props.className,
        })}
      />
    </li>
  );
}

export default HeaderNavItemSeparator;
