/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavGroup.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  open?: boolean;
  selected?: boolean;
  label?: any;
  disabled?: boolean;
  className?: string;
  styles?: Record<string, string>;
  onClick?: (event: any) => void;
  onFocus?: (event: any) => void;
  onBlur?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  ariaHidden?: boolean;
  ariaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false' | boolean;
  ariaLabel?: string;
  tabIndex?: number;
  dataTestId?: string;
};
const defaultProps: any = { ariaHidden: undefined, ariaCurrent: undefined };

import classes, { arrowClasses } from './SideNavItem.styles';
import GiKeyboardArrowDownIcon from '../icons/KeyboardArrowDown';
import { tv } from 'tailwind-variants';
const contentClasses = tv({
  base: 'gi-side-nav-group',
  variants: {
    open: {
      true: 'gi-block',
      false: 'gi-hidden',
    },
  },
  defaultVariants: {
    open: false,
  },
});

@Component({
  selector: 'gi-side-nav-group',
  template: `
    <li class="gi-list-none gi-mt-1 gi-relative gi-side-nav-list" [attr.aria-hidden]="ariaHidden">
      <div class="gi-relative">
        <button
          type="button"
          [attr.id]="id"
          [class]="
            classes({
              selected: !!selected,
              disabled: !!disabled,
              expandable: true,
              className: className,
            })
          "
          [ngStyle]="styles"
          [attr.disabled]="disabled || undefined"
          (click)="onClick && this.onClick.emit($event)"
          (focus)="onFocus && this.onFocus.emit($event)"
          (blur)="onBlur && this.onBlur.emit($event)"
          (keydown)="onKeyDown && this.onKeyDown.emit($event)"
          (keyup)="onKeyUp && this.onKeyUp.emit($event)"
          [attr.aria-current]="ariaCurrent"
          [attr.aria-label]="ariaLabel"
          [attr.tabIndex]="ariaHidden ? -1 : tabIndex"
          [attr.data-testid]="dataTestId"
        >
          <ng-content select="[label]"></ng-content>
        </button>
        <gi-keyboard-arrow-down-icon
          [className]="
            arrowClasses({
              open: !!open,
            })
          "
        ></gi-keyboard-arrow-down-icon>
      </div>
      <ul
        [attr.aria-expanded]="!!open"
        [class]="
          contentClasses({
            open: !!open,
          })
        "
      >
        <ng-content></ng-content>
      </ul>
    </li>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiKeyboardArrowDownIcon],
})
export default class SideNavGroup {
  contentClasses = contentClasses;
  classes = classes;
  arrowClasses = arrowClasses;

  @Input() ariaHidden: Props['ariaHidden'] = defaultProps['ariaHidden'];
  @Input() id!: Props['id'];
  @Input() selected!: Props['selected'];
  @Input() disabled!: Props['disabled'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() ariaCurrent: Props['ariaCurrent'] = defaultProps['ariaCurrent'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() tabIndex!: Props['tabIndex'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() open!: Props['open'];
  @Output() onClick = new EventEmitter<any>();
  @Output() onFocus = new EventEmitter<any>();
  @Output() onBlur = new EventEmitter<any>();
  @Output() onKeyDown = new EventEmitter<any>();
  @Output() onKeyUp = new EventEmitter<any>();
}
