/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavItem.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  actions?: any;
  value?: string;
  disabled?: boolean;
  className?: string;
  styles?: Record<string, string>;
  onClick?: (event: any) => void;
  ariaHidden?: boolean | 'true' | 'false';
  ariaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false' | boolean;
  ariaLabel?: string;
  ariaControls?: string;
  tabIndex?: number;
  dataTestId?: string;
};
const defaultProps: any = { disabled: false, ariaHidden: false };

import classes, { actionClasses } from './SideNavItem.styles';
import GiSideNavRow from './SideNavRow';
import GiBox from '../Box';

@Component({
  selector: 'gi-side-nav-item',
  template: `
    <gi-side-nav-row [ariaHidden]="ariaHidden"
      ><button
        [attr.id]="id"
        [class]="
          classes({
            disabled: disabled,
            hasAction: !!actions,
            className: ['gi-side-nav-item_', className],
          })
        "
        [ngStyle]="styles"
        [attr.value]="value"
        (click)="onClick && this.onClick.emit($event)"
        [attr.data-testid]="dataTestId"
        [attr.aria-current]="ariaCurrent"
        [attr.aria-label]="ariaLabel"
        [attr.aria-controls]="ariaControls"
        [attr.tabIndex]="ariaHidden ? -1 : tabIndex"
      >
        <ng-content></ng-content>
      </button>
      <ng-container *ngIf="!!actions"
        ><gi-box
          [className]="
            actionClasses({
              expandable: true,
            })
          "
          ><ng-content select="[actions]">{{ actions }}</ng-content></gi-box
        ></ng-container
      ></gi-side-nav-row
    >
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiSideNavRow, GiBox],
})
export default class SideNavItem {
  classes = classes;
  actionClasses = actionClasses;

  @Input() ariaHidden: Props['ariaHidden'] = defaultProps['ariaHidden'];
  @Input() id!: Props['id'];
  @Input() disabled: Props['disabled'] = defaultProps['disabled'];
  @Input() actions!: Props['actions'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() value!: Props['value'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() ariaCurrent!: Props['ariaCurrent'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaControls!: Props['ariaControls'];
  @Input() tabIndex!: Props['tabIndex'];
  @Output() onClick = new EventEmitter<any>();
}
