/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/sideNav/SideNav.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  children?: any;
  ariaLabel?: string;
  className?: string;
  id?: string;
  dataTestId?: string;
};

@Component({
  selector: 'gi-side-nav',
  template: `
    <nav
      [attr.id]="id"
      [class]="\`gi-max-w-[400px] \${className}\`"
      [attr.aria-label]="ariaLabel"
      [attr.data-testid]="dataTestId"
    >
      <ul class="gi-list-none gi-p-0 gi-m-0">
        <ng-content></ng-content>
      </ul>
    </nav>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class SideNav {
  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() dataTestId!: Props['dataTestId'];
}
