/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavItem.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  selected?: boolean;
  disabled?: boolean;
  className?: string;
  styles?: Record<string, string>;
  onClick?: (event: any) => void;
  onFocus?: (event: any) => void;
  onBlur?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  ariaHidden?: boolean | 'true' | 'false';
  ariaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false' | boolean;
  ariaLabel?: string;
  tabIndex?: number;
  dataTestId?: string;
};
const defaultProps: any = { ariaHidden: undefined, ariaCurrent: undefined };

import classes from './SideNavItem.styles';

@Component({
  selector: 'gi-side-nav-item',
  template: `
    <li class="gi-list-none gi-mt-1 gi-relative gi-side-nav-list" [attr.aria-hidden]="ariaHidden">
      <button
        type="button"
        [attr.id]="id"
        [class]="
          classes({
            selected: !!selected,
            disabled: !!disabled,
            className: className,
          })
        "
        [ngStyle]="styles"
        [attr.disabled]="disabled || undefined"
        (click)="onClick && this.onClick.emit($event)"
        (focus)="onFocus && this.onFocus.emit($event)"
        (blur)="onBlur && this.onBlur.emit($event)"
        (keydown)="onKeyDown && this.onKeyDown.emit($event)"
        (keyup)="onKeyUp && this.onKeyUp.emit($event)"
        [attr.aria-current]="ariaCurrent"
        [attr.aria-label]="ariaLabel"
        [attr.tabIndex]="ariaHidden ? -1 : tabIndex"
        [attr.data-testid]="dataTestId"
      >
        <ng-content></ng-content>
      </button>
    </li>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class SideNavItem {
  classes = classes;

  @Input() ariaHidden: Props['ariaHidden'] = defaultProps['ariaHidden'];
  @Input() id!: Props['id'];
  @Input() selected!: Props['selected'];
  @Input() disabled!: Props['disabled'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() ariaCurrent: Props['ariaCurrent'] = defaultProps['ariaCurrent'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() tabIndex!: Props['tabIndex'];
  @Input() dataTestId!: Props['dataTestId'];
  @Output() onClick = new EventEmitter<any>();
  @Output() onFocus = new EventEmitter<any>();
  @Output() onBlur = new EventEmitter<any>();
  @Output() onKeyDown = new EventEmitter<any>();
  @Output() onKeyUp = new EventEmitter<any>();
}
