/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavItemLink.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  href: string;
  selected?: boolean;
  className?: string;
  external?: boolean;
  target?: '_self' | '_blank' | '_parent' | '_top';
  rel?: string;
  download?: string | boolean;
  ariaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false' | boolean;
  ariaLabel?: string;
  ariaHidden?: boolean | 'true' | 'false';
  ariaLabelledBy?: string;
  ariaDescribedBy?: string;
  tabIndex?: number;
  lang?: string;
  styles?: Record<string, string>;
  onClick?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  dataTestId?: string;
};
const defaultProps: any = { download: undefined, selected: false, ariaHidden: undefined, ariaCurrent: undefined };

import classes from './SideNavItem.styles';

@Component({
  selector: 'gi-side-nav-item-link',
  template: `
    <li class="gi-list-none gi-mt-1 gi-relative gi-side-nav-list" [attr.aria-hidden]="ariaHidden">
      <a
        [attr.id]="id"
        [attr.href]="href"
        [attr.target]="target ?? (external ? '_blank' : undefined)"
        [attr.rel]="rel ?? (external ? 'noreferrer noopener' : undefined)"
        [attr.download]="download"
        (click)="onClick && this.onClick.emit($event)"
        [class]="
          classes({
            selected: !!selected,
            className: className,
          })
        "
        [ngStyle]="styles"
        [attr.data-testid]="dataTestId"
        [attr.aria-current]="ariaCurrent"
        [attr.aria-label]="ariaLabel"
        [attr.aria-labelledby]="ariaLabelledBy"
        [attr.aria-describedby]="ariaDescribedBy"
        [attr.tabIndex]="ariaHidden ? -1 : tabIndex"
        [attr.lang]="lang"
        (keydown)="onKeyDown && this.onKeyDown.emit($event)"
        (keyup)="onKeyUp && this.onKeyUp.emit($event)"
        ><ng-content></ng-content
      ></a>
    </li>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class SideNavItemLink {
  classes = classes;

  @Input() ariaHidden: Props['ariaHidden'] = defaultProps['ariaHidden'];
  @Input() id!: Props['id'];
  @Input() href!: Props['href'];
  @Input() target!: Props['target'];
  @Input() external!: Props['external'];
  @Input() rel!: Props['rel'];
  @Input() download: Props['download'] = defaultProps['download'];
  @Input() selected: Props['selected'] = defaultProps['selected'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() ariaCurrent: Props['ariaCurrent'] = defaultProps['ariaCurrent'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() ariaDescribedBy!: Props['ariaDescribedBy'];
  @Input() tabIndex!: Props['tabIndex'];
  @Input() lang!: Props['lang'];
  @Output() onClick = new EventEmitter<any>();
  @Output() onKeyDown = new EventEmitter<any>();
  @Output() onKeyUp = new EventEmitter<any>();
}
