/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavGroup.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  open?: boolean;
  actions?: any;
  label?: any;
  disabled?: boolean;
  className?: string;
  styles?: Record<string, string>;
  onClick?: (event: any) => void;
  onFocus?: (event: any) => void;
  onBlur?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  ariaHidden?: boolean;
  ariaLabel?: string;
  ariaControls?: string;
  tabIndex?: number;
  dataTestId?: string;
};
const defaultProps: any = { ariaHidden: undefined };

import classes, { actionClasses, arrowClasses, chevronClasses, rowClasses } from './SideNavItem.styles';
import GiKeyboardArrowDownIcon from '../icons/KeyboardArrowDown';
import { tv } from 'tailwind-variants';
const contentClasses = tv({
  base: 'gi-side-nav-group',
  variants: {
    open: {
      true: 'gi-block',
      false: 'gi-hidden',
    },
  },
  defaultVariants: {
    open: false,
  },
});

@Component({
  selector: 'gi-side-nav-group',
  template: `
    <li class="gi-list-none gi-mt-1 gi-side-nav-list" [attr.aria-hidden]="ariaHidden">
      <div [class]="rowClasses()">
        <button
          type="button"
          [attr.id]="id"
          [class]="
            classes({
              disabled: !!disabled,
              className: className,
            })
          "
          [ngStyle]="styles"
          [attr.disabled]="disabled || undefined"
          (click)="onClick && this.onClick.emit($event)"
          (focus)="onFocus && this.onFocus.emit($event)"
          (blur)="onBlur && this.onBlur.emit($event)"
          (keydown)="onKeyDown && this.onKeyDown.emit($event)"
          (keyup)="onKeyUp && this.onKeyUp.emit($event)"
          [attr.aria-label]="ariaLabel"
          [attr.aria-expanded]="!!open"
          [attr.aria-controls]="ariaControls"
          [attr.tabIndex]="ariaHidden ? -1 : tabIndex"
          [attr.data-testid]="dataTestId"
        >
          <ng-content select="[label]"></ng-content>
        </button>
        <div
          [class]="
            actionClasses({
              last: false,
            })
          "
        >
          <ng-content select="[actions]"></ng-content>
        </div>
        <div aria-hidden="true" [class]="chevronClasses()">
          <gi-keyboard-arrow-down-icon
            [className]="
              arrowClasses({
                open: !!open,
              })
            "
          ></gi-keyboard-arrow-down-icon>
        </div>
      </div>
      <ul
        [attr.id]="ariaControls"
        [class]="
          contentClasses({
            open: !!open,
          })
        "
      >
        <ng-content></ng-content>
      </ul>
    </li>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiKeyboardArrowDownIcon],
})
export default class SideNavGroup {
  contentClasses = contentClasses;
  classes = classes;
  actionClasses = actionClasses;
  arrowClasses = arrowClasses;
  chevronClasses = chevronClasses;
  rowClasses = rowClasses;

  @Input() ariaHidden: Props['ariaHidden'] = defaultProps['ariaHidden'];
  @Input() id!: Props['id'];
  @Input() disabled!: Props['disabled'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() open!: Props['open'];
  @Input() ariaControls!: Props['ariaControls'];
  @Input() tabIndex!: Props['tabIndex'];
  @Input() dataTestId!: Props['dataTestId'];
  @Output() onClick = new EventEmitter<any>();
  @Output() onFocus = new EventEmitter<any>();
  @Output() onBlur = new EventEmitter<any>();
  @Output() onKeyDown = new EventEmitter<any>();
  @Output() onKeyUp = new EventEmitter<any>();
}
