/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavGroup.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  open?: boolean;
  actions?: any;
  value?: string;
  label: any;
  disabled?: boolean;
  className?: string;
  onClick?: (event: any) => void;
  ariaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false' | boolean;
  ariaLabel?: string;
  dataTestId?: string;
};
const defaultProps: any = { open: false, disabled: false };

import classes, { actionClasses, arrowClasses } from './SideNavItem.styles';
import GiSideNavRow from './SideNavRow';
import GiKeyboardArrowDownIcon from '../icons/KeyboardArrowDown';
import GiBox from '../Box';

@Component({
  selector: 'gi-side-nav-group',
  template: `
    <ng-container
      ><gi-side-nav-row
        ><button
          [attr.id]="id"
          [class]="
            classes({
              disabled: disabled,
              hasAction: !!actions,
              className: className,
            })
          "
          [attr.value]="value"
          (click)="onClick && this.onClick.emit($event)"
          [attr.data-testid]="dataTestId"
          [attr.aria-current]="ariaCurrent"
          [attr.aria-label]="ariaLabel"
        >
          <ng-content select="[label]">{{ label }}</ng-content>
        </button>
        <ng-container *ngIf="!!actions"
          ><gi-box
            [className]="
              actionClasses({
                expandable: true,
              })
            "
            ><ng-content select="[actions]">{{ actions }}</ng-content></gi-box
          ></ng-container
        >
        <gi-keyboard-arrow-down-icon
          [className]="
            arrowClasses({
              open: open,
            })
          "
        ></gi-keyboard-arrow-down-icon
      ></gi-side-nav-row>
      <ng-container *ngIf="open"
        ><ul class="gi-side-nav-group">
          <ng-content></ng-content></ul></ng-container
    ></ng-container>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiSideNavRow, GiBox, GiKeyboardArrowDownIcon],
})
export default class SideNavGroup {
  classes = classes;
  actionClasses = actionClasses;
  arrowClasses = arrowClasses;

  @Input() id!: Props['id'];
  @Input() disabled: Props['disabled'] = defaultProps['disabled'];
  @Input() actions!: Props['actions'];
  @Input() className!: Props['className'];
  @Input() value!: Props['value'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() ariaCurrent!: Props['ariaCurrent'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() label!: Props['label'];
  @Input() open: Props['open'] = defaultProps['open'];
  @Output() onClick = new EventEmitter<any>();
}
