/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavItemLink.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  href: string;
  actions?: any;
  disabled?: boolean;
  className?: string;
  external?: boolean;
  target?: '_self' | '_blank' | '_parent' | '_top';
  rel?: string;
  download?: string | boolean;
  ariaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false' | boolean;
  ariaLabel?: string;
  ariaHidden?: boolean | 'true' | 'false';
  ariaLabelledBy?: string;
  ariaDescribedBy?: string;
  tabIndex?: number;
  lang?: string;
  styles?: Record<string, string>;
  onClick?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  dataTestId?: string;
};
const defaultProps: any = { disabled: false, external: false, download: undefined, ariaHidden: false };

import classes, { actionClasses } from './SideNavItem.styles';
import GiSideNavRow from './SideNavRow';
import GiBox from '../Box';

@Component({
  selector: 'gi-side-nav-item-link',
  template: `
    <gi-side-nav-row [ariaHidden]="ariaHidden"
      ><a
        [attr.id]="id"
        [attr.href]="href"
        [attr.target]="target ?? (external ? '_blank' : undefined)"
        [attr.rel]="rel ?? (external ? 'noreferrer noopener' : undefined)"
        [attr.download]="download"
        (click)="onClick && this.onClick.emit($event)"
        [class]="
          classes({
            disabled: disabled,
            hasAction: !!actions,
            className: ['gi-side-nav-item-link', className],
          })
        "
        [ngStyle]="styles"
        [attr.data-testid]="dataTestId"
        [attr.aria-current]="ariaCurrent"
        [attr.aria-label]="ariaLabel"
        [attr.aria-labelledby]="ariaLabelledBy"
        [attr.aria-describedby]="ariaDescribedBy"
        [attr.tabIndex]="ariaHidden ? -1 : tabIndex"
        [attr.lang]="lang"
        (keydown)="onKeyDown && this.onKeyDown.emit($event)"
        (keyup)="onKeyUp && this.onKeyUp.emit($event)"
        ><ng-content></ng-content
      ></a>
      <ng-container *ngIf="!!actions"
        ><gi-box
          [className]="
            actionClasses({
              expandable: true,
            })
          "
          ><ng-content select="[actions]">{{ actions }}</ng-content></gi-box
        ></ng-container
      ></gi-side-nav-row
    >
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiSideNavRow, GiBox],
})
export default class SideNavItem {
  classes = classes;
  actionClasses = actionClasses;

  @Input() ariaHidden: Props['ariaHidden'] = defaultProps['ariaHidden'];
  @Input() id!: Props['id'];
  @Input() href!: Props['href'];
  @Input() target!: Props['target'];
  @Input() external: Props['external'] = defaultProps['external'];
  @Input() rel!: Props['rel'];
  @Input() download: Props['download'] = defaultProps['download'];
  @Input() disabled: Props['disabled'] = defaultProps['disabled'];
  @Input() actions!: Props['actions'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() ariaCurrent!: Props['ariaCurrent'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() ariaDescribedBy!: Props['ariaDescribedBy'];
  @Input() tabIndex!: Props['tabIndex'];
  @Input() lang!: Props['lang'];
  @Output() onClick = new EventEmitter<any>();
  @Output() onKeyDown = new EventEmitter<any>();
  @Output() onKeyUp = new EventEmitter<any>();
}
