import type { MitosisPlugin } from '@builder.io/mitosis';
import path from 'node:path';
import { postProcess } from './post-process';

/**
 * Prepends an auto-generation notice to every Mitosis-emitted file.
 * `.vue` SFCs get an HTML comment, since a top-level JS comment is not valid in them.
 */
const annotation: MitosisPlugin = () => ({
  build: {
    post: postProcess((code, { filePath, lite }) => {
      const { dir, name } = path.parse(filePath);
      const notice = `
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in \`packages/core/${lite ? path.join(dir, `${name}.lite.tsx`) : filePath}\`
`;
      const comment = filePath.endsWith('.vue') ? `<!--${notice}-->` : `/*${notice} */`;
      return `${comment}\n\n${code}`;
    }),
  },
});

export default annotation;
