/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/ArrowDropUp.lite.tsx`
 */

import * as React from 'react';

import { IconProps } from './types';

function ArrowDropUp(props: IconProps) {
  return (
    <svg
      viewBox="0 -960 960 960"
      xmlns="http://www.w3.org/2000/svg"
      width={props.size ?? 24}
      height={props.size ?? 24}
      className={props.className}
      id={props.id}
      role={props.label ? 'img' : undefined}
      aria-label={props.label}
      aria-hidden={!props.label}
      fill={props.color ?? 'currentColor'}
      data-testid={props.dataTestId ?? 'arrow_drop_up'}
    >
      <path d="m280-400 200-200 200 200H280Z" />
    </svg>
  );
}

export default ArrowDropUp;
