'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { GovieParagraph as GovieParagraphElement, defineCustomElement as defineGovieParagraph } from "@ogcio/govie-component-library/components/govie-paragraph.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type GovieParagraphEvents = NonNullable<unknown>;

export const GovieParagraph: StencilReactComponent<GovieParagraphElement, GovieParagraphEvents> = /*@__PURE__*/ createComponent<GovieParagraphElement, GovieParagraphEvents>({
    tagName: 'govie-paragraph',
    elementClass: GovieParagraphElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as GovieParagraphEvents,
    defineCustomElement: defineGovieParagraph
});
