/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from '';

import { GovieParagraph as GovieParagraphElement } from "@ogcio/govie-component-library/components/govie-paragraph.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type ReactWebComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type GovieParagraphEvents = NonNullable<unknown>;

export const GovieParagraph: StencilReactComponent<GovieParagraphElement, GovieParagraphEvents> = /*@__PURE__*/ createComponent<GovieParagraphElement, GovieParagraphEvents>({
    tagName: 'govie-paragraph',
    properties: {
        as: 'as',
        size: 'size',
        align: 'align',
        whitespace: 'whitespace',
        ariaLabel: 'aria-label',
        dataTestid: 'data-testid'
    },
    hydrateModule: import('@ogcio/govie-component-library/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.GovieParagraph as ReactWebComponent<GovieParagraphElement, GovieParagraphEvents>,
    serializeShadowRoot,
});
