/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/heading/H1.lite.tsx`
 */

import * as React from 'react';

import classes from './styles';
import { getSize } from './styles';
import type { Props } from './types';

function H1(props: Props) {
  return (
    <h1
      id={props.id}
      className={classes({
        size: getSize(props.size, 'xl'),
        className: props.className,
      })}
      data-testid={props.dataTestId}
    >
      {props.children}
    </h1>
  );
}

export default H1;
