// must be sorted alphabetically
export const iconIds = [
  'arrow_forward',
  'arrow_left_alt',
  'arrow_right_alt',
  'attach_file',
  'call',
  'check',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'close',
  'content_copy',
  'delete',
  'download',
  'edit',
  'error',
  'home',
  'info',
  'keyboard_arrow_down',
  'location_on',
  'logout',
  'mail',
  'menu',
  'mic',
  'more_horiz',
  'open_in_new',
  'search',
  'send',
  'thumb_down',
  'thumb_up',
  'warning',
] as const;

export const Icons = [...iconIds];
