trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

parameters:
  - name: application
    type: object
    default:
      name: design-system-websites
      imageName: design-system-websites
      dockerFilePath: ./Dockerfile
  - name: techStack
    type: object
    default:
      runtime: node
      runtimeVersion: 24.x
      packageManager: pnpm
      packageManagerVersion: 10.33.0
      baseImageOs: alpine
  - name: autoReleaseCommitMessagePrefix
    default: "chore(auto-release):"
  - name: vmImage
    type: string
    default: "ubuntu-24.04"

variables:
  - group: design-system
  - name: isDefaultBranch
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  - template: pipeline-variables/shared-services.yaml
  - group: ogcio-release-please

resources:
  repositories:
    - repository: pipeline-templates
      type: github
      endpoint: ogcio
      name: ogcio/building-blocks-pipelines
      ref: refs/tags/v0.14.0
    - repository: design-system-k8s-apps
      type: github
      endpoint: ogcio
      name: ogcio/design-system-k8s-apps
      ref: main

stages:
  - template: stages/static-quality-checks.yml@pipeline-templates
    parameters:
      techStack: ${{ parameters.techStack }}

  - template: stages/unit-tests.yml@pipeline-templates
    parameters:
      techStack: ${{ parameters.techStack }}
      application:
        name: ${{ parameters.application.name }}
        unitTestsContainer: ${{ variables.playwrightImage }}
        customUnitTestsSteps:
          - script: pnpm install --frozen-lockfile
            displayName: Install dependencies
          - script: pnpm run build
            displayName: Build Libraries
          - script: pnpm run test
            displayName: Run Tests
        coverageDirectories:
          - component: html
            path: $(System.DefaultWorkingDirectory)/packages/html/ds/coverage
          - component: react
            path: $(System.DefaultWorkingDirectory)/packages/react/coverage
      dependsOnStages:
        - staticQualityChecks

  - stage: configureDeployment
    displayName: Configure deployment
    dependsOn:
      - staticQualityChecks
    jobs:
      - job: configureDeployment
        displayName: Configure deployment
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
          - template: templates/configure-deployment.yml
            parameters:
              autoReleaseCommitMessagePrefix: ${{ parameters.autoReleaseCommitMessagePrefix }}

  - template: stages/build-docker-image.yml@pipeline-templates
    parameters:
      techStack: ${{ parameters.techStack }}
      application:
        name: ${{ parameters.application.name }}
        dockerFilePath: ${{ parameters.application.dockerFilePath }}
        dockerImageName: ${{ parameters.application.imageName }}
        dockerBuildArguments: --build-arg DEPLOY_ENV=$(deployEnv) --build-arg NGINX_IMAGE=$(awsEcrRepository)/dhi.io/nginx:1-alpine3.23
      additionalEcrPullImages:
        - repository: "dhi.io/nginx"
          tag: "1-alpine3.23"
      variables:
        deployEnv: $[ stageDependencies.configureDeployment.configureDeployment.outputs['configureVariables.DEPLOY_ENVIRONMENT'] ]
      dependsOnStages:
        - configureDeployment

  - ${{ if eq(variables.isDefaultBranch, 'true') }}:
    - template: stages/push-image-to-ecr.yml@pipeline-templates
      parameters:
        application:
          name: ${{ parameters.application.name }}
          dockerImageName: ${{ parameters.application.imageName }}
        dependsOnStages:
          - unitTests_${{ replace(parameters.application.name, '-', '_') }}
          - scanDockerImage_${{ replace(parameters.application.name, '-', '_') }}

    - template: stages/deploy.yml@pipeline-templates
      parameters:
        manifestsRepositoryName: design-system-k8s-apps
        versionEndpointsAvailable: false
        environment:
          applications:
            - name: ${{ parameters.application.name }}
              image: ${{ parameters.application.imageName }}
        variables:
          overlaysPath: $[ stageDependencies.configureDeployment.configureDeployment.outputs['configureVariables.OVERLAYS_PATH'] ]
        dependsOnStages:
          - ecrPush_${{ replace(parameters.application.name, '-', '_') }}
          - configureDeployment

    - template: stages/release-packages.yml@pipeline-templates
      parameters:
        techStack: ${{ parameters.techStack }}
        repositoryUrl: "https://github.com/ogcio/govie-ds"
        packages:
          - name: "@ogcio/design-system-react"
            shortName: design-system-react
          - name: "@ogcio/theme-govie"
            shortName: theme-govie
          - name: "@ogcio/design-system-tailwind"
            shortName: design-system-tailwind
          - name: "@ogcio/design-system-tokens"
            shortName: design-system-tokens
        prePublishPackagesSteps:
          - task: Bash@3
            name: buildLibraries
            displayName: Build libraries
            inputs:
              targetType: inline
              script: |
                pnpm install --frozen-lockfile
                pnpm run build:libs
        postPublishPackagesSteps:
          - template: templates/publish-gh-assets.yml
        dependsOnStages:
          - unitTests_${{ replace(parameters.application.name, '-', '_') }}

    - stage: azureDevopsUpdate
      displayName: Azure DevOps Wiki Update
      dependsOn:
        - gitOps
        - publishPackages
      jobs:
        - job: updateAzureDevops
          displayName: Update Azure DevOps wiki with tickets
          pool:
            vmImage: ${{ parameters.vmImage }}
          steps:
            - checkout: self
              persistCredentials: true
              fetchDepth: 0
              displayName: Checkout code
            - template: templates/create-wiki-page.yml
            - template: templates/close-released-tickets.yml
            - template: templates/move-latest-git-tag.yml
