trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

parameters:
  - name: vmImage
    type: string
    default: "ubuntu-24.04"
  - name: services
    type: object
    default:
      - name: "design-system-websites"
        imageName: "design-system-websites"
  - name: autoReleaseCommitMessagePrefix
    default: "chore(auto-release):"

variables:
  - group: design-system
  - name: isDefaultBranch
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  - template: pipeline-variables/shared-services.yaml
  - name: developmentOverlaysPath
    value: websites/overlays/non-prod-02/dev
  - name: productionOverlaysPath
    value: websites/overlays/prod-02/prod
  - group: ogcio-release-please

resources:
  repositories:
    - repository: pipeline-templates
      type: github
      endpoint: ogcio
      name: ogcio/building-blocks-pipelines
      ref: refs/tags/v0.11.5
    - repository: design-system-k8s-apps
      type: github
      endpoint: ogcio
      name: ogcio/design-system-k8s-apps
      ref: main

stages:
  - stage: RetrieveCredentials
    displayName: Retrieve credentials from AWS Secrets Manager
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - job: readCredentials
        displayName: GitHub credentials
        steps:
          - checkout: none
          - template: gh/generate-app-token.yml@pipeline-templates
            parameters:
              githubAppId: $(RELEASE_PLEASE_APP_ID)
              githubInstallationId: $(RELEASE_PLEASE_INSTALLATION_ID)
              githubPrivateKey: $(RELEASE_PLEASE_PRIVATE_KEY)
          - script: echo "##vso[task.setvariable variable=githubTokenADO;issecret=true;isoutput=true;]$(GITHUB_TOKEN)"
            name: setGithubToken
            displayName: Expose GitHub credentials

  - stage: TestCredentials
    displayName: Test GH credentials
    dependsOn: RetrieveCredentials
    jobs:
      - job: TestCredentials
        variables:
          - name: githubTokenADO
            value: $[stageDependencies.RetrieveCredentials.readCredentials.outputs['setGithubToken.githubTokenADO']]
        displayName: Test GH credentials
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
          - task: Bash@3
            name: testCredentials
            inputs:
              targetType: "inline"
              script: |
                if [ -z "$GITHUB_TOKEN" ]; then
                  echo "GITHUB_TOKEN is not set. Please set the GITHUB_TOKEN environment variable."
                  exit 1
                fi
                
                echo "GH_TOKEN: ${GITHUB_TOKEN:0:3}...${GITHUB_TOKEN: -3}"
                
                ENDPOINT_2="https://api.github.com/repos/ogcio/govie-ds"

                HTTP_CODE_2=$(curl -s -o /dev/null -w "%{http_code}" \
                  -H "Authorization: token $GITHUB_TOKEN" \
                  -H "Accept: application/vnd.github+json" \
                  "$ENDPOINT_2")

                echo "$ENDPOINT_2: $HTTP_CODE_2"
            env:
              GITHUB_TOKEN: $(githubTokenADO)
