trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - main

parameters:
  - name: vmImage
    type: string
    default: "ubuntu-24.04"
  - name: services
    type: object
    default:
      - name: "design-system-websites"
        imageName: "design-system-websites"
  - name: autoReleaseCommitMessagePrefix
    default: "chore(auto-release):"

variables:
  - name: isDefaultBranch
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  - template: pipeline-variables/shared-services.yaml
  - name: developmentOverlaysPath
    value: websites/overlays/non-prod-02/dev
  - name: productionOverlaysPath
    value: websites/overlays/prod-02/prod

resources:
  repositories:
    - repository: pipeline-templates
      type: github
      endpoint: ogcio
      name: ogcio/building-blocks-pipelines
      ref: main
    - repository: design-system-k8s-apps
      type: github
      endpoint: ogcio
      name: ogcio/design-system-k8s-apps
      ref: main

stages:
  - stage: setup
    displayName: Setup Dependencies
    dependsOn: []
    jobs:
      - job: SetupDependencies
        displayName: Setup pnpm and Install Dependencies
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
          - template: tools/install-pnpm.yml@pipeline-templates

  - stage: CheckForChanges
    displayName: Check for Changes
    dependsOn: setup
    jobs:
      - job: CheckForChanges
        displayName: Check for Changes in Libraries
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
          - checkout: self
            displayName: "Get Full Git History"
            fetchDepth: 2
            clean: true
            fetchFilter: tree:0

          - task: PowerShell@2
            inputs:
              targetType: "inline"
              script: |
                $changedfiles = git log -1 --name-only --pretty='' | Join-String -Separator ', '
                Write-Host $changedfiles
                If ($changedfiles.Contains("react/ds/") -or $changedfiles.Contains("html/ds/") -or $changedfiles.Contains("tokens/") -or $changedfiles.Contains("tailwind/")) {
                  echo "Changes detected in design system libraries."
                  echo "##vso[task.setvariable variable=IfRunTests;isOutput=true]run"
                }
            name: "DetermineIfRunTests"

  - stage: Chromatic_HTML
    displayName: Chromatic for HTML Library
    dependsOn: CheckForChanges
    condition: eq(dependencies.CheckForChanges.outputs['DetermineIfRunTests.IfRunTests'],'run')
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - job: Chromatic_Deploy
        displayName: "Build and Upload Chromatic"
        steps:
          - checkout: self
            displayName: "Get Full Git History"
            fetchDepth: 0

          - template: tools/install-pnpm.yml@pipeline-templates

          - script: |
              pnpm build:libs
              pnpm html:storybook:build
            displayName: "Build Storybook for HTML Library"

          - task: CmdLine@2
            displayName: "Run Chromatic"
            inputs:
              script: npx chromatic --config-file packages/html/ds/chromatic.config.json
            env:
              CHROMATIC_PROJECT_TOKEN: $(CHROMATIC_PROJECT_TOKEN_HTML)

  - stage: Chromatic_React
    displayName: Chromatic for React Library
    dependsOn: CheckForChanges
    condition: eq(dependencies.CheckForChanges.outputs['DetermineIfRunTests.IfRunTests'],'run')
    pool:
      vmImage: ${{ parameters.vmImage }}
    jobs:
      - job: Chromatic_Deploy
        displayName: "Build and Upload Chromatic"
        steps:
          - checkout: self
            displayName: "Get Full Git History"
            fetchDepth: 0

          - template: tools/install-pnpm.yml@pipeline-templates

          - script: |
              pnpm build:libs
              pnpm react:storybook:build
            displayName: "Build Storybook for React Library"

          - task: CmdLine@2
            displayName: "Run Chromatic"
            inputs:
              script: npx chromatic --config-file packages/react/ds/chromatic.config.json
            env:
              CHROMATIC_PROJECT_TOKEN: $(CHROMATIC_PROJECT_TOKEN_REACT)

  - stage: Playwright
    displayName: Playwright for React Library
    dependsOn: CheckForChanges
    condition: eq(dependencies.CheckForChanges.outputs['DetermineIfRunTests.IfRunTests'],'run')
    jobs:
      - job: Playwright_Test
        displayName: "Run Playwright Tests"
        pool:
          vmImage: ${{ parameters.vmImage }}
        container: mcr.microsoft.com/playwright:v1.55.0-noble
        strategy:
          matrix:
            chromium:
              project: chromium
            firefox:
              project: firefox
            webkit:
              project: webkit
            android:
              project: android
            iphone:
              project: iphone
        steps:
          - template: tools/install-pnpm.yml@pipeline-templates

          - script: |
              pnpm build:libs
              pnpm react:storybook:build
            displayName: "Build Storybook for React Library"

          - script: |
              cd packages/react/ds
              pnpm playwright test --project=$(project) --shard=$(shard)
            displayName: "Run Tests"
            # pnpm --filter "@ogcio/design-system-react" playwright:test
            env:
              CI: "true"

          - task: PublishTestResults@2
            displayName: "Publish test results"
            inputs:
              searchFolder: "$(System.DefaultWorkingDirectory)/packages/react/ds/test-results"
              testResultsFormat: "JUnit"
              testResultsFiles: "results.xml"
              testRunTitle: "Playwright Tests"
            condition: succeededOrFailed()

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/packages/react/ds/test-results"
              artifact: $(project)
              publishLocation: "pipeline"
            condition: succeededOrFailed()
