/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/icons/logos/index.ts`
 */

export { default as LogoBlack } from './LogoBlack.vue';
export { default as LogoGoldGreen } from './LogoGoldGreen.vue';
export { default as LogoGoldWhite } from './LogoGoldWhite.vue';
export { default as LogoHarpBlack } from './LogoHarpBlack.vue';
export { default as LogoHarpWhite } from './LogoHarpWhite.vue';
export { default as LogoWhite } from './LogoWhite.vue';
