name: Feature Request
description: Suggest a new component, pattern, or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or improved? You can include screenshots by pasting or dragging images here.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve? Why is it needed?
      placeholder: e.g. Currently there is no way to...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Package
      options:
        - "@ogcio/design-system-react"
        - "@ogcio/design-system-html"
        - "@ogcio/design-system-angular"
        - "@ogcio/design-system-tailwind"
        - "Other"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: References, examples, or anything else relevant.
    validations:
      required: false
