<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/footer/FooterSection.lite.tsx`
-->

<template>
  <GiBox
    :id="id"
    :className="
      classes({
        variant: getVariant(variant),
      })
    "
    :styles="styles"
    :dataTestId="dataTestId"
    ><GiContainer
      :maxWidth="maxWidth"
      :className="
        contentClasses({
          variant: getVariant(variant),
          className: className,
        })
      "
      ><slot /></GiContainer
  ></GiBox>
</template>

<script setup lang="ts">
import { tv } from 'tailwind-variants';
import { SurfaceVariant } from '../constants';
import type { MaxWidth, ValueOf } from '../constants';
import { clamp } from '../utilities';
import GiBox from '../Box.vue';
import GiContainer from '../Container.vue';
const getVariant = (x: Props['variant']) => clamp(x, SurfaceVariant, SurfaceVariant.PRIMARY);
const classes = tv({
  base: 'gi-footer-section gi-w-full',
  variants: {
    variant: {
      primary: 'gi-bg-color-surface-system-neutral-layer1',
      utility: 'gi-bg-color-surface-system-neutral-layer2',
    },
  },
  defaultVariants: {
    variant: 'primary',
  },
});
const contentClasses = tv({
  base: 'gi-footer-section-container',
  variants: {
    variant: {
      primary: 'gi-py-8 md:gi-py-10',
      utility: 'gi-py-4',
    },
  },
  defaultVariants: {
    variant: 'primary',
  },
});

export type Props = {
  variant?: ValueOf<typeof SurfaceVariant>;
  maxWidth?: ValueOf<typeof MaxWidth>;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

const props = defineProps<Props>();
</script>
