/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/pagination/PaginationEllipsis.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = Omit<IconProps, 'label'>;

import GiMoreHorizontalIcon from '../icons/MoreHorizontal';
import type { IconProps } from '../icons/types';
import { tv } from 'tailwind-variants';
const classes = tv({
  base: 'gi-text-gray-700 gi-shrink-0',
});

@Component({
  selector: 'core-pagination-ellipsis',
  template: `
    <li [attr.aria-hidden]="true">
      <gi-more-horizontal-icon
        [id]="id"
        [className]="
          classes({
            className: className,
          })
        "
        [size]="size"
        [color]="color"
        [dataTestId]="dataTestId"
      ></gi-more-horizontal-icon>
    </li>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiMoreHorizontalIcon],
})
export default class PaginationEllipsis {
  classes = classes;

  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() size!: Props['size'];
  @Input() color!: Props['color'];
  @Input() dataTestId!: Props['dataTestId'];
}
