/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/pagination/PaginationLink.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

type Props = {
  current?: boolean;
  href: string;
  id?: string;
  className?: string;
  onClick?: (event: any) => void;
  onFocus?: (event: any) => void;
  onBlur?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  ariaLabel?: string;
};

import LinkButton from '../LinkButton';

@Component({
  selector: 'core-pagination-link',
  template: `
    <li>
      <link-button
        size="lg"
        appearance="dark"
        [href]="href"
        [id]="id"
        [className]="className"
        [variant]="current ? 'primary' : 'flat'"
        [ariaCurrent]="current ? 'page' : undefined"
        [ariaLabel]="ariaLabel"
        (click)="onClick && this.onClick.emit($event)"
        (focus)="onFocus && this.onFocus.emit($event)"
        (blur)="onBlur && this.onBlur.emit($event)"
        (keydown)="onKeyDown && this.onKeyDown.emit($event)"
        (keyup)="onKeyUp && this.onKeyUp.emit($event)"
      >
        <ng-content></ng-content>
      </link-button>
    </li>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, LinkButton],
})
export default class PaginationLink {
  @Input() href!: Props['href'];
  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() current!: Props['current'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Output() onClick = new EventEmitter<any>();
  @Output() onFocus = new EventEmitter<any>();
  @Output() onBlur = new EventEmitter<any>();
  @Output() onKeyDown = new EventEmitter<any>();
  @Output() onKeyUp = new EventEmitter<any>();
}
