<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/heading/H2.lite.tsx`
-->

<template>
  <h2
    :id="id"
    :class="
      classes({
        size: getSize(size, 'lg'),
        className: className,
      })
    "
    :data-testid="dataTestId"
  >
    <slot />
  </h2>
</template>

<script setup lang="ts">
import classes from './styles';
import { getSize } from './styles';
import type { Props } from './types';

const props = defineProps<Props>();
</script>
