/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/heading/types.ts`
 */

import type { ValueOf } from '../constants';
export const Size = {
  XL: 'xl',
  LG: 'lg',
  MD: 'md',
  SM: 'sm',
  XS: 'xs',
  XXS: '2xs',
} as const;
export type Props = {
  id?: string;
  size?: ValueOf<typeof Size>;
  className?: string;
  children?: any;
  dataTestId?: string;
};
