/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/storybook/FooterLogo.meta.ts`
 */

import type { StoryContext, Renderer } from 'storybook/internal/types';
import { within } from 'storybook/test';
import { checker } from './utilities';
export const footerLogoMeta = {
  tags: ['autodocs'] as string[],
  title: 'Layout/Footer/FooterLogo',
  args: {
    dataTestId: 'footer-logo',
    id: 'footer-logo-id',
  },
  argTypes: {
    id: {
      control: {
        disable: true,
      },
      description: 'Optional id for linking/targeting and aria references.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    className: {
      control: {
        disable: true,
      },
      description: 'CSS classes to apply. Use `gi-*` Tailwind utilities.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    styles: {
      control: {
        disable: true,
      },
      description:
        'Inline styles applied directly to the element. Use for truly dynamic values that cannot be expressed as Tailwind classes.',
      table: {
        type: {
          summary: 'Record<string, string>',
        },
      },
    },
    dataTestId: {
      control: {
        disable: true,
      },
      description: 'Test id for targeting the element in automated tests.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    children: {
      table: {
        disable: true,
      },
    },
  },
  parameters: {
    docs: {
      description: {
        component: 'Container for the Gov.ie logo within a footer layout.',
      },
    },
  },
};
export const Default = {
  play: async ({ canvasElement, step, args }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    await checker(args.dataTestId, canvas, step).is('div');
    await checker(args.dataTestId, canvas, step).attributes({
      id: args.id,
    });
  },
};
