/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/storybook/HeaderLogo.meta.ts`
 */

import type { StoryContext, Renderer } from 'storybook/internal/types';
import { within, expect } from 'storybook/test';
import { boxMeta } from './Box.meta';
export const headerLogoMeta = {
  tags: ['autodocs'] as string[],
  title: 'Layout/Header/HeaderLogo',
  args: {
    children: undefined,
    className: undefined,
    styles: undefined,
    id: 'header-logo-id',
    dataTestId: 'header-logo',
  },
  argTypes: {
    className: boxMeta.argTypes.className,
    styles: boxMeta.argTypes.styles,
    id: boxMeta.argTypes.id,
    dataTestId: boxMeta.argTypes.dataTestId,
  },
  parameters: {
    docs: {
      description: {
        component: 'Container for the site logo within a header layout.',
      },
    },
  },
};
export const Default = {
  args: headerLogoMeta.args,
  play: async ({ canvasElement, step, args }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    await step('passes dataTestId through', async () => {
      expect(canvas.getByTestId(args.dataTestId)).toBeInTheDocument();
    });
  },
};
