/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/storybook/SideNavItemLink.meta.ts`
 */

import type { ArgTypes, StoryContext, Renderer } from 'storybook/internal/types';
import { within } from 'storybook/test';
import type { Props } from '../sidenav/SideNavItemLink';
import { linkMeta } from './Link.meta';
import { checker } from './utilities';
export const sideNavItemLinkMeta = {
  tags: ['autodocs'] as string[],
  title: 'Navigation/SideNav/SideNavItemLink',
  args: {
    children: 'Homepage',
    href: '#',
    selected: false,
    id: 'side-nav-item-link-id',
    dataTestId: 'side-nav-item-link',
  },
  argTypes: {
    selected: {
      control: 'boolean',
      description: 'Marks the link as the current selection. Applies the selected accent treatment.',
      table: {
        type: {
          summary: 'boolean',
        },
        defaultValue: {
          summary: 'false',
        },
      },
    },
    actions: {
      control: {
        disable: true,
      },
      description: 'Trailing action slot rendered beside the link (for example an IconButton).',
      table: {
        type: {
          summary: 'ReactNode',
        },
      },
    },
    id: linkMeta.argTypes.id,
    href: linkMeta.argTypes.href,
    className: linkMeta.argTypes.className,
    external: linkMeta.argTypes.external,
    target: linkMeta.argTypes.target,
    rel: linkMeta.argTypes.rel,
    download: linkMeta.argTypes.download,
    ariaCurrent: linkMeta.argTypes.ariaCurrent,
    ariaLabel: linkMeta.argTypes.ariaLabel,
    ariaLabelledBy: linkMeta.argTypes.ariaLabelledBy,
    ariaDescribedBy: linkMeta.argTypes.ariaDescribedBy,
    ariaHidden: linkMeta.argTypes.ariaHidden,
    tabIndex: linkMeta.argTypes.tabIndex,
    lang: linkMeta.argTypes.lang,
    styles: linkMeta.argTypes.styles,
    dataTestId: linkMeta.argTypes.dataTestId,
    onClick: {
      action: 'clicked',
      description: 'Click handler for the link.',
      table: {
        type: {
          summary: '(event) => void',
        },
      },
    },
    onKeyDown: {
      action: 'keydown',
      description: 'Key down handler for the link.',
      table: {
        type: {
          summary: '(event) => void',
        },
      },
    },
    onKeyUp: {
      action: 'keyup',
      description: 'Key up handler for the link.',
      table: {
        type: {
          summary: '(event) => void',
        },
      },
    },
  } satisfies ArgTypes<Props>,
  parameters: {
    docs: {
      description: {
        component:
          'Link-style navigation item for SideNav. Renders an anchor in a list item with SideNav item styling. Use for destinations that navigate to a URL.',
      },
    },
  },
};
export const Default = {
  args: sideNavItemLinkMeta.args,
  play: async ({ canvasElement, step, args }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    const check = checker(args.dataTestId, canvas, step);
    await check.is('a');
    await check.attributes({
      id: args.id,
      href: args.href,
    });
    await check.children();
  },
};
