/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ParagraphAlign, ParagraphAs, ParagraphSize, ParagraphWhitespace } from "./components/paragraph/paragraph";
export { ParagraphAlign, ParagraphAs, ParagraphSize, ParagraphWhitespace } from "./components/paragraph/paragraph";
export namespace Components {
    interface GovieParagraph {
        /**
          * @default 'start'
         */
        "align": ParagraphAlign;
        /**
          * @default 'p'
         */
        "as": ParagraphAs;
        /**
          * @default 'md'
         */
        "size": ParagraphSize;
        /**
          * @default 'normal'
         */
        "whitespace": ParagraphWhitespace;
    }
}
declare global {
    interface HTMLGovieParagraphElement extends Components.GovieParagraph, HTMLStencilElement {
    }
    var HTMLGovieParagraphElement: {
        prototype: HTMLGovieParagraphElement;
        new (): HTMLGovieParagraphElement;
    };
    interface HTMLElementTagNameMap {
        "govie-paragraph": HTMLGovieParagraphElement;
    }
}
declare namespace LocalJSX {
    interface GovieParagraph {
        /**
          * @default 'start'
         */
        "align"?: ParagraphAlign;
        /**
          * @default 'p'
         */
        "as"?: ParagraphAs;
        /**
          * @default 'md'
         */
        "size"?: ParagraphSize;
        /**
          * @default 'normal'
         */
        "whitespace"?: ParagraphWhitespace;
    }
    interface IntrinsicElements {
        "govie-paragraph": GovieParagraph;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "govie-paragraph": LocalJSX.GovieParagraph & JSXBase.HTMLAttributes<HTMLGovieParagraphElement>;
        }
    }
}
