/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonProps } from "./components/button/types.js";
import { ParagraphAlign, ParagraphAs, ParagraphSize, ParagraphWhitespace } from "./components/paragraph/paragraph";
export { ButtonProps } from "./components/button/types.js";
export { ParagraphAlign, ParagraphAs, ParagraphSize, ParagraphWhitespace } from "./components/paragraph/paragraph";
export namespace Components {
    interface GovieButton {
        "appearance"?: ButtonProps['appearance'];
        "class"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        "size"?: ButtonProps['size'];
        "variant"?: ButtonProps['variant'];
    }
    interface GovieParagraph {
        /**
          * @default 'start'
         */
        "align": ParagraphAlign;
        "ariaLabel"?: string;
        /**
          * @default 'p'
         */
        "as": ParagraphAs;
        "dataTestid"?: string;
        /**
          * @default 'md'
         */
        "size": ParagraphSize;
        /**
          * @default 'normal'
         */
        "whitespace": ParagraphWhitespace;
    }
}
declare global {
    interface HTMLGovieButtonElement extends Components.GovieButton, HTMLStencilElement {
    }
    var HTMLGovieButtonElement: {
        prototype: HTMLGovieButtonElement;
        new (): HTMLGovieButtonElement;
    };
    interface HTMLGovieParagraphElement extends Components.GovieParagraph, HTMLStencilElement {
    }
    var HTMLGovieParagraphElement: {
        prototype: HTMLGovieParagraphElement;
        new (): HTMLGovieParagraphElement;
    };
    interface HTMLElementTagNameMap {
        "govie-button": HTMLGovieButtonElement;
        "govie-paragraph": HTMLGovieParagraphElement;
    }
}
declare namespace LocalJSX {
    interface GovieButton {
        "appearance"?: ButtonProps['appearance'];
        "class"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "size"?: ButtonProps['size'];
        "variant"?: ButtonProps['variant'];
    }
    interface GovieParagraph {
        /**
          * @default 'start'
         */
        "align"?: ParagraphAlign;
        "ariaLabel"?: string;
        /**
          * @default 'p'
         */
        "as"?: ParagraphAs;
        "dataTestid"?: string;
        /**
          * @default 'md'
         */
        "size"?: ParagraphSize;
        /**
          * @default 'normal'
         */
        "whitespace"?: ParagraphWhitespace;
    }
    interface IntrinsicElements {
        "govie-button": GovieButton;
        "govie-paragraph": GovieParagraph;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "govie-button": LocalJSX.GovieButton & JSXBase.HTMLAttributes<HTMLGovieButtonElement>;
            "govie-paragraph": LocalJSX.GovieParagraph & JSXBase.HTMLAttributes<HTMLGovieParagraphElement>;
        }
    }
}
