/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Box.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  className?: string;
  children?: any;
  id?: string;
  dataTestId?: string;
};

@Component({
  selector: 'gi-box',
  template: ` <div [attr.id]="id" [class]="className" [attr.data-testid]="dataTestId"><ng-content></ng-content></div> `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Box {
  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() dataTestId!: Props['dataTestId'];
}
