/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/BoxButton.lite.tsx`
 */

import { Component, Input } from "@angular/core";

import { CommonModule } from "@angular/common";

export type BoxButtonProps = {
  className?: string;
  variant?: "primary" | "secondary";
  onClick?: (event: any) => void;
  children?: any;
};

import DsButton from "./DsButton";

@Component({
  selector: "box-button",
  template: `
    <div
      [class]="'p-4 rounded-md border border-slate-200 ' + (className ?? '')"
    >
      <ds-button [variant]="variant" (click)="onClick?.($event)"
        ><ng-content></ng-content
      ></ds-button>
    </div>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, DsButton],
})
export default class BoxButton {
  @Input() className!: BoxButtonProps["className"];
  @Input() variant!: BoxButtonProps["variant"];
  @Input() onClick!: BoxButtonProps["onClick"];
}

