/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Button.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  variant?: (typeof Variant)[keyof typeof Variant];
  appearance?: (typeof Appearance)[keyof typeof Appearance];
  size?: (typeof ButtonSize)[keyof typeof ButtonSize];
  children?: any;
  disabled?: boolean;
  className?: string;
  onClick?: (event: any) => void;
  onFocus?: (event: any) => void;
  onBlur?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  ariaLabel?: string;
  ariaLabelledBy?: string;
  ariaDescribedBy?: string;
  ariaChecked?: boolean;
  ariaPressed?: boolean | 'mixed';
  ariaExpanded?: boolean;
  ariaControls?: string;
  ariaHasPopup?: 'menu' | 'listbox' | 'dialog' | 'grid' | 'tree' | boolean;
  ariaBusy?: boolean;
  role?: string;
  type?: 'button' | 'submit' | 'reset';
  form?: string;
  value?: string;
  tabIndex?: number;
  dataTestId?: string;
  ref?: any;
};

import { tv } from 'tailwind-variants';
import { Variant, Appearance, Size } from './utilities';
export const ButtonSize = {
  SM: Size.SM,
  MD: Size.MD,
  LG: Size.LG,
} as const;
export const buttonBaseStyles = tv({
  base: [
    'gi-font-primary',
    'gi-border-solid',
    'gi-border-sm',
    'gi-flex',
    'gi-rounded-sm',
    'gi-items-center',
    'disabled:gi-cursor-not-allowed',
    'disabled:gi-pointer-events-none',
    'enabled:focus:gi-outline',
    'enabled:focus:gi-outline-sm',
    'enabled:focus:gi-outline-color-shadow-intent-focus-default',
    'enabled:focus:gi-outline-offset-0',
    'enabled:focus:gi-border-solid',
    'enabled:focus:gi-border-color-border-intent-focus-default',
    'enabled:focus:gi-border-sm',
    'enabled:focus:gi-rounded-sm',
  ],
  variants: {
    variant: {
      primary: [
        'gi-border-transparent',
        'enabled:focus:gi-shadow-color-border-intent-focus-light',
        'enabled:focus:gi-shadow-[inset_0_0_0_2px]',
      ],
      secondary: [],
      flat: ['gi-border-base-transparent'],
    },
    appearance: {
      default: '',
      light: '',
      dark: '',
    },
    disabled: {
      true: '',
      false: '',
    },
  },
  compoundVariants: [
    {
      variant: 'primary',
      appearance: 'default',
      disabled: false,
      class: [
        'gi-text-color-text-tone-primary-fill-default',
        'gi-bg-color-surface-tone-primary-fill-default',
        'gi-stroke-color-text-tone-primary-fill-default',
        'hover:gi-bg-color-surface-tone-primary-fill-hover',
        'enabled:focus:gi-bg-color-surface-tone-primary-fill-hover',
      ],
    },
    {
      variant: 'primary',
      appearance: 'light',
      disabled: false,
      class: [
        'gi-text-color-text-tone-light-fill-default',
        'gi-stroke-color-text-tone-light-fill-default',
        'gi-bg-color-surface-tone-light-fill-default',
        'hover:gi-bg-color-surface-tone-light-fill-hover',
        'enabled:focus:gi-bg-color-surface-tone-light-fill-hover',
      ],
    },
    {
      variant: 'primary',
      appearance: 'dark',
      disabled: false,
      class: [
        'gi-text-color-text-tone-dark-fill-default',
        'gi-stroke-color-text-tone-dark-fill-default',
        'gi-bg-color-surface-tone-dark-fill-default',
        'hover:gi-bg-color-surface-tone-dark-fill-hover',
        'enabled:focus:gi-bg-color-surface-tone-dark-fill-hover',
      ],
    },
    {
      variant: 'primary',
      appearance: 'default',
      disabled: true,
      class: [
        'gi-bg-color-surface-tone-primary-fill-disabled',
        'gi-text-color-text-tone-primary-fill-disabled',
        'gi-stroke-color-text-tone-primary-fill-disabled',
      ],
    },
    {
      variant: 'primary',
      appearance: 'light',
      disabled: true,
      class: [
        'gi-bg-color-surface-tone-light-fill-disabled',
        'gi-text-color-text-tone-light-fill-disabled',
        'gi-stroke-color-text-tone-light-fill-disabled',
      ],
    },
    {
      variant: 'primary',
      appearance: 'dark',
      disabled: true,
      class: [
        'gi-bg-color-surface-tone-dark-fill-disabled',
        'gi-text-color-text-tone-dark-fill-disabled',
        'gi-stroke-color-text-tone-dark-fill-disabled',
      ],
    },
    {
      variant: 'secondary',
      appearance: 'default',
      disabled: false,
      class: [
        'gi-border-color-border-tone-primary-outline-default',
        'gi-text-color-text-tone-primary-outline-default',
        'gi-stroke-color-text-tone-primary-outline-default',
        'hover:gi-bg-color-surface-tone-primary-outline-hover',
        'enabled:focus:gi-bg-color-surface-tone-primary-outline-hover',
      ],
    },
    {
      variant: 'secondary',
      appearance: 'light',
      disabled: false,
      class: [
        'gi-text-color-text-tone-light-outline-default',
        'gi-stroke-color-text-tone-light-outline-default',
        'gi-border-color-border-tone-light-outline-default',
        'gi-bg-base-transparent',
        'hover:gi-bg-color-surface-tone-light-outline-hover',
        'enabled:focus:gi-bg-color-surface-tone-dark-fill-hover',
      ],
    },
    {
      variant: 'secondary',
      appearance: 'dark',
      disabled: false,
      class: [
        'gi-border-color-border-tone-dark-outline-default',
        'gi-bg-color-surface-tone-dark-outline-default',
        'hover:gi-bg-color-surface-tone-dark-outline-hover',
        'enabled:focus:gi-bg-color-surface-tone-light-fill-hover',
      ],
    },
    {
      variant: 'secondary',
      appearance: 'default',
      disabled: true,
      class: [
        'gi-border-color-border-tone-primary-outline-disabled',
        'gi-bg-color-surface-tone-primary-outline-disabled',
        'gi-text-color-text-tone-primary-outline-disabled',
        'gi-stroke-color-text-tone-primary-outline-disabled',
      ],
    },
    {
      variant: 'secondary',
      appearance: 'light',
      disabled: true,
      class: [
        'gi-bg-color-surface-tone-light-outline-disabled',
        'gi-border-color-border-tone-light-outline-disabled',
        'gi-text-color-text-tone-light-outline-disabled',
        'gi-stroke-color-text-tone-light-outline-disabled',
      ],
    },
    {
      variant: 'secondary',
      appearance: 'dark',
      disabled: true,
      class: [
        'gi-border-color-border-tone-dark-outline-disabled',
        'gi-bg-color-surface-tone-dark-fill-disabled',
        'gi-text-color-text-tone-dark-outline-disabled',
        'gi-stroke-color-text-tone-dark-outline-disabled',
      ],
    },
    {
      variant: 'flat',
      appearance: 'default',
      disabled: false,
      class: [
        'gi-text-color-text-tone-primary-flat-default',
        'gi-stroke-color-text-tone-primary-flat-default',
        'gi-bg-base-transparent',
        'hover:gi-bg-color-surface-tone-primary-flat-hover',
        'enabled:focus:gi-bg-color-surface-tone-primary-outline-hover',
      ],
    },
    {
      variant: 'flat',
      appearance: 'light',
      disabled: false,
      class: [
        'gi-bg-color-surface-tone-light-flat-default',
        'gi-text-color-text-tone-light-flat-default',
        'gi-stroke-color-text-tone-light-flat-default',
        'hover:gi-bg-color-surface-tone-light-flat-hover',
        'enabled:focus:gi-bg-color-surface-tone-dark-fill-hover',
      ],
    },
    {
      variant: 'flat',
      appearance: 'dark',
      disabled: false,
      class: [
        'gi-text-color-text-tone-dark-flat-default',
        'gi-stroke-color-text-tone-dark-flat-default',
        'hover:gi-bg-color-surface-tone-dark-flat-hover',
        'enabled:focus:gi-bg-color-surface-tone-light-fill-hover',
      ],
    },
    {
      variant: 'flat',
      appearance: 'default',
      disabled: true,
      class: [
        'gi-text-color-text-tone-primary-flat-disabled',
        'gi-stroke-color-text-tone-primary-flat-disabled',
        'gi-bg-color-surface-tone-primary-flat-disabled',
      ],
    },
    {
      variant: 'flat',
      appearance: 'light',
      disabled: true,
      class: [
        'gi-bg-color-surface-tone-light-flat-disabled',
        'gi-text-color-text-tone-light-flat-disabled',
        'gi-stroke-color-text-tone-light-flat-disabled',
      ],
    },
    {
      variant: 'flat',
      appearance: 'dark',
      disabled: true,
      class: [
        'gi-bg-color-surface-tone-dark-flat-disabled',
        'gi-text-color-text-tone-dark-flat-disabled',
        'gi-stroke-color-text-tone-dark-flat-disabled',
      ],
    },
  ],
  defaultVariants: {
    variant: 'primary',
    appearance: 'default',
    disabled: false,
  },
});
export const styles = tv({
  extend: buttonBaseStyles,
  base: ['gi-gap-2'],
  variants: {
    size: {
      sm: 'gi-h-8 gi-px-2 gi-py-1.5 gi-text-xs',
      md: 'gi-h-10 gi-px-3 gi-py-2 gi-text-sm',
      lg: 'gi-h-12 gi-px-4 gi-py-3 gi-text-2md',
    },
  },
  defaultVariants: {
    size: 'md',
  },
});
const getVariant = (x: Props['variant'] = Variant.PRIMARY) =>
  Object.values(Variant).includes(x) ? x : Variant.PRIMARY;
const getAppearance = (x: Props['appearance']) =>
  x === Appearance.LIGHT || x === Appearance.DARK ? x : Appearance.DEFAULT;
const getSize = (x: Props['size'] = ButtonSize.MD) => (Object.values(ButtonSize).includes(x) ? x : ButtonSize.MD);

@Component({
  selector: 'gi-button',
  template: `
    <button
      [attr.id]="id"
      [class]="
        styles({
          variant: getVariant(variant),
          appearance: getAppearance(appearance),
          size: getSize(size),
          disabled: !!disabled,
          class: className,
        })
      "
      [attr.data-size]="getSize(size)"
      [attr.disabled]="disabled || undefined"
      (click)="onClick && this.onClick.emit($event)"
      (focus)="onFocus && this.onFocus.emit($event)"
      (blur)="onBlur && this.onBlur.emit($event)"
      (keydown)="onKeyDown && this.onKeyDown.emit($event)"
      (keyup)="onKeyUp && this.onKeyUp.emit($event)"
      [attr.aria-label]="ariaLabel"
      [attr.aria-labelledby]="ariaLabelledBy"
      [attr.aria-describedby]="ariaDescribedBy"
      [attr.aria-checked]="ariaChecked"
      [attr.aria-pressed]="ariaPressed"
      [attr.aria-expanded]="ariaExpanded"
      [attr.aria-controls]="ariaControls"
      [attr.aria-haspopup]="ariaHasPopup"
      [attr.aria-busy]="ariaBusy"
      [attr.role]="role"
      [attr.type]="type ?? 'button'"
      [attr.form]="form"
      [attr.value]="value"
      [attr.tabIndex]="tabIndex"
      [attr.data-testid]="dataTestId"
    >
      <ng-content></ng-content>
    </button>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Button {
  styles = styles;
  getVariant = getVariant;
  getAppearance = getAppearance;
  getSize = getSize;

  @Input() id!: Props['id'];
  @Input() variant!: Props['variant'];
  @Input() appearance!: Props['appearance'];
  @Input() size!: Props['size'];
  @Input() disabled!: Props['disabled'];
  @Input() className!: Props['className'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() ariaDescribedBy!: Props['ariaDescribedBy'];
  @Input() ariaChecked!: Props['ariaChecked'];
  @Input() ariaPressed!: Props['ariaPressed'];
  @Input() ariaExpanded!: Props['ariaExpanded'];
  @Input() ariaControls!: Props['ariaControls'];
  @Input() ariaHasPopup!: Props['ariaHasPopup'];
  @Input() ariaBusy!: Props['ariaBusy'];
  @Input() role!: Props['role'];
  @Input() type!: Props['type'];
  @Input() form!: Props['form'];
  @Input() value!: Props['value'];
  @Input() tabIndex!: Props['tabIndex'];
  @Input() dataTestId!: Props['dataTestId'];
  @Output() onClick = new EventEmitter<any>();
  @Output() onFocus = new EventEmitter<any>();
  @Output() onBlur = new EventEmitter<any>();
  @Output() onKeyDown = new EventEmitter<any>();
  @Output() onKeyUp = new EventEmitter<any>();
}
