/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Container.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type ContainerInsetSizeType = (typeof ContainerInsetSizeEnum)[keyof typeof ContainerInsetSizeEnum];
export type Props = {
  children?: any;
  id?: string;
  insetTop?: ContainerInsetSizeType;
  insetBottom?: ContainerInsetSizeType;
  className?: string;
  fullWidth?: boolean;
};

import clsx from 'clsx';
export const ContainerInsetSizeEnum = {
  None: 'none',
  Medium: 'md',
  Large: 'lg',
  ExtraLarge: 'xl',
} as const;

@Component({
  selector: 'gi-container',
  template: `
    <div
      data-testid="govie-container"
      [attr.data-inset-top]="insetTop"
      [attr.data-inset-bottom]="insetBottom"
      [attr.id]="id"
      [class]="
        clsx('gi-layout-container', className, {
          'gi-layout-container-inset': insetTop || insetBottom,
          'gi-layout-container-full-width': fullWidth,
        })
      "
    >
      <ng-content></ng-content>
    </div>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Container {
  clsx = clsx;

  @Input() insetTop!: Props['insetTop'];
  @Input() insetBottom!: Props['insetBottom'];
  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() fullWidth!: Props['fullWidth'];
}
