/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Container.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  children?: any;
  className?: string;
  inset?: boolean;
  gutters?: boolean;
  maxWidth?: (typeof MaxWidth)[keyof typeof MaxWidth];
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import { clamp, Size } from './utilities';
export const MaxWidth = {
  ...Size,
  default: 'default',
  '2xl': '2xl',
  full: 'full',
} as const;
export const styles = tv({
  base: 'gi-container gi-mx-auto',
  variants: {
    inset: {
      true: 'gi-py-4 md:gi-py-6 lg:gi-py-8',
    },
    gutters: {
      false: 'gi-px-0', // gi-container override
    },
    maxWidth: {
      default: '',
      // defaults to gi-container
      sm: 'gi-max-w-screen-sm',
      // 640px
      md: 'gi-max-w-screen-md',
      // 768px
      lg: 'gi-max-w-screen-lg',
      // 1024px
      xl: 'gi-max-w-screen-xl',
      // 1280px
      '2xl': 'gi-max-w-screen-2xl',
      // 1536px
      full: 'gi-max-w-full', // parent 100%
    },
  },
  defaultVariants: {
    inset: false,
    gutters: true,
    maxWidth: 'default',
  },
});

@Component({
  selector: 'gi-container',
  template: `
    <div
      [attr.id]="id"
      [attr.data-testid]="dataTestId"
      [class]="
        styles({
          inset: inset ?? false,
          gutters: gutters ?? true,
          maxWidth: clamp(maxWidth, MaxWidth, MaxWidth.default),
          class: className,
        })
      "
    >
      <ng-content></ng-content>
    </div>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Container {
  MaxWidth = MaxWidth;
  styles = styles;
  clamp = clamp;

  @Input() id!: Props['id'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() inset!: Props['inset'];
  @Input() gutters!: Props['gutters'];
  @Input() maxWidth!: Props['maxWidth'];
  @Input() className!: Props['className'];
}
