/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Container.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  inset?: boolean;
  gutters?: boolean;
  maxWidth?: ValueOf<typeof MaxWidth>;
} & BoxProps;

import { tv } from 'tailwind-variants';
import { MaxWidth } from './constants';
import type { ValueOf } from './constants';
import { clamp } from './utilities';
import type { Props as BoxProps } from './Box';
import GiBox from './Box';
const getMaxWidth = (x: Props['maxWidth']) => clamp(x, MaxWidth, MaxWidth.DEFAULT);
const classes = tv({
  base: 'gi-container gi-mx-auto',
  variants: {
    inset: {
      true: 'gi-py-4 md:gi-py-6 lg:gi-py-8',
    },
    gutters: {
      false: 'gi-px-0',
    },
    maxWidth: {
      default: 'gi-max-w-full 2xl:gi-max-w-screen-2xl',
      sm: 'gi-max-w-screen-sm',
      md: 'gi-max-w-screen-md',
      lg: 'gi-max-w-screen-lg',
      xl: 'gi-max-w-screen-xl',
      '2xl': 'gi-max-w-screen-2xl',
      full: 'gi-max-w-full',
    },
  },
  defaultVariants: {
    inset: false,
    gutters: true,
    maxWidth: MaxWidth.DEFAULT,
  },
});

@Component({
  selector: 'gi-container',
  template: `
    <gi-box
      [id]="id"
      [role]="role"
      [ariaLabel]="ariaLabel"
      [ariaLabelledBy]="ariaLabelledBy"
      [styles]="styles"
      [dataTestId]="dataTestId"
      [className]="
        classes({
          inset: inset ?? false,
          gutters: gutters ?? true,
          maxWidth: getMaxWidth(maxWidth),
          className: className,
        })
      "
      ><ng-content></ng-content
    ></gi-box>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiBox],
})
export default class Container {
  getMaxWidth = getMaxWidth;
  classes = classes;

  @Input() id!: Props['id'];
  @Input() role!: Props['role'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() styles!: Props['styles'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() inset!: Props['inset'];
  @Input() gutters!: Props['gutters'];
  @Input() maxWidth!: Props['maxWidth'];
  @Input() className!: Props['className'];
}
