/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in 'packages/core/atoms/DsButton'
 */

import { Component, Input } from "@angular/core";

import { CommonModule } from "@angular/common";

type Props = {
  variant?: (typeof Variant)[keyof typeof Variant];
  appearance?: (typeof Appearance)[keyof typeof Appearance];
  size?: (typeof Size)[keyof typeof Size];
  children?: any;
  disabled?: boolean;
  className?: string;

  /** Handlers */
  onClick?: (event: any) => void;
  onFocus?: (event: any) => void;
  onBlur?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;

  /** A11y */
  ariaLabel?: string;
  ariaLabelledBy?: string;
  ariaDescribedBy?: string;
  ariaPressed?: boolean | "mixed";
  ariaExpanded?: boolean;
  ariaControls?: string;
  ariaHasPopup?: "menu" | "listbox" | "dialog" | "grid" | "tree" | boolean;
  type?: "button" | "submit" | "reset";
  tabIndex?: number;
  dataTestId?: string;
  dataTestid?: string; // backwards compatibility
};

export const Variant = {
  PRIMARY: "primary",
  SECONDARY: "secondary",
  FLAT: "flat",
} as const;
export const Appearance = {
  DARK: "dark",
  LIGHT: "light",
  DEFAULT: "default",
} as const;
export const Size = {
  REGULAR: "regular",
  SMALL: "small",
  MEDIUM: "medium",
  LARGE: "large",
  EXTRA_LARGE: "extraLarge",
} as const;
const getVariant = (x: Props["variant"] = Variant.PRIMARY) =>
  Object.values(Variant).includes(x) ? x : Variant.PRIMARY;
const getAppearance = (x: Props["appearance"]) =>
  x === Appearance.LIGHT || x === Appearance.DARK ? x : "";
// TODO: compatibility issue to fix: replace regular with medium for consistency
// TODO: compatibility issue to fix: replace regular with medium for consistency
const getSize = (x: Props["size"]) =>
  x === Size.SMALL || x === Size.LARGE || x === Size.EXTRA_LARGE
    ? x
    : Size.REGULAR;
// const getSize = (x: Props['size'] = Size.REGULAR) => Object.values(Size).includes(x) ? x : Size.REGULAR

@Component({
  selector: "ds-button",
  template: `
    <button
      [class]="\`gi-btn \${variantClass} gi-btn-\${getSize(size)} \${className || ''}\`"
      [attr.disabled]="disabled"
      (click)="onClick?.($event)"
      (focus)="onFocus?.($event)"
      (blur)="onBlur?.($event)"
      (keydown)="onKeyDown?.($event)"
      (keyup)="onKeyUp?.($event)"
      [attr.aria-label]="ariaLabel"
      [attr.aria-labelledby]="ariaLabelledBy"
      [attr.aria-describedby]="ariaDescribedBy"
      [attr.aria-pressed]="ariaPressed"
      [attr.aria-expanded]="ariaExpanded"
      [attr.aria-controls]="ariaControls"
      [attr.aria-haspopup]="ariaHasPopup"
      [attr.type]="type || 'button'"
      [attr.tabIndex]="tabIndex"
      [attr.data-testid]="dataTestId || dataTestid"
    >
      <ng-content></ng-content>
    </button>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class DsButton {
  getSize = getSize;

  @Input() variant!: Props["variant"];
  @Input() appearance!: Props["appearance"];
  @Input() disabled!: Props["disabled"];
  @Input() size!: Props["size"];
  @Input() className!: Props["className"];
  @Input() onClick!: Props["onClick"];
  @Input() onFocus!: Props["onFocus"];
  @Input() onBlur!: Props["onBlur"];
  @Input() onKeyDown!: Props["onKeyDown"];
  @Input() onKeyUp!: Props["onKeyUp"];
  @Input() ariaLabel!: Props["ariaLabel"];
  @Input() ariaLabelledBy!: Props["ariaLabelledBy"];
  @Input() ariaDescribedBy!: Props["ariaDescribedBy"];
  @Input() ariaPressed!: Props["ariaPressed"];
  @Input() ariaExpanded!: Props["ariaExpanded"];
  @Input() ariaControls!: Props["ariaControls"];
  @Input() ariaHasPopup!: Props["ariaHasPopup"];
  @Input() type!: Props["type"];
  @Input() tabIndex!: Props["tabIndex"];
  @Input() dataTestId!: Props["dataTestId"];
  @Input() dataTestid!: Props["dataTestid"];

  get variantClass() {
    return [
      "gi-btn",
      getVariant(this.variant),
      getAppearance(this.appearance),
      this.disabled && "disabled",
    ]
      .filter(Boolean)
      .join("-");
  }
}

