/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/DsInsetText.lite.tsx`
 */

import { Component, Input } from "@angular/core";

import { CommonModule } from "@angular/common";

export type Props = {
  id?: string;
  children?: any;
  cite?: string;
  ariaDescribedBy?: string;
  ariaLabelledBy?: string;
  ariaLabel?: string;
};

@Component({
  selector: "ds-inset-text",
  template: `
    <blockquote
      class="gi-p-4 gi-border-l-2xl gi-border-gray-500 gi-text-sm md:gi-text-md gi-not-prose"
      [attr.id]="id"
      [attr.cite]="cite"
      [attr.aria-describedby]="ariaDescribedBy || undefined"
      [attr.aria-labelledby]="ariaLabelledBy || undefined"
      [attr.aria-label]="ariaLabelledBy ? undefined : ariaLabel || undefined"
    >
      <ng-content></ng-content>
    </blockquote>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class DsInsetText {
  @Input() id!: Props["id"];
  @Input() cite!: Props["cite"];
  @Input() ariaDescribedBy!: Props["ariaDescribedBy"];
  @Input() ariaLabelledBy!: Props["ariaLabelledBy"];
  @Input() ariaLabel!: Props["ariaLabel"];
}

