/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/FooterSection.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  variant?: (typeof FooterSectionVariant)[keyof typeof FooterSectionVariant];
  maxWidth?: ContainerProps['maxWidth'];
  children?: any;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import { clamp } from './utilities';
import GiBox from './Box';
import GiContainer from './Container';
import type { Props as ContainerProps } from './Container';
export const FooterSectionVariant = {
  PRIMARY: 'primary',
  UTILITY: 'utility',
} as const;
const getVariant = (x: Props['variant']) => clamp(x, FooterSectionVariant, FooterSectionVariant.PRIMARY);
const classes = tv({
  base: 'gi-footer-section gi-w-full',
  variants: {
    variant: {
      primary: 'gi-bg-color-surface-system-neutral-layer1',
      utility: 'gi-bg-color-surface-system-neutral-layer2',
    },
  },
  defaultVariants: {
    variant: 'primary',
  },
});
const contentClasses = tv({
  base: 'gi-footer-section-container',
  variants: {
    variant: {
      primary: 'gi-py-8 md:gi-py-10',
      utility: 'gi-py-4',
    },
  },
  defaultVariants: {
    variant: 'primary',
  },
});

@Component({
  selector: 'gi-footer-section',
  template: `
    <gi-box
      [id]="id"
      [className]="
        classes({
          variant: getVariant(variant),
        })
      "
      [styles]="styles"
      [dataTestId]="dataTestId"
      ><gi-container
        [maxWidth]="maxWidth"
        [className]="
          contentClasses({
            variant: getVariant(variant),
            className: className,
          })
        "
        ><ng-content></ng-content></gi-container
    ></gi-box>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiBox, GiContainer],
})
export default class FooterSection {
  getVariant = getVariant;
  classes = classes;
  contentClasses = contentClasses;

  @Input() id!: Props['id'];
  @Input() variant!: Props['variant'];
  @Input() styles!: Props['styles'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() maxWidth!: Props['maxWidth'];
  @Input() className!: Props['className'];
}
