/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Footer.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  ariaLabel?: string;
  ariaLabelledBy?: string;
  children?: any;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

@Component({
  selector: 'gi-footer',
  template: `
    <footer
      [attr.id]="id"
      [class]="className"
      [ngStyle]="styles"
      [attr.aria-label]="ariaLabel"
      [attr.aria-labelledby]="ariaLabelledBy"
      [attr.data-testid]="dataTestId"
    >
      <ng-content></ng-content>
    </footer>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Footer {
  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() dataTestId!: Props['dataTestId'];
}
