/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/FooterSection.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  variant?: (typeof FooterSectionVariant)[keyof typeof FooterSectionVariant];
  children?: any;
  className?: string;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import { clamp } from './utilities';
import GiBox from './Box';
export const FooterSectionVariant = {
  PRIMARY: 'primary',
  UTILITY: 'utility',
} as const;
const getVariant = (x: Props['variant']) => clamp(x, FooterSectionVariant, FooterSectionVariant.PRIMARY);
const styles = tv({
  base: '',
  variants: {
    variant: {
      primary: 'gi-py-10 gi-bg-color-surface-system-neutral-layer1',
      utility: 'gi-py-4 gi-px-8 gi-bg-color-surface-system-neutral-layer2',
    },
  },
  defaultVariants: {
    variant: 'primary',
  },
});

@Component({
  selector: 'gi-footer-section',
  template: `
    <gi-box
      [id]="id"
      [className]="
        styles({
          variant: getVariant(variant),
          className: className,
        })
      "
      [dataTestId]="dataTestId"
      ><ng-content></ng-content
    ></gi-box>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiBox],
})
export default class FooterSection {
  getVariant = getVariant;
  styles = styles;

  @Input() id!: Props['id'];
  @Input() variant!: Props['variant'];
  @Input() className!: Props['className'];
  @Input() dataTestId!: Props['dataTestId'];
}
