/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/FooterLogo.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  children: any;
  id?: string;
  className?: string;
  styles?: Record<string, string>;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import GiBox from './Box';
const footerStyles = tv({
  base: 'gi-w-fit md:gi-ml-auto gi-mt-8 md:gi-mt-0',
});

@Component({
  selector: 'gi-footer-logo',
  template: `
    <gi-box
      [id]="id"
      [className]="
        footerStyles({
          class: className,
        })
      "
      [styles]="styles"
      [dataTestId]="dataTestId"
      ><ng-content></ng-content
    ></gi-box>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiBox],
})
export default class FooterLogo {
  footerStyles = footerStyles;

  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() dataTestId!: Props['dataTestId'];
}
