/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Grid.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  container?: boolean;
  columns?: ResponsiveValue<SpacingScale>;
  gap?: ResponsiveValue<SpacingScale>;
  size?: ResponsiveValue<SpacingScale>;
} & BoxProps;

import _ from 'lodash';
import type { ResponsiveValue, BreakpointKey, SpacingScale } from './constants';
import type { Props as BoxProps } from './Box';
import { resolveResponsive } from './utilities';
import GiBox from './Box';
const DEFAULT_COLUMNS: Partial<Record<BreakpointKey, SpacingScale>> = {
  base: 4,
  sm: 6,
  md: 8,
  lg: 12,
};
const getGridClasses = (value: ResponsiveValue<SpacingScale> | undefined, prefix: string): string =>
  resolveResponsive(value, (v, bp) => `${bp}${prefix}-${_.clamp(v as number, 0, 12)}`);

@Component({
  selector: 'gi-grid',
  template: `
    <gi-box
      [id]="id"
      [role]="role"
      [ariaLabel]="ariaLabel"
      [ariaLabelledBy]="ariaLabelledBy"
      [styles]="styles"
      [className]="
        _.compact([
          container &&
            \`gi-grid-container \${getGridClasses(columns ?? DEFAULT_COLUMNS, 'gi-grid-columns')}
                \${getGridClasses(gap, 'gi-grid-gap')}\`,
          (!_.isNil(size) || !container) && \`gi-grid-item \${getGridClasses(size, 'gi-grid-span')}\`,
          className,
        ]).join(' ')
      "
      [dataTestId]="dataTestId"
      ><ng-content></ng-content
    ></gi-box>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiBox],
})
export default class Grid {
  DEFAULT_COLUMNS = DEFAULT_COLUMNS;
  getGridClasses = getGridClasses;
  _ = _;

  @Input() id!: Props['id'];
  @Input() role!: Props['role'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() styles!: Props['styles'];
  @Input() container!: Props['container'];
  @Input() columns!: Props['columns'];
  @Input() gap!: Props['gap'];
  @Input() size!: Props['size'];
  @Input() className!: Props['className'];
  @Input() dataTestId!: Props['dataTestId'];
}
