/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Grid.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  children: any;
  container?: boolean;
  columns?: ResponsiveValue<SpacingScale>;
  gap?: ResponsiveValue<SpacingScale>;
  size?: ResponsiveValue<SpacingScale>;
  role?: 'region' | 'navigation' | 'complementary' | 'search' | 'form';
  ariaLabel?: string;
  ariaLabelledBy?: string;
  className?: string;
  dataTestId?: string;
};

import _ from 'lodash';
import type { ResponsiveValue, BreakpointKey, SpacingScale } from './constants';
const FIGMA_COLUMNS: Partial<Record<BreakpointKey, SpacingScale>> = {
  base: 4,
  sm: 6,
  md: 8,
  lg: 12,
};
const buildGridClasses = (value: ResponsiveValue<SpacingScale> | undefined, prefix: string): string => {
  if (!value) {
    return '';
  }
  const source = _.isNumber(value)
    ? {
        base: Math.max(0, value) as SpacingScale,
      }
    : (value as Partial<Record<BreakpointKey, SpacingScale>>);
  return (_.keys(source) as BreakpointKey[])
    .map((bp) => {
      const clamped = Math.max(0, source[bp] as number);
      return bp === 'base' ? `${prefix}-${clamped}` : `${bp}:${prefix}-${clamped}`;
    })
    .join(' ');
};

@Component({
  selector: 'gi-grid',
  template: `
    <div
      [attr.id]="id"
      [attr.role]="role"
      [attr.aria-label]="role ? ariaLabel : undefined"
      [attr.aria-labelledby]="role ? ariaLabelledBy : undefined"
      [class]="
        container
          ? _.compact([
              'gi-grid-container',
              buildGridClasses(columns ?? FIGMA_COLUMNS, 'gi-grid-columns'),
              buildGridClasses(gap, 'gi-grid-gap'),
              className,
            ]).join(' ')
          : _.compact(['gi-grid-item', buildGridClasses(size, 'gi-grid-span'), className]).join(' ')
      "
      [attr.data-testid]="dataTestId"
    >
      <ng-content></ng-content>
    </div>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Grid {
  FIGMA_COLUMNS = FIGMA_COLUMNS;
  buildGridClasses = buildGridClasses;
  _ = _;

  @Input() id!: Props['id'];
  @Input() role!: Props['role'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() container!: Props['container'];
  @Input() columns!: Props['columns'];
  @Input() gap!: Props['gap'];
  @Input() className!: Props['className'];
  @Input() size!: Props['size'];
  @Input() dataTestId!: Props['dataTestId'];
}
