/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/HeaderNav.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  variant?: (typeof HeaderNavVariant)[keyof typeof HeaderNavVariant];
  ariaLabel: string;
  children?: any;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import { clamp } from './utilities';
export const HeaderNavVariant = {
  PRIMARY: 'primary',
  SECONDARY: 'secondary',
} as const;
const getVariant = (x: Props['variant']) => clamp(x, HeaderNavVariant, HeaderNavVariant.PRIMARY);
const navStyles = tv({
  base: '',
  variants: {
    variant: {
      primary: 'gi-flex gi-items-center gi-flex-none',
      secondary: '',
    },
  },
  defaultVariants: {
    variant: 'primary',
  },
});
const listStyles = tv({
  base: 'gi-list-none gi-flex gi-items-center gi-m-0 gi-p-0',
  variants: {
    variant: {
      primary: 'gi-gap-2 md:gi-gap-4',
      secondary: 'gi-justify-end gi-gap-4',
    },
  },
  defaultVariants: {
    variant: 'primary',
  },
});

@Component({
  selector: 'gi-header-nav',
  template: `
    <nav
      [attr.id]="id"
      [class]="
        navStyles({
          variant: getVariant(variant),
          className: className,
        })
      "
      [ngStyle]="styles"
      [attr.aria-label]="ariaLabel"
      [attr.data-testid]="dataTestId"
    >
      <ul
        [class]="
          listStyles({
            variant: getVariant(variant),
          })
        "
      >
        <ng-content></ng-content>
      </ul>
    </nav>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class HeaderNav {
  getVariant = getVariant;
  navStyles = navStyles;
  listStyles = listStyles;

  @Input() id!: Props['id'];
  @Input() variant!: Props['variant'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() dataTestId!: Props['dataTestId'];
}
