/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Header.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  ariaLabel?: string;
  ariaLabelledBy?: string;
  children?: any;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
const headerStyles = tv({
  base: 'gi-grid gi-relative gi-overflow-x-clip gi-w-full gi-font-primary',
});

@Component({
  selector: 'gi-header',
  template: `
    <header
      [attr.id]="id"
      [class]="
        headerStyles({
          className: className,
        })
      "
      [ngStyle]="styles"
      [attr.aria-label]="ariaLabel"
      [attr.aria-labelledby]="ariaLabelledBy"
      [attr.data-testid]="dataTestId"
    >
      <ng-content></ng-content>
    </header>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Header {
  headerStyles = headerStyles;

  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() dataTestId!: Props['dataTestId'];
}
