/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/HeaderNavItemLink.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = Pick<
  LinkProps,
  | 'href'
  | 'children'
  | 'ariaLabel'
  | 'target'
  | 'rel'
  | 'className'
  | 'styles'
  | 'id'
  | 'dataTestId'
  | 'variant'
  | 'appearance'
  | 'visited'
  | 'underline'
> & {
  showItemMode?: (typeof ShowItemMode)[keyof typeof ShowItemMode];
};

import { tv } from 'tailwind-variants';
import { clamp } from './utilities';
import { ShowItemMode } from './HeaderNavItem';
import GiLink from './Link';
import type { Props as LinkProps } from './Link';
const getShowItemMode = (x: Props['showItemMode']) => clamp(x, ShowItemMode, ShowItemMode.ALWAYS);
const itemStyles = tv({
  base: '',
  variants: {
    showItemMode: {
      always: '',
      'desktop-only': 'gi-hidden lg:gi-flex',
      'mobile-only': 'gi-flex lg:gi-hidden',
    },
  },
  defaultVariants: {
    showItemMode: 'always',
  },
});

@Component({
  selector: 'gi-header-nav-item-link',
  template: `
    <li
      [class]="
        itemStyles({
          showItemMode: getShowItemMode(showItemMode),
        })
      "
    >
      <gi-link
        [href]="href"
        [id]="id"
        [className]="className"
        [styles]="styles"
        [ariaLabel]="ariaLabel"
        [target]="target"
        [rel]="rel"
        [variant]="variant"
        [appearance]="appearance"
        [visited]="visited"
        [underline]="underline"
        [dataTestId]="dataTestId"
        ><ng-content></ng-content
      ></gi-link>
    </li>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiLink],
})
export default class HeaderNavItemLink {
  getShowItemMode = getShowItemMode;
  itemStyles = itemStyles;

  @Input() showItemMode!: Props['showItemMode'];
  @Input() href!: Props['href'];
  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() target!: Props['target'];
  @Input() rel!: Props['rel'];
  @Input() variant!: Props['variant'];
  @Input() appearance!: Props['appearance'];
  @Input() visited!: Props['visited'];
  @Input() underline!: Props['underline'];
  @Input() dataTestId!: Props['dataTestId'];
}
