/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/IconButton.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  variant?: (typeof Variant)[keyof typeof Variant];
  appearance?: (typeof Appearance)[keyof typeof Appearance];
  size?: (typeof IconButtonSize)[keyof typeof IconButtonSize];
  children?: any;
  disabled?: boolean;
  className?: string;
  onClick?: (event: any) => void;
  onFocus?: (event: any) => void;
  onBlur?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  ariaLabel?: string;
  ariaLabelledBy?: string;
  ariaDescribedBy?: string;
  ariaExpanded?: boolean;
  ariaPressed?: boolean | 'mixed';
  ariaHasPopup?: 'menu' | 'listbox' | 'dialog' | 'grid' | 'tree' | boolean;
  ariaControls?: string;
  ariaBusy?: boolean;
  role?: string;
  type?: 'button' | 'submit' | 'reset';
  form?: string;
  tabIndex?: number;
  dataTestId?: string;
  ref?: any;
};

import { tv } from 'tailwind-variants';
import { Variant, Appearance, Size } from './constants';
import { buttonBaseStyles } from './Button';
export const IconButtonSize = {
  SM: Size.SM,
  MD: Size.MD,
  LG: Size.LG,
  XL: Size.XL,
} as const;
export const iconButtonStyles = tv({
  extend: buttonBaseStyles,
  base: ['gi-justify-center'],
  variants: {
    size: {
      sm: 'gi-h-8 gi-w-8',
      md: 'gi-h-10 gi-w-10',
      lg: 'gi-h-12 gi-w-12',
      xl: 'gi-h-14 gi-w-14',
    },
  },
  defaultVariants: {
    size: IconButtonSize.MD,
  },
});
const getVariant = (x: Props['variant'] = Variant.PRIMARY) =>
  Object.values(Variant).includes(x) ? x : Variant.PRIMARY;
const getAppearance = (x: Props['appearance']) =>
  x === Appearance.LIGHT || x === Appearance.DARK ? x : Appearance.DEFAULT;
const getSize = (x: Props['size'] = IconButtonSize.MD) =>
  Object.values(IconButtonSize).includes(x) ? x : IconButtonSize.MD;

@Component({
  selector: 'gi-icon-button',
  template: `
    <button
      [attr.id]="id"
      [class]="
        iconButtonStyles({
          variant: getVariant(variant),
          appearance: getAppearance(appearance),
          size: getSize(size),
          disabled: !!disabled,
          class: className,
        })
      "
      [attr.disabled]="disabled || undefined"
      (click)="onClick && this.onClick.emit($event)"
      (focus)="onFocus && this.onFocus.emit($event)"
      (blur)="onBlur && this.onBlur.emit($event)"
      (keydown)="onKeyDown && this.onKeyDown.emit($event)"
      (keyup)="onKeyUp && this.onKeyUp.emit($event)"
      [attr.aria-label]="ariaLabel"
      [attr.aria-labelledby]="ariaLabelledBy"
      [attr.aria-describedby]="ariaDescribedBy"
      [attr.aria-expanded]="ariaExpanded"
      [attr.aria-pressed]="ariaPressed"
      [attr.aria-haspopup]="ariaHasPopup"
      [attr.aria-controls]="ariaControls"
      [attr.aria-busy]="ariaBusy"
      [attr.role]="role"
      [attr.type]="type ?? 'button'"
      [attr.form]="form"
      [attr.tabIndex]="tabIndex"
      [attr.data-testid]="dataTestId"
    >
      <ng-content></ng-content>
    </button>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class IconButton {
  iconButtonStyles = iconButtonStyles;
  getVariant = getVariant;
  getAppearance = getAppearance;
  getSize = getSize;

  @Input() id!: Props['id'];
  @Input() variant!: Props['variant'];
  @Input() appearance!: Props['appearance'];
  @Input() size!: Props['size'];
  @Input() disabled!: Props['disabled'];
  @Input() className!: Props['className'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() ariaDescribedBy!: Props['ariaDescribedBy'];
  @Input() ariaExpanded!: Props['ariaExpanded'];
  @Input() ariaPressed!: Props['ariaPressed'];
  @Input() ariaHasPopup!: Props['ariaHasPopup'];
  @Input() ariaControls!: Props['ariaControls'];
  @Input() ariaBusy!: Props['ariaBusy'];
  @Input() role!: Props['role'];
  @Input() type!: Props['type'];
  @Input() form!: Props['form'];
  @Input() tabIndex!: Props['tabIndex'];
  @Input() dataTestId!: Props['dataTestId'];
  @Output() onClick = new EventEmitter<any>();
  @Output() onFocus = new EventEmitter<any>();
  @Output() onBlur = new EventEmitter<any>();
  @Output() onKeyDown = new EventEmitter<any>();
  @Output() onKeyUp = new EventEmitter<any>();
}
