/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/InsetText.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  children: any;
  cite?: string;
  describedBy?: string;
  labelledBy?: string;
};

@Component({
  selector: 'inset-text',
  template: `
    <blockquote
      class="gi-font-primary gi-p-4 gi-border-l-2xl gi-border-gray-500 gi-text-sm md:gi-text-md gi-not-prose"
      [attr.id]="id"
      [attr.cite]="cite"
      [attr.aria-describedby]="describedBy || undefined"
      [attr.aria-labelledby]="labelledBy || undefined"
    >
      <ng-content></ng-content>
    </blockquote>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class InsetText {
  @Input() id!: Props['id'];
  @Input() cite!: Props['cite'];
  @Input() describedBy!: Props['describedBy'];
  @Input() labelledBy!: Props['labelledBy'];
}
