/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/LinkButton.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = Omit<LinkProps, 'variant' | 'appearance' | 'underline' | 'visited'> &
  Pick<ButtonProps, 'variant' | 'appearance' | 'size'>;

import { tv } from 'tailwind-variants';
import { buttonBaseStyles, ButtonSize, buttonSizeVariants, getSize, getVariant, getAppearance } from './Button';
import type { Props as ButtonProps } from './Button';
import type { Props as LinkProps } from './Link';
export const linkButtonStyles = tv({
  extend: buttonBaseStyles,
  base: ['gi-gap-2', 'gi-no-underline', 'hover:gi-no-underline'],
  variants: {
    size: buttonSizeVariants,
  },
  defaultVariants: {
    size: ButtonSize.MD,
  },
});

@Component({
  selector: 'gi-link-button',
  template: `
    <a
      [attr.id]="id"
      [attr.href]="href"
      [class]="
        linkButtonStyles({
          variant: getVariant(variant),
          appearance: getAppearance(appearance),
          size: getSize(size),
          class: className,
        })
      "
      [ngStyle]="styles"
      [attr.target]="target ?? (external ? '_blank' : undefined)"
      [attr.rel]="rel ?? (external ? 'noreferrer noopener' : undefined)"
      [attr.download]="download"
      [attr.aria-current]="ariaCurrent"
      [attr.aria-label]="ariaLabel"
      [attr.aria-labelledby]="ariaLabelledBy"
      [attr.aria-describedby]="ariaDescribedBy"
      [attr.aria-hidden]="ariaHidden"
      [attr.tabIndex]="ariaHidden ? -1 : tabIndex"
      [attr.lang]="lang"
      (click)="onClick && this.onClick.emit($event)"
      (focus)="onFocus && this.onFocus.emit($event)"
      (blur)="onBlur && this.onBlur.emit($event)"
      (keydown)="onKeyDown && this.onKeyDown.emit($event)"
      (keyup)="onKeyUp && this.onKeyUp.emit($event)"
      [attr.data-testid]="dataTestId"
      ><ng-content></ng-content
    ></a>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class LinkButton {
  linkButtonStyles = linkButtonStyles;
  getSize = getSize;
  getVariant = getVariant;
  getAppearance = getAppearance;

  @Input() id!: Props['id'];
  @Input() href!: Props['href'];
  @Input() variant!: Props['variant'];
  @Input() appearance!: Props['appearance'];
  @Input() size!: Props['size'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() target!: Props['target'];
  @Input() external!: Props['external'];
  @Input() rel!: Props['rel'];
  @Input() download!: Props['download'];
  @Input() ariaCurrent!: Props['ariaCurrent'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() ariaDescribedBy!: Props['ariaDescribedBy'];
  @Input() ariaHidden!: Props['ariaHidden'];
  @Input() tabIndex!: Props['tabIndex'];
  @Input() lang!: Props['lang'];
  @Input() dataTestId!: Props['dataTestId'];
  @Output() onClick = new EventEmitter<any>();
  @Output() onFocus = new EventEmitter<any>();
  @Output() onBlur = new EventEmitter<any>();
  @Output() onKeyDown = new EventEmitter<any>();
  @Output() onKeyUp = new EventEmitter<any>();
}
