/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Paragraph.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  size?: (typeof Size)[keyof typeof Size];
  align?: (typeof Align)[keyof typeof Align];
  whitespace?: (typeof Whitespace)[keyof typeof Whitespace];
  children?: any;
  className?: string;
  styles?: Record<string, string>;
  dataTestId?: string;
  ariaHidden?: boolean;
};

import { tv } from 'tailwind-variants';
import { Size, Whitespace } from './utilities';
export const Align = {
  START: 'start',
  CENTER: 'center',
  END: 'end',
  JUSTIFY: 'justify',
} as const;
export const paragraphStyles = tv({
  base: ['gi-font-primary', 'gi-max-w-prose'],
  variants: {
    size: {
      sm: 'gi-text-sm',
      md: 'gi-text-md',
      lg: 'gi-text-lg',
      xl: 'gi-text-lg xs:gi-text-xl',
    },
    align: {
      start: 'gi-text-start',
      center: 'gi-text-center',
      end: 'gi-text-end',
      justify: 'gi-text-justify',
    },
    whitespace: {
      normal: 'gi-whitespace-normal',
      pre: 'gi-whitespace-pre',
      'pre-wrap': 'gi-whitespace-pre-wrap',
      'break-spaces': 'gi-whitespace-break-spaces',
    },
  },
  defaultVariants: {
    size: 'md',
    align: 'start',
    whitespace: 'normal',
  },
});
const getSize = (x: Props['size'] = Size.MD) => (Object.values(Size).includes(x) ? x : Size.MD);
const getAlign = (x: Props['align'] = Align.START) => (Object.values(Align).includes(x) ? x : Align.START);
const getWhitespace = (x: Props['whitespace'] = Whitespace.NORMAL) =>
  Object.values(Whitespace).includes(x) ? x : Whitespace.NORMAL;

@Component({
  selector: 'gi-paragraph',
  template: `
    <p
      [attr.id]="id"
      [class]="
        paragraphStyles({
          size: getSize(size),
          align: getAlign(align),
          whitespace: getWhitespace(whitespace),
          class: className,
        })
      "
      [ngStyle]="styles"
      [attr.data-testid]="dataTestId"
      [attr.aria-hidden]="ariaHidden"
    >
      <ng-content></ng-content>
    </p>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Paragraph {
  paragraphStyles = paragraphStyles;
  getSize = getSize;
  getAlign = getAlign;
  getWhitespace = getWhitespace;

  @Input() id!: Props['id'];
  @Input() size!: Props['size'];
  @Input() align!: Props['align'];
  @Input() whitespace!: Props['whitespace'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() ariaHidden!: Props['ariaHidden'];
}
