/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Stack.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  direction?: ResponsiveValue<ValueOf<typeof Direction>>;
  gap?: ResponsiveValue<SpacingScale>;
  align?: ValueOf<typeof AlignItems>;
  justify?: ValueOf<typeof Justify>;
  wrap?: boolean;
} & BoxProps;

import type { AlignItems, Direction, Justify, ResponsiveValue, SpacingScale, ValueOf } from './constants';
import type { Props as BoxProps } from './Box';
import { getAlignItems, getJustify } from './utilities';
import classes, { getDirectionClasses, getGapClasses } from './Stack.styles';
import CoreBox from './Box';

@Component({
  selector: 'core-stack',
  template: `
    <core-box
      [id]="id"
      [role]="role"
      [ariaLabel]="ariaLabel"
      [ariaLabelledBy]="ariaLabelledBy"
      [styles]="styles"
      [className]="
        classes({
          align: getAlignItems(align),
          justify: getJustify(justify),
          wrap: !!wrap,
          className: [getDirectionClasses(direction), getGapClasses(gap), className],
        })
      "
      [dataTestId]="dataTestId"
      ><ng-content></ng-content
    ></core-box>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, CoreBox],
})
export default class Stack {
  getAlignItems = getAlignItems;
  getJustify = getJustify;
  classes = classes;
  getDirectionClasses = getDirectionClasses;
  getGapClasses = getGapClasses;

  @Input() id!: Props['id'];
  @Input() role!: Props['role'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() styles!: Props['styles'];
  @Input() align!: Props['align'];
  @Input() justify!: Props['justify'];
  @Input() wrap!: Props['wrap'];
  @Input() direction!: Props['direction'];
  @Input() gap!: Props['gap'];
  @Input() className!: Props['className'];
  @Input() dataTestId!: Props['dataTestId'];
}
