/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Stack.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  direction?: ResponsiveValue<(typeof Direction)[keyof typeof Direction]>;
  gap?: ResponsiveValue<number>;
  align?: (typeof AlignItems)[keyof typeof AlignItems];
  justify?: (typeof Justify)[keyof typeof Justify];
  wrap?: boolean;
  role?: 'region' | 'navigation' | 'complementary' | 'search' | 'form' | 'group';
  ariaLabel?: string;
  ariaLabelledBy?: string;
  className?: string;
  id?: string;
  styles?: Record<string, string>;
  children?: any;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import { Direction, AlignItems, Justify, ResponsiveValue, BreakpointKey } from './constants';
import { getAlignItems, getJustify, resolveResponsive } from './utilities';
const directionToClass = (direction: string, bp?: BreakpointKey): string => {
  const cls = direction === 'row' ? 'gi-flex-row' : 'gi-flex-col';
  return bp ? `${bp}:${cls}` : cls;
};
const gapToClass = (gap: number, bp?: BreakpointKey): string => (bp ? `${bp}:gi-gap-${gap}` : `gi-gap-${gap}`);
const stackVariants = tv({
  base: ['gi-flex', 'gi-w-full'],
  variants: {
    align: {
      start: 'gi-items-start',
      center: 'gi-items-center',
      end: 'gi-items-end',
      stretch: 'gi-items-stretch',
      baseline: 'gi-items-baseline',
    },
    justify: {
      start: 'gi-justify-start',
      center: 'gi-justify-center',
      end: 'gi-justify-end',
      between: 'gi-justify-between',
      around: 'gi-justify-around',
      evenly: 'gi-justify-evenly',
    },
    wrap: {
      true: 'gi-flex-wrap',
      false: 'gi-flex-nowrap',
    },
  },
  defaultVariants: {
    align: 'start',
    justify: 'start',
    wrap: false,
  },
});

@Component({
  selector: 'gi-stack',
  template: `
    <div
      [attr.id]="id"
      [attr.role]="role"
      [attr.aria-label]="role ? ariaLabel : undefined"
      [attr.aria-labelledby]="role ? ariaLabelledBy : undefined"
      [ngStyle]="styles"
      [class]="
        stackVariants({
          align: getAlignItems(align),
          justify: getJustify(justify),
          wrap: wrap ?? false,
          class: [
            resolveResponsive(direction ?? Direction.COLUMN, directionToClass),
            resolveResponsive(gap ?? 0, gapToClass),
            className,
          ],
        })
      "
      [attr.data-testid]="dataTestId"
    >
      <ng-content></ng-content>
    </div>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Stack {
  directionToClass = directionToClass;
  gapToClass = gapToClass;
  stackVariants = stackVariants;
  getAlignItems = getAlignItems;
  getJustify = getJustify;
  resolveResponsive = resolveResponsive;

  @Input() id!: Props['id'];
  @Input() role!: Props['role'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() styles!: Props['styles'];
  @Input() align!: Props['align'];
  @Input() justify!: Props['justify'];
  @Input() wrap!: Props['wrap'];
  @Input() direction!: Props['direction'];
  @Input() gap!: Props['gap'];
  @Input() className!: Props['className'];
  @Input() dataTestId!: Props['dataTestId'];
}
