/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Text.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  children: any;
  size?: (typeof Size)[keyof typeof Size];
  whitespace?: (typeof Whitespace)[keyof typeof Whitespace];
  className?: string;
  id?: string;
  dataTestId?: string;
  styles?: Record<string, string>;
  ariaHidden?: boolean;
};

import { tv } from 'tailwind-variants';
import { getSize, getWhitespace, Size, Whitespace } from './utilities';
export const textVariants = tv({
  base: 'gi-font-primary gi-not-prose',
  variants: {
    size: {
      sm: 'gi-text-sm',
      md: 'gi-text-md',
      lg: 'gi-text-lg',
      xl: 'gi-text-lg xs:gi-text-xl',
    },
    whitespace: {
      normal: 'gi-whitespace-normal',
      pre: 'gi-whitespace-pre',
      'pre-wrap': 'gi-whitespace-pre-wrap',
      'break-spaces': 'gi-whitespace-break-spaces',
    },
  },
  defaultVariants: {
    size: 'md',
    whitespace: 'normal',
  },
});

@Component({
  selector: 'gi-text',
  template: `
    <span
      [attr.id]="id"
      [ngStyle]="styles"
      [attr.data-testid]="dataTestId"
      [attr.aria-hidden]="ariaHidden"
      [class]="
        textVariants({
          size: getSize(size),
          whitespace: getWhitespace(whitespace),
          class: className,
        })
      "
      ><ng-content></ng-content
    ></span>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Text {
  textVariants = textVariants;
  getSize = getSize;
  getWhitespace = getWhitespace;

  @Input() id!: Props['id'];
  @Input() styles!: Props['styles'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() ariaHidden!: Props['ariaHidden'];
  @Input() size!: Props['size'];
  @Input() whitespace!: Props['whitespace'];
  @Input() className!: Props['className'];
}
