/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Text.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  size?: ValueOf<typeof Size>;
  whitespace?: ValueOf<typeof Whitespace>;
  className?: string;
  id?: string;
  dataTestId?: string;
  styles?: Record<string, string>;
  ariaHidden?: boolean;
};
const defaultProps: any = { ariaHidden: undefined };

import type { Size, ValueOf, Whitespace } from './constants';
import { getSize, getWhitespace } from './utilities';
import classes from './Text.styles';

@Component({
  selector: 'gi-text',
  template: `
    <span
      [class]="
        classes({
          size: getSize(size),
          whitespace: getWhitespace(whitespace),
          className: className,
        })
      "
      [attr.id]="id"
      [ngStyle]="styles"
      [attr.data-testid]="dataTestId"
      [attr.aria-hidden]="ariaHidden"
      ><ng-content></ng-content
    ></span>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Text {
  getSize = getSize;
  getWhitespace = getWhitespace;
  classes = classes;

  @Input() size!: Props['size'];
  @Input() whitespace!: Props['whitespace'];
  @Input() className!: Props['className'];
  @Input() id!: Props['id'];
  @Input() styles!: Props['styles'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() ariaHidden: Props['ariaHidden'] = defaultProps['ariaHidden'];
}
