/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Text.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  children: any;
  size?: (typeof Size)[keyof typeof Size];
  whitespace?: (typeof Whitespace)[keyof typeof Whitespace];
  align?: (typeof Align)[keyof typeof Align];
  className?: string;
  id?: string;
  dataTestId?: string;
  styles?: Record<string, string>;
  ariaHidden?: boolean;
};

import { tv } from 'tailwind-variants';
import { Align, Size, Whitespace } from './utilities';
const textVariants = tv({
  base: 'gi-font-primary gi-not-prose',
  variants: {
    size: {
      sm: 'gi-text-sm',
      md: 'gi-text-md',
      lg: 'gi-text-lg',
      xl: 'gi-text-lg xs:gi-text-xl',
    },
    whitespace: {
      normal: 'gi-whitespace-normal',
      pre: 'gi-whitespace-pre',
      'pre-wrap': 'gi-whitespace-pre-wrap',
      'break-spaces': 'gi-whitespace-break-spaces',
    },
    align: {
      start: 'gi-text-start',
      center: 'gi-text-center',
      end: 'gi-text-end',
      justify: 'gi-text-justify',
    },
  },
  defaultVariants: {
    size: 'md',
    whitespace: 'normal',
    align: 'start',
  },
});
const getSize = (x: Props['size'] = Size.MD) => (Object.values(Size).includes(x) ? x : Size.MD);
const getWhitespace = (x: Props['whitespace'] = Whitespace.NORMAL) =>
  Object.values(Whitespace).includes(x) ? x : Whitespace.NORMAL;
const getAlign = (x: Props['align'] = Align.START) => (Object.values(Align).includes(x) ? x : Align.START);

@Component({
  selector: 'gi-text',
  template: `
    <span
      [attr.id]="id"
      [ngStyle]="styles"
      [attr.data-testid]="dataTestId"
      [attr.aria-hidden]="ariaHidden"
      [class]="
        textVariants({
          size: getSize(size),
          whitespace: getWhitespace(whitespace),
          align: getAlign(align),
          class: className,
        })
      "
      ><ng-content></ng-content
    ></span>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Text {
  textVariants = textVariants;
  getSize = getSize;
  getWhitespace = getWhitespace;
  getAlign = getAlign;

  @Input() id!: Props['id'];
  @Input() styles!: Props['styles'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() ariaHidden!: Props['ariaHidden'];
  @Input() size!: Props['size'];
  @Input() whitespace!: Props['whitespace'];
  @Input() align!: Props['align'];
  @Input() className!: Props['className'];
}
