<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavHeading.lite.tsx`
-->

<template>
  <li class="gi-list-none">
    <H5
      :id="id"
      :dataTestId="dataTestId"
      :className="
        classes({
          secondary: !!secondary,
          class: className,
        })
      "
      ><slot
    /></H5>
  </li>
</template>

<script setup lang="ts">
import { tv } from 'tailwind-variants';
import H5 from '../heading/H5.vue';
const classes = tv({
  base: [
    'gi-border-l-sm',
    'gi-text-md',
    'gi-font-bold',
    'gi-mt-2',
    'gi-text-color-text-system-neutral-muted',
    'gi-py-2',
    'gi-border-transparent',
  ],
  variants: {
    secondary: {
      true: 'gi-px-6',
      false: 'gi-px-3',
    },
  },
  defaultVariants: {
    secondary: false,
  },
});

export type Props = {
  secondary?: boolean;
  className?: string;
  id?: string;
  dataTestId?: string;
};

const props = defineProps<Props>();
</script>
