<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavItemLink.lite.tsx`
-->

<template>
  <GiSideNavRow :ariaHidden="ariaHidden"
    ><a
      :id="id"
      :href="href"
      :target="target ?? (external ? '_blank' : undefined)"
      :rel="rel ?? (external ? 'noreferrer noopener' : undefined)"
      :download="download"
      @click="async (event) => onClick && onClick(event)"
      :class="
        classes({
          disabled: disabled,
          hasAction: !!actions,
          className: ['gi-side-nav-item-link', className],
        })
      "
      :style="styles"
      :data-testid="dataTestId"
      :aria-current="ariaCurrent"
      :aria-label="ariaLabel"
      :aria-labelledby="ariaLabelledBy"
      :aria-describedby="ariaDescribedBy"
      :tabIndex="ariaHidden ? -1 : tabIndex"
      :lang="lang"
      @keydown="async (event) => onKeyDown && onKeyDown(event)"
      @keyup="async (event) => onKeyUp && onKeyUp(event)"
      ><slot
    /></a>
    <template v-if="!!actions">
      <GiBox
        :className="
          actionClasses({
            expandable: true,
          })
        "
        ><slot name="actions">{{ actions }}</slot></GiBox
      >
    </template>
  </GiSideNavRow>
</template>

<script setup lang="ts">
import classes, { actionClasses } from './SideNavItem.styles';
import GiSideNavRow from './SideNavRow.vue';
import GiBox from '../Box.vue';

export type Props = {
  id?: string;
  href: string;
  actions?: any;
  disabled?: boolean;
  className?: string;
  external?: boolean;
  target?: '_self' | '_blank' | '_parent' | '_top';
  rel?: string;
  download?: string | boolean;
  ariaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false' | boolean;
  ariaLabel?: string;
  ariaHidden?: boolean | 'true' | 'false';
  ariaLabelledBy?: string;
  ariaDescribedBy?: string;
  tabIndex?: number;
  lang?: string;
  styles?: Record<string, string>;
  onClick?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  dataTestId?: string;
};

const props = withDefaults(defineProps<Props>(), {
  ariaHidden: false,
  id: undefined,
  href: undefined,
  target: undefined,
  external: false,
  rel: undefined,
  download: undefined,
  onClick: undefined,
  disabled: false,
  actions: undefined,
  className: undefined,
  styles: undefined,
  dataTestId: undefined,
  ariaCurrent: undefined,
  ariaLabel: undefined,
  ariaLabelledBy: undefined,
  ariaDescribedBy: undefined,
  tabIndex: undefined,
  lang: undefined,
  onKeyDown: undefined,
  onKeyUp: undefined,
  children: undefined,
});
</script>
