<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavItem.lite.tsx`
-->

<template>
  <li class="gi-list-none gi-mt-1 gi-relative gi-side-nav-list" :aria-hidden="ariaHidden">
    <button
      type="button"
      :id="id"
      :class="
        classes({
          selected: !!selected,
          disabled: !!disabled,
          className: className,
        })
      "
      :disabled="disabled || undefined"
      :style="styles"
      @click="async (event) => onClick && onClick(event)"
      :aria-current="ariaCurrent"
      :aria-label="ariaLabel"
      :aria-controls="ariaControls"
      :tabIndex="ariaHidden ? -1 : tabIndex"
      :data-testid="dataTestId"
    >
      <slot />
    </button>
  </li>
</template>

<script setup lang="ts">
import classes from './SideNavItem.styles';

export type Props = {
  id?: string;
  selected?: boolean;
  disabled?: boolean;
  className?: string;
  styles?: Record<string, string>;
  onClick?: (event: any) => void;
  ariaHidden?: boolean | 'true' | 'false';
  ariaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false' | boolean;
  ariaLabel?: string;
  ariaControls?: string;
  tabIndex?: number;
  dataTestId?: string;
};

const props = withDefaults(defineProps<Props>(), {
  ariaHidden: undefined,
  id: undefined,
  selected: false,
  disabled: undefined,
  className: undefined,
  styles: undefined,
  onClick: undefined,
  ariaCurrent: undefined,
  ariaLabel: undefined,
  ariaControls: undefined,
  tabIndex: undefined,
  dataTestId: undefined,
  children: undefined,
});
</script>
