/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/header/HeaderTitle.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  children: any;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import GiBox from '../Box';
const classes = tv({
  base: [
    'gi-min-w-0 gi-grow',
    'gi-text-lg xl:gi-text-xl gi-font-bold gi-font-primary',
    'gi-truncate',
    'gi-ml-4 md:gi-ml-6 lg:gi-ml-12',
  ],
});

@Component({
  selector: 'gi-header-title',
  template: `
    <gi-box
      [id]="id"
      [className]="
        classes({
          className: className,
        })
      "
      [styles]="styles"
      [dataTestId]="dataTestId"
      ><ng-content></ng-content
    ></gi-box>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiBox],
})
export default class HeaderTitle {
  classes = classes;

  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() dataTestId!: Props['dataTestId'];
}
