/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/header/HeaderNavItemSeparator.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  /** Visibility: `true`/`false`, a breakpoint to show from (e.g. `"lg"`), or a per-breakpoint map like `{ base: false, lg: true }`. */
  visible?: VisibleValue;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import GiDivider from '../Divider';
import { getVisibility } from './HeaderNavItem.styles';
import type { VisibleValue } from './HeaderNavItem.styles';
const classes = tv({
  base: 'gi-mx-2 gi-h-8 gi-items-stretch',
});
const dividerClasses = tv({
  base: 'gi-header-nav-item-separator !gi-border-[currentColor]' /* `!important` needed for styles to resolve correctly given Tailwind's class-merge limitations. */,
});

@Component({
  selector: 'gi-header-nav-item-separator',
  template: `
    <li
      role="none"
      [class]="
        classes({
          className: getVisibility(visible),
        })
      "
    >
      <gi-divider
        orientation="vertical"
        [id]="id"
        [dataTestId]="dataTestId"
        [styles]="styles"
        [className]="
          dividerClasses({
            className: className,
          })
        "
      ></gi-divider>
    </li>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule, GiDivider],
})
export default class HeaderNavItemSeparator {
  classes = classes;
  dividerClasses = dividerClasses;
  getVisibility = getVisibility;

  @Input() visible!: Props['visible'];
  @Input() id!: Props['id'];
  @Input() dataTestId!: Props['dataTestId'];
  @Input() styles!: Props['styles'];
  @Input() className!: Props['className'];
}
