<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/icons/ChatBubble.lite.tsx`
-->

<template>
  <svg
    viewBox="0 -960 960 960"
    xmlns="http://www.w3.org/2000/svg"
    :width="size ?? 24"
    :height="size ?? 24"
    :class="className"
    :id="id"
    :role="label ? 'img' : undefined"
    :aria-label="label"
    :aria-hidden="!label"
    :fill="color ?? 'currentColor'"
    :data-testid="dataTestId ?? 'chat-bubble'"
  >
    <path
      d="M80-80v-720q0-33 23.5-56.5T160-880h640q33 0 56.5 23.5T880-800v480q0 33-23.5 56.5T800-240H240L80-80Zm126-240h594v-480H160v525l46-45Zm-46 0v-480 480Z"
    ></path>
  </svg>
</template>

<script setup lang="ts">
import type { IconProps } from './types';

const props = defineProps<IconProps>();
</script>
