<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/icons/ContentCopy.lite.tsx`
-->

<template>
  <svg
    viewBox="0 -960 960 960"
    xmlns="http://www.w3.org/2000/svg"
    :width="size ?? 24"
    :height="size ?? 24"
    :class="className"
    :id="id"
    :role="label ? 'img' : undefined"
    :aria-label="label"
    :aria-hidden="!label"
    :fill="color ?? 'currentColor'"
    :data-testid="dataTestId ?? 'content-copy'"
  >
    <path
      d="M360-240q-33 0-56.5-23.5T280-320v-480q0-33 23.5-56.5T360-880h360q33 0 56.5 23.5T800-800v480q0 33-23.5 56.5T720-240H360Zm0-80h360v-480H360v480ZM200-80q-33 0-56.5-23.5T120-160v-560h80v560h440v80H200Zm160-240v-480 480Z"
    ></path>
  </svg>
</template>

<script setup lang="ts">
import type { IconProps } from './types';

const props = defineProps<IconProps>();
</script>
