<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/icons/Event.lite.tsx`
-->

<template>
  <svg
    viewBox="0 -960 960 960"
    xmlns="http://www.w3.org/2000/svg"
    :width="size ?? 24"
    :height="size ?? 24"
    :class="className"
    :id="id"
    :role="label ? 'img' : undefined"
    :aria-label="label"
    :aria-hidden="!label"
    :fill="color ?? 'currentColor'"
    :data-testid="dataTestId ?? 'event'"
  >
    <path
      d="M509-269q-29-29-29-71t29-71q29-29 71-29t71 29q29 29 29 71t-29 71q-29 29-71 29t-71-29ZM200-80q-33 0-56.5-23.5T120-160v-560q0-33 23.5-56.5T200-800h40v-80h80v80h320v-80h80v80h40q33 0 56.5 23.5T840-720v560q0 33-23.5 56.5T760-80H200Zm0-80h560v-400H200v400Zm0-480h560v-80H200v80Zm0 0v-80 80Z"
    ></path>
  </svg>
</template>

<script setup lang="ts">
import type { IconProps } from './types';

const props = defineProps<IconProps>();
</script>
