<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/icons/Refresh.lite.tsx`
-->

<template>
  <svg
    viewBox="0 -960 960 960"
    xmlns="http://www.w3.org/2000/svg"
    :width="size ?? 24"
    :height="size ?? 24"
    :class="className"
    :id="id"
    :role="label ? 'img' : undefined"
    :aria-label="label"
    :aria-hidden="!label"
    :fill="color ?? 'currentColor'"
    :data-testid="dataTestId ?? 'refresh'"
  >
    <path
      d="M480-160q-134 0-227-93t-93-227q0-134 93-227t227-93q69 0 132 28.5T720-690v-110h80v280H520v-80h168q-32-56-87.5-88T480-720q-100 0-170 70t-70 170q0 100 70 170t170 70q77 0 139-44t87-116h84q-28 106-114 173t-196 67Z"
    ></path>
  </svg>
</template>

<script setup lang="ts">
import type { IconProps } from './types';

const props = defineProps<IconProps>();
</script>
