<!--
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/icons/SwapVertical.lite.tsx`
-->

<template>
  <svg
    viewBox="0 -960 960 960"
    xmlns="http://www.w3.org/2000/svg"
    :width="size ?? 24"
    :height="size ?? 24"
    :class="className"
    :id="id"
    :role="label ? 'img' : undefined"
    :aria-label="label"
    :aria-hidden="!label"
    :fill="color ?? 'currentColor'"
    :data-testid="dataTestId ?? 'swap-vertical'"
  >
    <path
      d="M320-440v-287L217-624l-57-56 200-200 200 200-57 56-103-103v287h-80ZM600-80 400-280l57-56 103 103v-287h80v287l103-103 57 56L600-80Z"
    ></path>
  </svg>
</template>

<script setup lang="ts">
import type { IconProps } from './types';

const props = defineProps<IconProps>();
</script>
