/**
 * THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
 * Generated by: pnpm generate
 * Source: packages/design/svgs/scripts/generate.ts
 */

import { forwardRef } from 'react';
import type { SVGProps } from 'react';

export interface ChevronRightProps extends SVGProps<SVGSVGElement> {
  size?: string | number;
  title?: string;
}

export const ChevronRight = forwardRef<SVGSVGElement, ChevronRightProps>(
  ({ size = 24, title, ...props }, ref) => (
    <svg
      ref={ref}
      width={size}
      height={size}
      viewBox="0 -960 960 960"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      role={title ? 'img' : 'presentation'}
      aria-label={title}
      {...props}
    >
      {title && <title>{title}</title>}
      <path d="M530-481 332-679l43-43 241 241-241 241-43-43 198-198Z"/>
    </svg>
  ),
);

ChevronRight.displayName = 'ChevronRight';
export default ChevronRight;
