/**
 * THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
 * Generated by: pnpm generate
 * Source: packages/design/svgs/scripts/generate.ts
 */

export * from './icons/index.js';
export * from './logos/index.js';
export * from './favicons/index.js';
