/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavGroup.lite.tsx`
 */

'use client';
import * as React from 'react';

export type Props = {
  id?: string;
  children: any;
  open?: boolean;
  selected?: boolean;
  label?: any;
  disabled?: boolean;
  className?: string;
  styles?: Record<string, string>;
  onClick?: (event: any) => void;
  onFocus?: (event: any) => void;
  onBlur?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  ariaHidden?: boolean;
  ariaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false' | boolean;
  ariaLabel?: string;
  tabIndex?: number;
  dataTestId?: string;
};

import classes, { arrowClasses } from './SideNavItem.styles';
import GiKeyboardArrowDownIcon from '../icons/KeyboardArrowDown';
import { tv } from 'tailwind-variants';
const contentClasses = tv({
  base: 'gi-side-nav-group',
  variants: {
    open: {
      true: 'gi-block',
      false: 'gi-hidden',
    },
  },
  defaultVariants: {
    open: false,
  },
});

function SideNavGroup(props: Props) {
  props = { ariaHidden: undefined, ariaCurrent: undefined, ...props };
  return (
    <li className="gi-list-none gi-mt-1 gi-relative gi-side-nav-list" aria-hidden={props.ariaHidden}>
      <div className="gi-relative">
        <button
          type="button"
          id={props.id}
          className={classes({
            selected: !!props.selected,
            disabled: !!props.disabled,
            expandable: true,
            className: props.className,
          })}
          style={props.styles}
          disabled={props.disabled || undefined}
          onClick={(event) => props.onClick && props.onClick(event)}
          onFocus={(event) => props.onFocus && props.onFocus(event)}
          onBlur={(event) => props.onBlur && props.onBlur(event)}
          onKeyDown={(event) => props.onKeyDown && props.onKeyDown(event)}
          onKeyUp={(event) => props.onKeyUp && props.onKeyUp(event)}
          aria-current={props.ariaCurrent}
          aria-label={props.ariaLabel}
          tabIndex={props.ariaHidden ? -1 : props.tabIndex}
          data-testid={props.dataTestId}
        >
          <>{props.label}</>
        </button>
        <GiKeyboardArrowDownIcon
          className={arrowClasses({
            open: !!props.open,
          })}
        />
      </div>
      <ul
        aria-expanded={!!props.open}
        className={contentClasses({
          open: !!props.open,
        })}
      >
        {props.children}
      </ul>
    </li>
  );
}

export default SideNavGroup;
