/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavItem.lite.tsx`
 */

'use client';
import * as React from 'react';

export type Props = {
  id?: string;
  children?: any;
  actions?: any;
  value?: string;
  disabled?: boolean;
  className?: string;
  styles?: Record<string, string>;
  onClick?: (event: any) => void;
  ariaHidden?: boolean | 'true' | 'false';
  ariaCurrent?: 'page' | 'step' | 'location' | 'date' | 'time' | 'true' | 'false' | boolean;
  ariaLabel?: string;
  ariaControls?: string;
  tabIndex?: number;
  dataTestId?: string;
};

import classes, { actionClasses } from './SideNavItem.styles';
import GiSideNavRow from './SideNavRow';
import GiBox from '../Box';

function SideNavItem(props: Props) {
  props = { disabled: false, ariaHidden: false, ...props };
  return (
    <GiSideNavRow ariaHidden={props.ariaHidden}>
      <button
        id={props.id}
        className={classes({
          disabled: props.disabled,
          hasAction: !!props.actions,
          className: ['gi-side-nav-item_', props.className],
        })}
        style={props.styles}
        value={props.value}
        onClick={(event) => props.onClick && props.onClick(event)}
        data-testid={props.dataTestId}
        aria-current={props.ariaCurrent}
        aria-label={props.ariaLabel}
        aria-controls={props.ariaControls}
        tabIndex={props.ariaHidden ? -1 : props.tabIndex}
      >
        {props.children}
      </button>
      {!!props.actions ? (
        <GiBox
          className={actionClasses({
            expandable: true,
          })}
        >
          <>{props.actions || '{props.actions}'}</>
        </GiBox>
      ) : null}
    </GiSideNavRow>
  );
}

export default SideNavItem;
