/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavRow.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  children?: any;
  ariaHidden?: boolean | 'true' | 'false';
};

function SideNavRow(props: Props) {
  return (
    <li className="gi-list-none gi-mt-1 gi-relative" aria-hidden={props.ariaHidden}>
      {props.children}
    </li>
  );
}

export default SideNavRow;
