/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNavHeading.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  children?: any;
  className?: string;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
const classes = tv({
  base: [
    'gi-border-l-sm',
    'gi-text-md',
    'gi-font-bold',
    'gi-mt-2',
    'gi-text-color-text-system-neutral-muted',
    'gi-py-2',
    'gi-border-transparent',
  ],
});

function SideNavHeading(props: Props) {
  return (
    <li className="gi-list-none">
      <h5
        id={props.id}
        data-testid={props.dataTestId}
        className={classes({
          class: props.className,
        })}
      >
        {props.children}
      </h5>
    </li>
  );
}

export default SideNavHeading;
