/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/sidenav/SideNav.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  children?: any;
  className?: string;
  styles?: Record<string, string>;
  ariaLabel?: string;
  ariaLabelledBy?: string;
  id?: string;
  dataTestId?: string;
};

function SideNav(props: Props) {
  return (
    <nav
      id={props.id}
      className={props.className}
      style={props.styles}
      aria-label={props.ariaLabel}
      aria-labelledby={props.ariaLabelledBy}
      data-testid={props.dataTestId}
    >
      <ul className="gi-list-none gi-p-0 gi-m-0">{props.children}</ul>
    </nav>
  );
}

export default SideNav;
