/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/CoreH3.lite.tsx`
 */

import * as React from 'react';

import styles from './styles';
import { getSize } from './utils';
import type { Props } from './types';

function CoreH3(props: Props) {
  return (
    <h3
      id={props.id}
      data-testid={props.dataTestId}
      className={styles({
        size: getSize(props.size, 'md'),
        class: props.className,
      })}
    >
      {props.children}
    </h3>
  );
}

export default CoreH3;
