/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/CoreH2.lite.tsx`
 */

import * as React from 'react';

import styles from './styles';
import { getSize } from './utils';
import type { Props } from './types';

function CoreH2(props: Props) {
  return (
    <h2
      id={props.id}
      data-testid={props.dataTestId}
      className={styles({
        size: getSize(props.size, 'lg'),
        class: props.className,
      })}
    >
      {props.children}
    </h2>
  );
}

export default CoreH2;
