/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/H4.lite.tsx`
 */

import * as React from 'react';

import styles from './styles';
import { getSize } from './utils';
import type { Props } from './types';

function H4(props: Props) {
  return (
    <h4
      id={props.id}
      data-testid={props.dataTestId}
      className={styles({
        size: getSize(props.size, 'sm'),
        class: props.className,
      })}
    >
      {props.children}
    </h4>
  );
}

export default H4;
