/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/breadcrumbs/BreadcrumbEllipsis.lite.tsx`
 */

import * as React from 'react';

export type Props = Omit<IconProps, 'label'>;

import GiMoreHorizontalIcon from '../icons/MoreHorizontal';
import listClasses, { moreHorizontalClasses } from './BreadcrumbLink.styles';
import type { IconProps } from '../icons/types';

function BreadcrumbEllipsis(props: Props) {
  return (
    <li className={listClasses()} aria-hidden>
      <GiMoreHorizontalIcon
        id={props.id}
        className={moreHorizontalClasses({
          className: props.className,
        })}
        size={props.size}
        color={props.color}
        dataTestId={props.dataTestId}
      />
    </li>
  );
}

export default BreadcrumbEllipsis;
