/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/breadcrumbs/BreadcrumbEllipsis.lite.tsx`
 */

import * as React from 'react';

export type Props = Omit<IconProps, 'label'>;

import GiMoreHorizontalIcon from '../icons/MoreHorizontal';
import { listItemClasses } from './BreadcrumbLink.styles';
import type { IconProps } from '../icons/types';
import { tv } from 'tailwind-variants';
const classes = tv({
  base: 'gi-text-gray-700 gi-shrink-0',
});

function BreadcrumbEllipsis(props: Props) {
  return (
    <li className={listItemClasses()} aria-hidden>
      <GiMoreHorizontalIcon
        id={props.id}
        className={classes({
          className: props.className,
        })}
        size={props.size}
        color={props.color}
        dataTestId={props.dataTestId}
      />
    </li>
  );
}

export default BreadcrumbEllipsis;
