/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/storybook/SideNavItem.meta.ts`
 */

import type { ArgTypes, StoryContext, Renderer } from 'storybook/internal/types';
import { within } from 'storybook/test';
import type { Props } from '../sidenav/SideNavItem.vue';
import { boxMeta } from './Box.meta';
import { linkMeta } from './Link.meta';
import { checker } from './utilities';
import { buttonMeta } from './Button.meta';
export const sideNavItemMeta = {
  title: 'Navigation/SideNav/SideNavItem',
  args: {
    children: 'Overview',
    selected: false,
    disabled: false,
    id: 'side-nav-item-id',
    dataTestId: 'side-nav-item',
  },
  argTypes: {
    selected: {
      control: 'boolean',
      description: 'Marks the item as the current selection. Applies the selected accent treatment.',
      table: {
        type: {
          summary: 'boolean',
        },
        defaultValue: {
          summary: 'false',
        },
      },
    },
    disabled: buttonMeta.argTypes.disabled,
    actions: {
      control: {
        disable: true,
      },
      description: 'Trailing action slot rendered beside the item (for example an IconButton). ',
    },
    onClick: {
      action: 'clicked',
      description: 'Click handler for the item.',
      table: {
        type: {
          summary: '(event) => void',
        },
      },
    },
    onKeyDown: {
      action: 'keydown',
      description: 'Key down handler for the item.',
      table: {
        type: {
          summary: '(event) => void',
        },
      },
    },
    onKeyUp: {
      action: 'keyup',
      description: 'Key up handler for the item.',
      table: {
        type: {
          summary: '(event) => void',
        },
      },
    },
    onFocus: {
      action: 'focus',
      description: 'Focus handler for the item.',
      table: {
        type: {
          summary: '(event) => void',
        },
      },
    },
    onBlur: {
      action: 'blur',
      description: 'Blur handler for the item.',
      table: {
        type: {
          summary: '(event) => void',
        },
      },
    },
    className: buttonMeta.argTypes.className,
    styles: boxMeta.argTypes.styles,
    id: boxMeta.argTypes.id,
    ariaLabel: {
      control: 'text',
      description: 'Accessible label for the item button. Maps to `aria-label`.',
      table: {
        type: {
          summary: 'string',
        },
      },
    },
    ariaCurrent: linkMeta.argTypes.ariaCurrent,
    ariaHidden: {
      control: {
        disable: true,
      },
      description: 'Hides the list item from assistive technology. Maps to `aria-hidden` on the wrapping `<li>`.',
      table: {
        type: {
          summary: "boolean | 'true' | 'false'",
        },
      },
    },
    tabIndex: {
      control: {
        disable: true,
      },
      description: 'Overrides the default tab order. Automatically set to `-1` when `ariaHidden` is true.',
      table: {
        type: {
          summary: 'number',
        },
      },
    },
    dataTestId: boxMeta.argTypes.dataTestId,
  } satisfies ArgTypes<Props>,
  parameters: {
    docs: {
      description: {
        component:
          'Button-style navigation item for SideNav. Use for destinations that select in place rather than navigating to a URL. Nest inside `SideNav` or `SideNavGroup`.',
      },
    },
  },
};
export const Default = {
  args: sideNavItemMeta.args,
  play: async ({ canvasElement, step, args }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    const check = checker(args.dataTestId, canvas, step);
    await check.is('button');
    await check.attributes({
      id: args.id,
    });
    await check.children();
  },
};
export const Selected = {
  args: {
    ...sideNavItemMeta.args,
    selected: true,
    ariaCurrent: 'page' as const,
    dataTestId: 'side-nav-item-selected',
    id: 'side-nav-item-selected-id',
  },
  play: async ({ canvasElement, step, args }: StoryContext<Renderer>) => {
    const canvas = within(canvasElement as HTMLElement);
    const check = checker(args.dataTestId, canvas, step);
    await check.is('button');
    await check.attributes({
      'aria-current': 'page',
    });
    await check.children();
  },
};
