/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/pagination/PaginationButton.lite.tsx`
 */

import * as React from 'react';

type Props = {
  current?: boolean;
  id?: string;
  className?: string;
  children: any;
  disabled?: boolean;
  onClick?: (event: any) => void;
  onFocus?: (event: any) => void;
  onBlur?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
  ariaLabel?: string;
};

import Button from '../Button';

function PaginationButton(props: Props) {
  return (
    <li>
      <Button
        size="lg"
        appearance="dark"
        id={props.id}
        className={props.className}
        variant={props.current ? 'primary' : 'flat'}
        disabled={props.disabled}
        ariaLabel={props.ariaLabel}
        ariaCurrent={props.current}
        onClick={(event) => props.onClick && props.onClick(event)}
        onFocus={(event) => props.onFocus && props.onFocus(event)}
        onBlur={(event) => props.onBlur && props.onBlur(event)}
        onKeyDown={(event) => props.onKeyDown && props.onKeyDown(event)}
        onKeyUp={(event) => props.onKeyUp && props.onKeyUp(event)}
      >
        {props.children}
      </Button>
    </li>
  );
}

export default PaginationButton;
