/**
 * THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
 * Generated by: pnpm generate
 * Source: packages/design/svgs/scripts/generate.ts
 */

export { FaviconDark, type FaviconDarkProps } from './FaviconDark.js';
export { FaviconLight, type FaviconLightProps } from './FaviconLight.js';