/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/breadcrumbs/BreadcrumbLink.lite.tsx`
 */

import { Output, EventEmitter, Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  href: string;
  current?: boolean;
  className?: string;
  styles?: Record<string, string>;
  ariaLabel?: string;
  ariaHidden?: boolean;
  ariaLabelledBy?: string;
  ariaDescribedBy?: string;
  dataTestId?: string;
  onClick?: (event: any) => void;
  onKeyDown?: (event: any) => void;
  onKeyUp?: (event: any) => void;
};
const defaultProps: any = { ariaHidden: undefined };

import listClasses, { linkClasses } from './BreadcrumbLink.styles';

@Component({
  selector: 'gi-breadcrumb-link',
  template: `
    <li [class]="listClasses()" [attr.aria-hidden]="ariaHidden">
      <a
        [attr.id]="id"
        [attr.href]="href"
        [class]="
          linkClasses({
            className: className,
          })
        "
        [ngStyle]="styles"
        (click)="onClick && this.onClick.emit($event)"
        (keydown)="onKeyDown && this.onKeyDown.emit($event)"
        (keyup)="onKeyUp && this.onKeyUp.emit($event)"
        [attr.aria-current]="current ? 'page' : undefined"
        [attr.aria-label]="ariaLabel"
        [attr.aria-labelledby]="ariaLabelledBy"
        [attr.aria-describedby]="ariaDescribedBy"
        [attr.data-testid]="dataTestId"
        ><ng-content></ng-content
      ></a>
    </li>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class BreadcrumbLink {
  listClasses = listClasses;
  linkClasses = linkClasses;

  @Input() ariaHidden: Props['ariaHidden'] = defaultProps['ariaHidden'];
  @Input() id!: Props['id'];
  @Input() href!: Props['href'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() current!: Props['current'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() ariaDescribedBy!: Props['ariaDescribedBy'];
  @Input() dataTestId!: Props['dataTestId'];
  @Output() onClick = new EventEmitter<any>();
  @Output() onKeyDown = new EventEmitter<any>();
  @Output() onKeyUp = new EventEmitter<any>();
}
