/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/breadcrumbs/Breadcrumbs.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

export type Props = {
  id?: string;
  className?: string;
  styles?: Record<string, string>;
  ariaLabel?: string;
  ariaLabelledBy?: string;
  dataTestId?: string;
};

import { parentList } from './BreadcrumbLink.styles';

@Component({
  selector: 'gi-breadcrumbs',
  template: `
    <nav
      [attr.id]="id"
      [class]="className"
      [ngStyle]="styles"
      [attr.aria-label]="ariaLabel"
      [attr.aria-labelledby]="ariaLabelledBy"
      [attr.data-testid]="dataTestId"
    >
      <ol [class]="parentList()">
        <ng-content></ng-content>
      </ol>
    </nav>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Breadcrumbs {
  parentList = parentList;

  @Input() id!: Props['id'];
  @Input() className!: Props['className'];
  @Input() styles!: Props['styles'];
  @Input() ariaLabel!: Props['ariaLabel'];
  @Input() ariaLabelledBy!: Props['ariaLabelledBy'];
  @Input() dataTestId!: Props['dataTestId'];
}
