/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/FilterList.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

import { IconProps } from './types';

@Component({
  selector: 'gi-filter-list-icon',
  template: `
    <svg
      viewBox="0 -960 960 960"
      xmlns="http://www.w3.org/2000/svg"
      [attr.width]="size ?? 24"
      [attr.height]="size ?? 24"
      [class]="className"
      [attr.id]="id"
      [attr.role]="label ? 'img' : undefined"
      [attr.aria-label]="label"
      [attr.aria-hidden]="!label"
      [attr.fill]="color ?? 'currentColor'"
      [attr.data-testid]="dataTestId ?? 'filter-list'"
    >
      <path d="M400-240v-80h160v80H400ZM240-440v-80h480v80H240ZM120-640v-80h720v80H120Z"></path>
    </svg>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class FilterList {
  @Input() size!: IconProps['size'];
  @Input() className!: IconProps['className'];
  @Input() id!: IconProps['id'];
  @Input() label!: IconProps['label'];
  @Input() color!: IconProps['color'];
  @Input() dataTestId!: IconProps['dataTestId'];
}
