/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Home.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

import { IconProps } from './types';

@Component({
  selector: 'gi-home-icon',
  template: `
    <svg
      viewBox="0 -960 960 960"
      xmlns="http://www.w3.org/2000/svg"
      [attr.width]="size ?? 24"
      [attr.height]="size ?? 24"
      [class]="className"
      [attr.id]="id"
      [attr.role]="label ? 'img' : undefined"
      [attr.aria-label]="label"
      [attr.aria-hidden]="!label"
      [attr.fill]="color ?? 'currentColor'"
      [attr.data-testid]="dataTestId ?? 'home'"
    >
      <path
        d="M240-200h120v-240h240v240h120v-360L480-740 240-560v360Zm-80 80v-480l320-240 320 240v480H520v-240h-80v240H160Zm320-350Z"
      ></path>
    </svg>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Home {
  @Input() size!: IconProps['size'];
  @Input() className!: IconProps['className'];
  @Input() id!: IconProps['id'];
  @Input() label!: IconProps['label'];
  @Input() color!: IconProps['color'];
  @Input() dataTestId!: IconProps['dataTestId'];
}
