/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/KeyboardArrowUp.lite.tsx`
 */

import { Component, Input } from "@angular/core";

import { CommonModule } from "@angular/common";

import { IconProps } from "./types";

@Component({
  selector: "keyboard-arrow-up",
  template: `
    <svg
      viewBox="0 -960 960 960"
      xmlns="http://www.w3.org/2000/svg"
      [attr.width]="size ?? 24"
      [attr.height]="size ?? 24"
      [class]="className"
      [attr.id]="id"
      [attr.role]="label ? 'img' : undefined"
      [attr.aria-label]="label"
      [attr.aria-hidden]="!label"
      [attr.fill]="color ?? 'currentColor'"
      [attr.data-testid]="dataTestId ?? 'keyboard_arrow_up'"
    >
      <path d="M480-528 296-344l-56-56 240-240 240 240-56 56-184-184Z"></path>
    </svg>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class KeyboardArrowUp {
  @Input() size!: IconProps["size"];
  @Input() className!: IconProps["className"];
  @Input() id!: IconProps["id"];
  @Input() label!: IconProps["label"];
  @Input() color!: IconProps["color"];
  @Input() dataTestId!: IconProps["dataTestId"];
}

