/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Upload.lite.tsx`
 */

import { Component, Input } from '@angular/core';

import { CommonModule } from '@angular/common';

import { IconProps } from './types';

@Component({
  selector: 'gi-upload-icon',
  template: `
    <svg
      viewBox="0 -960 960 960"
      xmlns="http://www.w3.org/2000/svg"
      [attr.width]="size ?? 24"
      [attr.height]="size ?? 24"
      [class]="className"
      [attr.id]="id"
      [attr.role]="label ? 'img' : undefined"
      [attr.aria-label]="label"
      [attr.aria-hidden]="!label"
      [attr.fill]="color ?? 'currentColor'"
      [attr.data-testid]="dataTestId ?? 'upload'"
    >
      <path
        d="M440-320v-326L336-542l-56-58 200-200 200 200-56 58-104-104v326h-80ZM240-160q-33 0-56.5-23.5T160-240v-120h80v120h480v-120h80v120q0 33-23.5 56.5T720-160H240Z"
      ></path>
    </svg>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class Upload {
  @Input() size!: IconProps['size'];
  @Input() className!: IconProps['className'];
  @Input() id!: IconProps['id'];
  @Input() label!: IconProps['label'];
  @Input() color!: IconProps['color'];
  @Input() dataTestId!: IconProps['dataTestId'];
}
