/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/VisibilityOff.lite.tsx`
 */

import { Component, Input } from "@angular/core";

import { CommonModule } from "@angular/common";

import { IconProps } from "./types";

@Component({
  selector: "visibility-off",
  template: `
    <svg
      viewBox="0 -960 960 960"
      [attr.width]="size ?? 24"
      [attr.height]="size ?? 24"
      [class]="className"
      [attr.id]="id"
      [attr.data-testid]="dataTestId"
      [attr.role]="role"
      [attr.aria-label]="ariaLabel"
      [attr.aria-hidden]="ariaHidden ?? 'true'"
      [attr.fill]="color ?? 'currentColor'"
    >
      <path
        d="m644-428-58-58q9-47-27-88t-93-32l-58-58q17-8 34.5-12t37.5-4q75 0 127.5 52.5T660-500q0 20-4 37.5T644-428Zm128 126-58-56q38-29 67.5-63.5T832-500q-50-101-143.5-160.5T480-720q-29 0-57 4t-55 12l-62-62q41-17 84-25.5t90-8.5q151 0 269 83.5T920-500q-23 59-60.5 109.5T772-302Zm20 246L624-222q-35 11-70.5 16.5T480-200q-151 0-269-83.5T40-500q21-53 53-98.5t73-81.5L56-792l56-56 736 736-56 56ZM222-624q-29 26-53 57t-41 67q50 101 143.5 160.5T480-280q20 0 39-2.5t39-5.5l-36-38q-11 3-21 4.5t-21 1.5q-75 0-127.5-52.5T300-500q0-11 1.5-21t4.5-21l-84-82Zm319 93Zm-151 75Z"
      ></path>
    </svg>
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  standalone: true,
  imports: [CommonModule],
})
export default class VisibilityOff {
  @Input() size!: IconProps["size"];
  @Input() className!: IconProps["className"];
  @Input() id!: IconProps["id"];
  @Input() dataTestId!: IconProps["dataTestId"];
  @Input() role!: IconProps["role"];
  @Input() ariaLabel!: IconProps["ariaLabel"];
  @Input() ariaHidden!: IconProps["ariaHidden"];
  @Input() color!: IconProps["color"];
}

