/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/constants.ts`
 */

export type ValueOf<T> = T[keyof T];
export type BreakpointKey = ValueOf<typeof Breakpoint>;
export type ResponsiveValue<T> = T | Partial<Record<BreakpointKey, T>>;
export type SpacingScale = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
export const Size = {
  SM: 'sm',
  MD: 'md',
  LG: 'lg',
  XL: 'xl',
} as const;
export const Whitespace = {
  NORMAL: 'normal',
  PRE: 'pre',
  PRE_WRAP: 'pre-wrap',
  BREAK_SPACES: 'break-spaces',
} as const;
export const Align = {
  START: 'start',
  CENTER: 'center',
  END: 'end',
  JUSTIFY: 'justify',
} as const;
export const Direction = {
  ROW: 'row',
  COLUMN: 'column',
} as const;
export const Orientation = {
  HORIZONTAL: 'horizontal',
  VERTICAL: 'vertical',
} as const;
export const AlignItems = {
  START: 'start',
  CENTER: 'center',
  END: 'end',
  STRETCH: 'stretch',
  BASELINE: 'baseline',
} as const;
export const Justify = {
  START: 'start',
  CENTER: 'center',
  END: 'end',
  BETWEEN: 'between',
  AROUND: 'around',
  EVENLY: 'evenly',
} as const;
export const Breakpoint = {
  BASE: 'base',
  XS: 'xs',
  SM: 'sm',
  MD: 'md',
  LG: 'lg',
  XL: 'xl',
  '2XL': '2xl',
} as const;

// A surface (banded zone / region / panel) has a role variant and a theme appearance.
export const SurfaceVariant = {
  PRIMARY: 'primary',
  UTILITY: 'utility',
} as const;

// Theme of a surface (band / region / panel). Descendants inherit its tone.
export const SurfaceAppearance = {
  DEFAULT: 'default',
  LIGHT: 'light',
} as const;

// Tone of an element itself (Button/Link) — the inverse case (dark element on a light
// surface, light on dark). Shared vocabulary; Button/Link own this, not surfaces.
export const Appearance = {
  DEFAULT: 'default',
  DARK: 'dark',
  LIGHT: 'light',
} as const;
