/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Container.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  id?: string;
  children?: any;
  className?: string;
  inset?: boolean;
  gutters?: boolean;
  maxWidth?: (typeof MaxWidth)[keyof typeof MaxWidth];
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import { clamp, Size } from './utilities';
export const MaxWidth = {
  ...Size,
  '2xl': '2xl',
  full: 'full',
  screen: 'screen',
} as const;
export const styles = tv({
  base: 'gi-w-full gi-container md:gi-mx-auto',
  variants: {
    inset: {
      true: 'gi-mx-auto gi-py-4 md:gi-py-6 lg:gi-py-8',
    },
    gutters: {
      true: 'gi-px-4 md:gi-px-6 lg:gi-px-8',
      false: 'gi-px-0',
    },
    maxWidth: {
      sm: 'gi-max-w-sm',
      md: 'gi-max-w-md',
      lg: 'gi-max-w-lg',
      xl: 'gi-max-w-xl',
      '2xl': 'gi-max-w-2xl',
      full: 'gi-max-w-full',
      screen: 'gi-max-w-[100vw]',
    },
  },
  defaultVariants: {
    inset: false,
    gutters: true,
    maxWidth: MaxWidth.screen,
  },
});

function Container(props: Props) {
  return (
    <div
      className={styles({
        inset: props.inset ?? false,
        gutters: props.gutters ?? true,
        maxWidth: clamp(props.maxWidth, MaxWidth, MaxWidth.screen),
        class: props.className,
      })}
      id={props.id}
      data-testid={props.dataTestId}
    >
      {props.children}
    </div>
  );
}

export default Container;
