/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Container.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  inset?: boolean;
  gutters?: boolean;
  maxWidth?: (typeof MaxWidth)[keyof typeof MaxWidth];
} & LayoutBaseProps;

import { tv } from 'tailwind-variants';
import { clamp } from './utilities';
import { Size, LayoutBaseProps } from './constants';
export const MaxWidth = {
  ...Size,
  default: 'default',
  '2xl': '2xl',
  full: 'full',
} as const;
export const containerStyles = tv({
  base: 'gi-container gi-mx-auto',
  variants: {
    inset: {
      true: 'gi-py-4 md:gi-py-6 lg:gi-py-8',
    },
    gutters: {
      false: 'gi-px-0', // gi-container override
    },
    maxWidth: {
      default: 'gi-max-w-full 2xl:gi-max-w-screen-2xl',
      // defaults to gi-container
      sm: 'gi-max-w-screen-sm',
      // 640px
      md: 'gi-max-w-screen-md',
      // 768px
      lg: 'gi-max-w-screen-lg',
      // 1024px
      xl: 'gi-max-w-screen-xl',
      // 1280px
      '2xl': 'gi-max-w-screen-2xl',
      // 1536px
      full: 'gi-max-w-full', // parent 100%
    },
  },
  defaultVariants: {
    inset: false,
    gutters: true,
    maxWidth: 'default',
  },
});

function Container(props: Props) {
  return (
    <div
      id={props.id}
      role={props.role}
      aria-label={props.role ? props.ariaLabel : undefined}
      aria-labelledby={props.role ? props.ariaLabelledBy : undefined}
      style={props.styles}
      data-testid={props.dataTestId}
      className={containerStyles({
        inset: props.inset ?? false,
        gutters: props.gutters ?? true,
        maxWidth: clamp(props.maxWidth, MaxWidth, MaxWidth.default),
        class: props.className,
      })}
    >
      {props.children}
    </div>
  );
}

export default Container;
