/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Container.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  inset?: boolean;
  gutters?: boolean;
  maxWidth?: ValueOf<typeof MaxWidth>;
} & BoxProps;

import { tv } from 'tailwind-variants';
import { MaxWidth } from './constants';
import type { ValueOf } from './constants';
import { clamp } from './utilities';
import type { Props as BoxProps } from './Box';
import GiBox from './Box';
const getMaxWidth = (x: Props['maxWidth']) => clamp(x, MaxWidth, MaxWidth.DEFAULT);
const classes = tv({
  base: 'gi-container gi-mx-auto',
  variants: {
    inset: {
      true: 'gi-py-4 md:gi-py-6 lg:gi-py-8',
    },
    gutters: {
      false: 'gi-px-0',
    },
    maxWidth: {
      default: 'gi-max-w-full 2xl:gi-max-w-screen-2xl',
      sm: 'gi-max-w-screen-sm',
      md: 'gi-max-w-screen-md',
      lg: 'gi-max-w-screen-lg',
      xl: 'gi-max-w-screen-xl',
      '2xl': 'gi-max-w-screen-2xl',
      full: 'gi-max-w-full',
    },
  },
  defaultVariants: {
    inset: false,
    gutters: true,
    maxWidth: MaxWidth.DEFAULT,
  },
});

function Container(props: Props) {
  props = { inset: false, gutters: true, ...props };
  return (
    <GiBox
      id={props.id}
      role={props.role}
      ariaLabel={props.ariaLabel}
      ariaLabelledBy={props.ariaLabelledBy}
      styles={props.styles}
      dataTestId={props.dataTestId}
      className={classes({
        inset: props.inset,
        gutters: props.gutters,
        maxWidth: getMaxWidth(props.maxWidth),
        className: props.className,
      })}
    >
      {props.children}
    </GiBox>
  );
}

export default Container;
