/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Divider.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  orientation?: ValueOf<typeof Orientation>;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

import type { Orientation, ValueOf } from './constants';
import { getOrientation } from './utilities';
import classes from './Divider.styles';

function Divider(props: Props) {
  return (
    <hr
      id={props.id}
      data-testid={props.dataTestId}
      aria-orientation={getOrientation(props.orientation)}
      className={classes({
        orientation: getOrientation(props.orientation),
        className: props.className,
      })}
      style={props.styles}
    />
  );
}

export default Divider;
