/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/FooterLogo.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  children: any;
  id?: string;
  className?: string;
  styles?: Record<string, string>;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import GiBox from './Box';
const footerStyles = tv({
  base: 'gi-w-fit md:gi-ml-auto gi-mt-8 md:gi-mt-0',
});

function FooterLogo(props: Props) {
  return (
    <GiBox
      id={props.id}
      className={footerStyles({
        class: props.className,
      })}
      styles={props.styles}
      dataTestId={props.dataTestId}
    >
      {props.children}
    </GiBox>
  );
}

export default FooterLogo;
