/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/FooterLogo.lite.tsx`
 */

import * as React from 'react';

type Props = {
  children: any;
  id?: string;
  className?: string;
  dataTestId?: string;
  ariaLabel?: string;
};

import { tv } from 'tailwind-variants';
import GiBox from './Box';
const footerLogoStyles = tv({
  base: 'gi-min-w-fit md:gi-ml-auto gi-mt-8 md:gi-mt-0',
});

function FooterLogo(props: Readonly<Props>) {
  return (
    <GiBox
      id={props.id}
      className={footerLogoStyles({
        class: props.className,
      })}
      data-testid={props.dataTestId}
    >
      {props.children}
    </GiBox>
  );
}

export default FooterLogo;
