/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/FooterLogo.lite.tsx`
 */

import * as React from 'react';

type Props = {
  children: any;
  href?: string;
  id?: string;
  className?: string;
  dataTestId?: string;
  ariaLabel?: string;
};

import { tv } from 'tailwind-variants';
import Box from './Box';
const footerLogoStyles = tv({
  base: 'gi-min-w-fit md:gi-ml-auto md:gi-mt-0',
  variants: {
    asLink: {
      true: [
        'focus:gi-rounded-sm',
        'focus:gi-shadow-[0_0_0_2px_var(--gieds-color-gray-950),0_0_0_5px_var(--gieds-color-yellow-400)]',
        'focus-visible:gi-shadow-[0_0_0_2px_var(--gieds-color-gray-950),0_0_0_5px_var(--gieds-color-yellow-400)]',
        'focus-visible:gi-outline-none',
        'focus-visible:gi-rounded-sm',
      ],
      false: '',
    },
  },
});

function FooterLogo(props: Readonly<Props>) {
  return (
    <>
      {props.href ? (
        <>
          <a
            href={props.href}
            id={props.id}
            aria-label={props.ariaLabel}
            data-testid={props.dataTestId}
            className={footerLogoStyles({
              asLink: true,
              class: props.className,
            })}
          >
            {props.children}
          </a>
        </>
      ) : (
        <Box
          id={props.id}
          className={footerLogoStyles({
            asLink: false,
            class: props.className,
          })}
          data-testid={props.dataTestId}
        >
          {props.children}
        </Box>
      )}
    </>
  );
}

export default FooterLogo;
