/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Footer.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  ariaLabel?: string;
  ariaLabelledBy?: string;
  children?: any;
  className?: string;
  styles?: Record<string, string>;
  id?: string;
  dataTestId?: string;
};

function Footer(props: Props) {
  return (
    <footer
      id={props.id}
      className={props.className}
      style={props.styles}
      aria-label={props.ariaLabel}
      aria-labelledby={props.ariaLabelledBy}
      data-testid={props.dataTestId}
    >
      {props.children}
    </footer>
  );
}

export default Footer;
