/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Grid.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  container?: boolean;
  columns?: ResponsiveValue<SpacingScale>;
  gap?: ResponsiveValue<SpacingScale>;
  size?: ResponsiveValue<SpacingScale>;
} & BoxProps;

import type { ResponsiveValue, SpacingScale } from './constants';
import type { Props as BoxProps } from './Box';
import classes from './Grid.styles';
import CoreBox from './Box';

function Grid(props: Props) {
  return (
    <CoreBox
      id={props.id}
      role={props.role}
      ariaLabel={props.ariaLabel}
      ariaLabelledBy={props.ariaLabelledBy}
      styles={props.styles}
      className={classes({
        container: props.container,
        columns: props.columns,
        gap: props.gap,
        size: props.size,
        className: props.className,
      })}
      dataTestId={props.dataTestId}
    >
      {props.children}
    </CoreBox>
  );
}

export default Grid;
