/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/Grid.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  container?: boolean;
  columns?: ResponsiveValue<number>;
  gap?: ResponsiveValue<number>;
  size?: ResponsiveValue<number>;
  role?: 'region' | 'navigation' | 'complementary' | 'search' | 'form';
  ariaLabel?: string;
  ariaLabelledBy?: string;
  className?: string;
  id?: string;
  dataTestId?: string;
  children: any;
};

import _ from 'lodash';
import type { ResponsiveValue, BreakpointKey } from './constants';
const buildGridClasses = (value: ResponsiveValue<number> | undefined, prefix: string, min: number): string => {
  if (_.isNumber(value)) {
    return `${prefix}-${Math.max(min, value)}`;
  }
  if (!_.isPlainObject(value)) {
    return '';
  }
  const responsive = value as Partial<Record<BreakpointKey, number>>;
  return (_.keys(responsive) as BreakpointKey[])
    .map((bp) => {
      const clamped = Math.max(min, responsive[bp] as number);
      if (bp === 'base') {
        return `${prefix}-${clamped}`;
      }
      return `${prefix}-${bp}-${clamped}`;
    })
    .join(' ');
};

function Grid(props: Props) {
  return (
    <div
      id={props.id}
      role={props.role}
      aria-label={props.role ? props.ariaLabel : undefined}
      aria-labelledby={props.role ? props.ariaLabelledBy : undefined}
      className={`${props.className || ''} ${props.container ? `gi-grid-container ${buildGridClasses(props.columns, 'gi-grid-columns', 1)} ${buildGridClasses(props.gap, 'gi-grid-gap', 0)}` : `gi-grid-item ${buildGridClasses(props.size, 'gi-grid-span', 1)}`}`}
      data-testid={props.dataTestId}
    >
      {props.children}
    </div>
  );
}

export default Grid;
