/**
 * Mitosis automatically generates this file.
 * Do not edit this file directly.
 * The file source is in `packages/core/atoms/HeaderNavItemSeparator.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  className?: string;
  id?: string;
  dataTestId?: string;
};

import { tv } from 'tailwind-variants';
import { dividerStyles } from './Divider';
const separatorStyles = tv({
  extend: dividerStyles,
  base: 'gi-h-8 gi-mx-2 gi-self-center',
  defaultVariants: {
    orientation: 'vertical',
  },
});

function HeaderNavItemSeparator(props: Props) {
  return (
    <li
      role="none"
      aria-hidden="true"
      id={props.id}
      className={separatorStyles({
        className: props.className,
      })}
      data-testid={props.dataTestId}
    />
  );
}

export default HeaderNavItemSeparator;
