/*
  Mitosis automatically generates this file.
  Do not edit this file directly.
  The file source is in `packages/core/atoms/Stack.lite.tsx`
 */

import * as React from 'react';

export type Props = {
  direction?: ResponsiveValue<ValueOf<typeof Direction>>;
  gap?: ResponsiveValue<SpacingScale>;
  align?: ValueOf<typeof AlignItems>;
  justify?: ValueOf<typeof Justify>;
  wrap?: boolean;
} & BoxProps;

import type { AlignItems, Direction, Justify, ResponsiveValue, SpacingScale, ValueOf } from './constants';
import type { Props as BoxProps } from './Box';
import { getAlignItems, getJustify } from './utilities';
import classes, { getDirectionClasses, getGapClasses } from './Stack.styles';
import CoreBox from './Box';

function Stack(props: Props) {
  return (
    <CoreBox
      id={props.id}
      role={props.role}
      ariaLabel={props.ariaLabel}
      ariaLabelledBy={props.ariaLabelledBy}
      styles={props.styles}
      className={classes({
        align: getAlignItems(props.align),
        justify: getJustify(props.justify),
        wrap: !!props.wrap,
        className: [getDirectionClasses(props.direction), getGapClasses(props.gap), props.className],
      })}
      dataTestId={props.dataTestId}
    >
      {props.children}
    </CoreBox>
  );
}

export default Stack;
