name: Chromatic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

concurrency:
  group: chromatic-${{ github.ref }}
  cancel-in-progress: true

jobs:
  determine-affected:
    runs-on: ubuntu-latest
    outputs:
      html_affected: ${{ steps.check-affected.outputs.html_affected }}
      react_affected: ${{ steps.check-affected.outputs.react_affected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Determine affected projects
        id: affected
        run: |
          pnpm nx show projects --affected --base=main --head=HEAD > affected.txt
          cat affected.txt

      - name: Set environment output if HTML package is affected
        id: check-html-affected
        run: |
          if grep -q "@govie-frontend/storybook" affected.txt; then
            echo "html_affected=true" >> $GITHUB_ENV
            echo "::set-output name=html_affected::true"
          else
            echo "html_affected=false" >> $GITHUB_ENV
            echo "::set-output name=html_affected::false"
          fi
      - name: Set environment output if HTML package is affected
        id: check-react-affected
        run: |
          if grep -q "@govie-react/storybook" affected.txt; then
            echo "react_affected=true" >> $GITHUB_ENV
            echo "::set-output name=react_affected::true"
          else
            echo "react_affected=false" >> $GITHUB_ENV
            echo "::set-output name=react_affected::false"
          fi

  chromatic:
    runs-on: ubuntu-latest
    environment: dev
    needs: determine-affected
    if: ${{ needs.determine-affected.outputs.html_affected == 'true' || needs.determine-affected.outputs.react_affected == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Storybook build
        if: ${{ needs.determine-affected.outputs.html_affected == 'true' }}
        run: pnpm html:storybook:build

      - name: Publish Global HTML Library to Chromatic
        if: ${{ needs.determine-affected.outputs.html_affected == 'true' }}
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_HTML }}
          storybookBuildDir: packages/html/storybook/storybook-static
          autoAcceptChanges: "main"

      - name: Storybook build
        if: ${{ needs.determine-affected.outputs.react_affected == 'true' }}
        run: pnpm react:storybook:build

      - name: Publish React Library to Chromatic
        if: ${{ needs.determine-affected.outputs.react_affected == 'true' }}
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_REACT }}
          storybookBuildDir: packages/react/storybook/storybook-static
          autoAcceptChanges: "main"
