name: Deploy HTML Storybook to AWS S3

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual deployment trigger
    inputs:
      deploy_reason:
        description: "Select deployment type"
        required: true
        default: "Manual Trigger"

env:
  AWS_S3_BUCKET_NAME: storybook-html-design-system-blocks-gov-ie

jobs:
  determine-affected:
    runs-on: ubuntu-latest
    outputs:
      html_affected: ${{ steps.check-affected.outputs.html_affected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Install Nx CLI
        run: pnpm add -g nx

      - name: Determine affected projects
        id: affected
        run: |
          nx show projects --affected --base=origin/main~1 --head=HEAD > affected.txt
          cat affected.txt

      - name: Set environment output if HTML package is affected
        id: check-affected
        run: |
          if grep -q "@govie-frontend/storybook" affected.txt; then
            echo "html_affected=true" >> $GITHUB_ENV
            echo "::set-output name=html_affected::true"
          else
            echo "html_affected=false" >> $GITHUB_ENV
            echo "::set-output name=html_affected::false"
          fi

  build:
    runs-on: ubuntu-latest
    needs: determine-affected
    # Run if html is affected or manually triggered
    if: ${{ needs.determine-affected.outputs.html_affected == 'true' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Install Nx CLI
        run: pnpm add -g nx

      - name: Storybook build
        run: pnpm html:storybook:build

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-artifact
          path: packages/html/storybook/storybook-static

  deploy:
    name: Deploy to Amazon S3
    runs-on: ubuntu-latest
    needs: build
    # Run if html is affected or manually triggered
    if: ${{ needs.determine-affected.outputs.html_affected == 'true' || github.event_name == 'workflow_dispatch' }}
    permissions:
      id-token: write
      contents: read
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: build-artifact
          path: build

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DS_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy to S3
        run: aws s3 sync build/ s3://$AWS_S3_BUCKET_NAME/
